### ISSUE TITLE
Nonexistent document does not throw `DocumentNotFound` when used with `getJoin`.

### ISSUE THREAD

**Issue by Morgul** [neumino/thinky#105]
When doing a `.get()` on a nonexistent id, thinky throws a `DocumentNotFound` error (as documented [here](http://thinky.io/documentation/api/thinky/#errors)). However, if you use `getJoin()`, it no longer throws that error, instead returns:

```
Error: { [ReqlRuntimeError: Cannot perform merge on a non-object non-sequence `null` in:
r.table("Revision").get("not fount").merge(function(var_4) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        
    return r.branch(var_4.hasFields("commit_id"), r.table("Commit").getAll(var_4("commit_id"), {
        index: "id"
    }).coerceTo("ARRAY").do(function(var_5) {
        return r.branch(var_5.count().eq(1), r.expr("commit").object(var_5.nth(0)), r.branch(var_5.count().eq(0), {

        }, r.error(r.expr("More than one element found for ").add(var_4.coerceTo("STRING")).add(r.expr("for the field ").add("commit")))))
    }), {

    })
})
]
```

I've made a gist to illustrate this:

https://gist.github.com/Morgul/458368871a6a9fe5deb0

**Comment by freak4pc** [comment]
This seems to still happen today in 2.0.x 
This does't catch and goes straight to error.
```
User.get(req.params.uid).then(function(result){
				res.sendOK(result);
			}).catch(thinky.Errors.DocumentNotFound, function(err){
				res.sendNotFound("The requested user does not exist");
				return;
			}).error(function(error){
				res.sendServerError(error);
			});
```

response:
```{"message":"The query did not find a document and returned null in:\nr.table(\"users\").get(\"d0b70945-e1a3-4396-8ae6-e4da06d11005\").default(r.error(\"The query did not find a document and returned null.\"))\n                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ \n","frames":[1]}```

**Comment by neumino** [comment]
You can use `run` before `then` for now and it will work fine.
I haven't overwritten `then` in `thinky`, and calling it will just eventually just call rethinkdbdash's (therefore no validation happen).

**Comment by freak4pc** [comment]
Yup, adding run() deals with it.. 
Maybe there could be a smart way making then forcefully execute run() before itself so it would be thinky-fied ?
