### ISSUE TITLE
[request] Pre save methods

### ISSUE THREAD

**Issue by jcspencer** [neumino/thinky#11]

**Comment by alantrrs** [comment]
Is there a way to see if certain field was modified before saving? 
I'm trying to implement this same logic above for hashing passwords, however I'm not sure how to skip hashing if the password field wasn't modified. 
Basically I'm looking for something equivalent to mongoose's:  ``doc.isModified('password')``

Any thoughts?

**Comment by neumino** [comment]
Hum, no that's not possible at the moment.

**Comment by xfg** [comment]
@alantrrs I ran into the same problem. How did you solve it?

**Comment by alantrrs** [comment]
Unfortunately, for now I ended up querying the document inside the ``pre('save',...)`` hook and comparing the password with the new one.

**Comment by thelamborghinistory** [comment]
Would be indeed nice to have such a modified check on attributes
