### ISSUE TITLE
getAll Method without index

### ISSUE THREAD

**Issue by chrisspiegl** [neumino/thinky#13]
I am just getting to know thinky and wanted to access all the elements in a table via the getAll method.

Why not give the option to just pass an callback to the method and select everything from the table?

**Comment by PantherHawk** [comment]
I'm having trouble processing the result of `.run()` method.  I would like an array containing each table element.  What I receive is a single big clunker.  

`Seed.filter({}).run().then((seeds) => {
    console.log(seeds)`
result:
`[ model {
    id: '68b21e22-2274-484e-b055-e88e06eff12e',
    imagePath: 'http://www.foodandphysique.com/UNIT%20PICS/blog%20pics/seed.png',
    name: 'apples',
    createdAt: { [Function: term] _query: [Object], _r: [Object] } },
  model {
    id: '18d8b612-c9d6-4d3d-bbfe-948c99177bf1',
    imagePath: 'http://www.foodandphysique.com/UNIT%20PICS/blog%20pics/seed.png',
    name: 'oranges',
    createdAt: { [Function: term] _query: [Object], _r: [Object] } },
  model {
    id: 'cf474cbb-bba0-4cd0-8310-a30e7ec5f371',
    imagePath: 'http://www.foodandphysique.com/UNIT%20PICS/blog%20pics/seed.png',
    name: 'bananas',
    createdAt: { [Function: term] _query: [Object], _r: [Object] } },
  model {
    id: 'a18b4ce2-70b4-42d4-be31-ee02f508065d',
    imagePath: 'http://www.foodandphysique.com/UNIT%20PICS/blog%20pics/seed.png',
    name: 'grapes',
    createdAt: { [Function: term] _query: [Object], _r: [Object] } } ]`

**Comment by PantherHawk** [comment]
Hiya!  Big fan of your ORM.

I'm struggling a bit to process the result of `.run()`
This is what my controller looks like: 
`Seed.run().then((seeds) => {
    res.send(seeds)`

When I hit the route I get a 
`Unhandled rejection ReqlDriverError: `toJSON` takes 0 argument`

What would you recommend?
