### ISSUE TITLE
Suggestion: created_at and updated_at values set automatically

### ISSUE THREAD

**Issue by chrisspiegl** [neumino/thinky#16]
I got to know Eloquent from Laravel some time ago and loved the created_at and updated_at timestamp fields that are automatically set by the ORM. Maybe this would be a good idea for Thinky (obviously including a way to switch it on / off).
- created_at: set the first time the model is created. Never to be edited (kinda read-only).
- updated_at: set upon update and should not be updated outside the orm.

**Comment by cur3n4** [comment]
Several ways, for example with a pre save hook:
```
Something.pre('save', function () {
    if (!this.createdOn) {
        this.createdOn = new Date();
    }
    this.updatedOn = new Date();
})
```
