### ISSUE TITLE
Variations of Point type is not converted to `r.point()` when using Model.save

### ISSUE THREAD

**Issue by soplakanets** [neumino/thinky#167]
Example:

```
var Foo = thinky.createModel('Foo', {
  location: "Point"
});

Foo.save({location: [1,2]}....
```

In this example `location` field not get converted to `r.point()` and will be stored as Array, while it will work if you use `new Foo({location: [1,2]}).save...`. It is either that documentation is unclear or a BUG. Also, I did not check if that is also a case for other types.

**Comment by neumino** [comment]
Hello @soplakanets!

Thanks for reporting this. This is actually a bug, I just forgot to implement the syntax `Model.ensureIndex(name, options)`.

**Comment by neumino** [comment]
Sorry, wrong thread. If you're just reading messages via email, I just updated the previous comment.
