### ISSUE TITLE
Documentation unclear on Geospatial indexes

### ISSUE THREAD

**Issue by soplakanets** [neumino/thinky#168]
In order to create a Geo index I did the following:
```
Model.ensureIndex('location', undefined, {geo: true})
```

While it worked for me, I think it is not really clear from documentation. Not sure if it's worth a separate issue on github, but did not know how to communicate it in other way.

**Comment by neumino** [comment]
Hello @soplakanets again!

Thanks for reporting this. This was actually a bug, I just forgot to enable the syntax `Model.ensureIndex(name, options)`.
It was released in 1.15.8

**Comment by soplakanets** [comment]
:thumbsup: Thank you
