### ISSUE TITLE
Model prototype

### ISSUE THREAD

**Issue by davidsteinberger** [neumino/thinky#169]
Is it possible to extend the prototype of a model and call such a function within the `pre`hook? Something like:

    var model = thinky.createModel('ModelName', {
      ...
    });

    model.prototype.expensiveOperation = function() {
      ...
      /*return promise;*/
    }

    model.pre('save', function(next) {
      this.expensiveOperation
      .then(function() {
        next();
      });
    });

**Comment by dave8401** [comment]
I just realized that I can actually use `Model.define(key, fn)`. I think it would still be nice to expose the `prototype` to add setters.

**Comment by marshall007** [comment]
See also #57, I agree for certain situations (like defining setters) virtuals aren't quite enough.
