### ISSUE TITLE
Closing a connection / disconnecting

### ISSUE THREAD

**Issue by chrisfosterelli** [neumino/thinky#174]
Hi there,

Is it possible to close a connection and disconnect from the server? I havn't been able to figure out how this is exposed either in the docs or from the code. If it's not currently exposed, this would be a useful feature to have!

Thanks!

**Comment by neumino** [comment]
If you want to close all the connections, you can use
```
thinky.r.getPool().drain()
```

**Comment by neumino** [comment]
Closing this ticket. Feel free to ask here if you have more questions!

**Comment by chrisfosterelli** [comment]
Sorry for the delay. Thanks @neumino that was exactly what I was looking for!
