### ISSUE TITLE
`this` in `pre('save')` is undefined.

### ISSUE THREAD

**Issue by chrisabrams** [neumino/thinky#177]
I have a piece of code:

    User.pre('save', function(next) {
        console.log("pre save event\n", this)
    })

`this` is undefined. In this scenario, it is the first time I am saving this document. Not sure if that helps.

**Comment by neumino** [comment]
Hum, this seems to work for me.
Are you sure `this` is set to `undefined`?
You are also missing `next()` in your callback.

This works fine for me:
```js
var thinky = require('./lib/thinky.js')({buffer: 1, max: 2});

User = thinky.createModel("users", {id: String});

User.pre('save', function(next) {
    console.log("pre save event");
    console.log(this);
    console.log('----');
    next();
});

var user = new User({id: "someid"});

user.save().then(function() {
    console.log('done');
    process.exit(0)
}).error(function(error) {
    console.log(error);
    process.exit(1)
});
```

Output on stdout:
```
pre save event
{ id: 'someid' }
----
done
```

**Comment by chrisabrams** [comment]
It seems that the issue resolves from another module: https://github.com/6to5/6to5/issues/733

**Comment by jordanh** [comment]
For others running into this issue, see: http://blog.jesusgollonet.com/2015/04/21/this-undefined-es6-arrow-functions/

**Comment by evenfrost** [comment]
@neumino So there is currently no way to use pre hooks with arrow functions? By that I mean to avoid `this` in hook function scope.

Something like this would be great:
```js
Model.pre('save', (doc, next) => {
  // 'doc' is 'this'
});
```

**Comment by evenfrost** [comment]
#481 related.

**Comment by neumino** [comment]
@evenfrost - like mentioned in #481, that's not possible at the moment.

**Comment by evenfrost** [comment]
@neumino is it planned or would you mind accepting a PR implementing this behavior? This way it could be a possible API break though, that's way I'm curious.
