### ISSUE TITLE
.save() promise not firing when using .merge()

### ISSUE THREAD

**Issue by chrisabrams** [neumino/thinky#178]
I'm having a scenario where the promise (or callback) do not fire on `save` when using `merge`. When I look at the promise, it returns this:

    { _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined,
  _boundTo: undefined }

Where in the source code is the promise/callback handled on save? I would like to see what I am doing that is preventing the promise from firing. Not even the error handler triggers.

**Comment by neumino** [comment]
Where the promise returned by `save` is resolved should be here:
https://github.com/neumino/thinky/blob/master/lib/document.js#L1093

Here's the order of the operations:

1. Execute pre-hooks
2. Save belongsTo joined documents
3. Save self
4. Save hasOne and hasMany joined documents
5. Save hasAndBelongsToMany joined documents
6. Save hasAndBelongsToMany links
7. Resolve the promise.

Could you provide a bit more background (or a snippet) on what you are doing?
I just updated the box on wercker to Node 0.12, and all the tests still pass.

**Comment by chrisabrams** [comment]
It ended up being an error in my code :O Thanks for the help though - it was very educational to see how the promise chain works on save!
