### ISSUE TITLE
Consider translating `r.now()` defaults to `new Date()` on the client-side

### ISSUE THREAD

**Issue by marshall007** [neumino/thinky#180]
In cases where you're instantiating models directly, properties that have RQL terms as the default value become problematic. Consider the following schema:

```js
var Model = thinky.createModel('models', {
  id: String,
  last_updated: {
    _type: Date,
    default: r.now()
  }
});
```

If I create a new instance of `Model`, it can't be serialized to JSON without persisting it to the database first because `last_updated` won't be a `Date` object. This is particularly problematic if you're using cursors and need to construct the instances yourself:

```js
Model.execute().then(function(cursor) {
  cursor.each(function(data) {
    var model = new Model(data);
    // if model does not already have `last_updated`
    // it gets set to `r.now()` which can't be serialized
  }
});
```

**Comment by marshall007** [comment]
I'm not sure what the best solution to this would be because if you do intend to save the instance you'd want the RQL term to be evaluated on the server rather than persisting a `Date` object that was created on the client at an arbitrary time.

**Comment by neumino** [comment]
@marshall007 -- Does that work for you?

```
var Model = thinky.createModel('models', {
  id: String,
  last_updated: {
    _type: Date,
    default: function() { return new Date(); }
  }
});
```

`r.now()` has a few properties that new Date() does not have. Typically it will convey the same value in a document even if it's called multiple times.

**Comment by marshall007** [comment]
Yep that'll work for now, thanks! Didn't realize `default` could take a function.
