### ISSUE TITLE
findOne aka uniqueResult

### ISSUE THREAD

**Issue by Tlvenn** [neumino/thinky#182]
Unless I am missing something really obvious, it seems that whenever I am looking for a single document using some filters, the result will always be an array and then I have to access/test the first element. Many ORM usually have a method that would automatically extract that single element and return it instead of the collection.

Common use case is looking up a user by a unique email address for example.

Maybe we could chain a .uniqueResult() that would tell Thinky that it should return the first element of the array. If the array has more than 1 element, it should throw an exception.

**Comment by neumino** [comment]
The only way to enforce  a unique field in rethinkdb is with the primary key.
You can do

```js
var Users = thinky.create('users', { id: String, name: String, ...}
Users.get('<userId>').run(...).then(function(user) {
    // user
})
```

If you are using a secondary index or a filter, you could do:
```js
var Users = thinky.create('users', { id: String, name: String, ...}
Users.getAll('<email>', {index: 'email').nth(0).default(r.error("Document not found")).run(...).then(function(user) {
    // ...
})
```
I guess thinky could create this shortcut by default.

For now, you could also do

```js
Users.defineStatic('uniqueResult', function(sequence) {
    return sequence.nth(0).default(r.error("Document not found"))
});
Users.getAll('<email>', {index: 'email').uniqueResult().run().then(function(user) {
    // ...
})

```

**Comment by Tlvenn** [comment]
Hi Michel,

Thanks for the quick reply.
It would be great to have some kind of shortcut for this use case.

**Comment by Tlvenn** [comment]
One minor correction to the example you posted which did not work for me (sequence is undefined)

````
Users.defineStatic('uniqueResult', function() {
    return this.nth(0).default(r.error("Document not found"))
});
````

Quick related question, how would you throw a thinky.Errors.DocumentNotFound error as default in that case ?

**Comment by Tlvenn** [comment]
For now,I am abusing how thinky query.js  works by using:
````
Users.defineStatic('uniqueResult', function() {
    return this.nth(0).default(r.error("The query did not find a document and returned null."));
});
````
This message being the default message of the thinky.Errors.DocumentNotFound. thinky will return a DocumentNotFound

**Comment by neumino** [comment]
Arg yes, sorry for the mistake earlier. I'll edit my answer.

To access the DocumentNotFound error, you can do

```
var DocumentNotFound = thinky.Errors.DocumentNotFound;
```

**Comment by Tlvenn** [comment]
No worry. As for the DocumentNotFound, I understand how to access it, I am just not sure how to use it with the r.default() function so that the promise in Thinky query.js is rejected with that DocumentNotFound error.

**Comment by neumino** [comment]
Arg sorry. If you want to get a DocumentNotFound error, you can actually just use `default(null)`.
Thinky will catch it as `get` finding nothing, so:

```
Users.defineStatic('uniqueResult', function() {
    return this.nth(0).default(null);
});
```

**Comment by mattlenz** [comment]
Hi @neumino.

I'm trying to implement a query based on a unique index, and uniqueResult looks like what I need.

For example, I'm looking to write queries like so:

```
Users.getAll('user@example.com', { index: 'email' }).nth(0).default(null).run().then(next).catch(next);
```

The issue is that it's throwing `DocumentNotFoundError` (stopping execution), rather than being handled by the promise `catch`.

I'd love to not have to wrap my query in try/catch, but use the promise.

Looks like @acdlite was referring to this in https://github.com/neumino/thinky/issues/187

**Comment by neumino** [comment]
`run` expect a document to be returned. If it finds `null`, it will reject with the `DocumentNotFoundError`. If you don't want to parse the result, you can use `execute`.

On the other hand, you probably want to just call `getAll` and throw an error if the result is empty or has more than 1 user.

**Comment by mattlenz** [comment]
Thanks for clarifying @neumino, and for your work on the library.

I've decoded to ditch `nth(0).default(null)` and instead either check if the result is an empty array (and use `Promise.reject()`), or take the first item off the array.

**Comment by tlvenn** [comment]
Wouldn't it be possible to have another get method, let's say `fetch` that would run implicitly hence preventing any chaining but would actually return null if no record were found ?

Wasn't `_get` suppose to do throw an error but return null instead (the original behavior) ?

**Comment by tlvenn** [comment]
I guess one can easily do:

```

**Comment by neumino** [comment]
`_get` doesn't throw if `null` is returned, but thinky will throw if you use `run` instead of `execute` as `null` is not a valid instance of your model.

**Comment by tlvenn** [comment]
Yes that is what I meant, I want to be able to use this pattern:

```
let model = await Model._get(id).run();
if(model === null) {
   model = await Model.save({...});
} else {
   model.xxx = 'foo';
   await model.save();
}
```

If I use `execute` rather than `run`, it does not return the model anymore.

So in my opinion, when the developer is using `_get`, Thinky shouldn't try to safeguard against chaining on a null value and let it crash if the developer uses it incorrectly. It should be the escape hatch around this behaviour of throwing a DocumentNotFound error.

**Comment by tlvenn** [comment]
For example. I remember that Hibernate (Java ORM) has 2 methods to get a given instance by id. `get()` and `load()`. `get()` is returning null if the document does not exist while `load()` is throwing an error.

The doc for `load()` is stating:
```
You should not use this method to determine if an instance exists (use get() instead). Use this only to retrieve an instance that you assume exists, where non-existence would be an actual error.
```
