### ISSUE TITLE
enforce_missing: true option should allow id to be missing

### ISSUE THREAD

**Issue by mindjuice** [neumino/thinky#185]
I'm using Thinky with the global ``enforce_missing: true`` option.

In addition, I've defined several objects in Thinky with string ids like so:

    var Class = thinky.createModel('Class', {
      id:       type.string(),
      name:     type.string(),
      schoolId: type.string()
    });

When attempting to save a new object, I get an error that ``id`` is not set, which seems odd, since ``id`` is about to get created by Rethink.

I've worked around it by changing the ``id`` definition to the following:

          id:       type.string().options({enforce_missing: false}),

It would be nice to not have to do this all the time, as it's quite verbose.  I can think of two reasonable options:

1. Have Thinky treat **``id``** as a special name and allow it to be missing even when the global ``enforce_missing`` flag is ``true``.

2. Add a new function, ``type.id()``, that is an alias for ``type.string()``, but also sets the ``enforce_missing`` flag to ``false``.

Then I could instead write:

    var Class = thinky.createModel('Class', {
      id:       type.id(),
      name:     type.string(),
      schoolId: type.string()
    });

**Comment by mindjuice** [comment]
On a side note, it took me a while to find the ``enforce_missing`` option.  I was looking for something along the lines of "required" or "optional".  The "missing" nomenclature is a bit non-standard IMO.

**Comment by neumino** [comment]
Adding `type.id()` as `type.string().option({enforce_missing: false})` should be pretty straight forward.

About `enforce_missing` being hard to find, I'm sorry for that. I refactored the way the schema is declared and I was planning to implement `type.string().required()`, `type.string().optional()`, `type.string().removeExtra()` etc... but I just somehow forgot it.
It's reasonably easy to do, so I'll try to get that done in the next few days.

**Comment by mindjuice** [comment]
Sounds great!  The ``.required()`` and ``.optional()`` will be very nice additions.
