### ISSUE TITLE
Incorrect example output for getJoin({_array: false})

### ISSUE THREAD

**Issue by mindjuice** [neumino/thinky#190]
On the thinky documentation page describing the ``_array`` option (http://thinky.io/documentation/api/query/#getjoin), I think the example output is wrong. The code is pasted below:

    Example: Retrieve a user and the number of accounts

    var User = thinky.createModel("User", {
        id: String,
        name: String
    });

    var Account = thinky.createModel("Account", {
        id: String,
        userId: String,
        sold: Number
    });

    User.hasOne(Account, "account", "id", "userId")

    User.get("0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a").getJoin({
      _apply: function(seq) { return seq.count() },
      _array: false
    }).run().then(function(user) {

        /*
         * user = {
         *     id: "0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a",
         *     name: "Michel",
         *     account: {
         *         id: "3851d8b4-5358-43f2-ba23-f4d481358901",
         *         userId: "0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a",
         *         sold: 2420
         *     }
         * }
         */
    });

My understanding is that ``account`` should be set to the number of accounts, which should be ``1``, since this is a ``hasOne()`` relationship.

The output should be as below:

    /*
     * user = {
     *     id: "0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a",
     *     name: "Michel",
     *     account: 1
     * }
     */

**Comment by neumino** [comment]
Thanks for the report. Just pushed a fix for that :)

**Comment by Tlvenn** [comment]
FYI, The online doc does not reflect the fix yet.

**Comment by neumino** [comment]
Sorry for that, it should be fixed this time.
