### ISSUE TITLE
Documentation for type.string().email() has a typo

### ISSUE THREAD

**Issue by mindjuice** [neumino/thinky#191]
The documentation at the following link has a typo:

* http://thinky.io/documentation/schemas/

The arguments for ``regex()`` seem to have been copied/pasted for ``email()``.

    regex(regex[, flags]): requires the string to match the given regex
    email(regex[, flags]): requires the string to be an email

The ``email()`` function does not require any arguments.

**Comment by neumino** [comment]
Thanks again @mindjuice -- fix coming
