### ISSUE TITLE
Join on array with hasAndBelongsToMany question

### ISSUE THREAD

**Issue by jschill** [neumino/thinky#196]
I dont really get the Thinky hasAndBelongsToMany().

This is my setup:

Book = thinky.createModel(’Book', {
	id: String,
	title: String,
	description: String,
	meta: {
		author: [String]
	}
});

BookAuthor = thinky.createModel(’BookAuthor', {
	id: String,
	name: String,
	url: String
});

// Define relation
BookAuthor.hasAndBelongsToMany(Book, 'books', 'id', 'meta_author’); // meta_author is a secondary index on meta.author

// Query
BookAuthor.getAll(authorUrl, {index: 'url'}).limit(1).getJoin()

—

Result:

[ { books: [],
    id: '011837a6-766f-461f-906f-8e50e7b8c931',
    name: 'Lorem Ipsum",
    url: 'lorem-ipsum' } ]

So the books.length is always 0, even though i can query the Book-table and see there are results in there. Should i do these types of queries outside of Thinky? Cheers

**Comment by neumino** [comment]
Sorry for the late answer, I was out of town.

Thinky does join in a SQL-ish way with only foreign keys and no nested arrays. 

```
Book = thinky.createModel(’Book', {
  id: String,
  title: String,
  description: String,
});

BookAuthor = thinky.createModel(’BookAuthor', {
  id: String,
  name: String,
  url: String
});

// Define relation
BookAuthor.hasAndBelongsToMany(Book, 'books', 'id', 'id’);

var bookAutor = new BookAuthor({
  name: "foo",
  url: "http://foo.com",
  books: [
    {title: "bar", description: "bar bar"},
    {title: "buzz", description: "buzz buzz"},
  ]
})
bookAutor.saveAll().then(function(result) {
  BookAuthor.get(result.id).getJoin()
})
```

See http://thinky.io/documentation/relations/ and more precisely the "n-n relation" section.
Let me know if you have more questions.

**Comment by chovy** [comment]
I am having same problem. It's always an empty array for me. I can't figure out how to list the join table to see if there is any data in there. It seems to be missing.

**Comment by neumino** [comment]
Under the hood, thinky creates a third table and use it to link the documents the same way you would do in a traditional databases.

If you want to know what relations are saved, you can query this table (named `<model1>_<model2>`)

**Comment by chovy** [comment]
How can I query that table using ReQL? Everything I try returns nothing.

`r.db('mydb').table('Post_Tag').getAll('id')` -- this doesn't work.

**Comment by neumino** [comment]
`r.db('mydb').table('Post_Tag')` should give you all the relations. `getAll('id')` returns all the document for which the primary key value is `id`.

**Comment by chovy** [comment]
`Executed in 6ms. No results returned.`

Can you provide an example of how to actually create a `Post` that has associated `Tag`?

I've just been passing `{ ...., tags: [array of tag objects] }` but that didn't populate the join table.

**Comment by neumino** [comment]
Did you call `saveAll` on your document?
http://thinky.io/documentation/relations/

**Comment by chovy** [comment]
This is what I'm doing:

```
/**
 * post
 * create a post object
 * @param next
 */
ctrl.post = function *(next){
  var data = this.request.body;

  var post = new POst(data);
  var newPost = yield post.save();

  this.body = newPost;

  yield next;
};
```

`data` contains an array of `tag` objects.

**Comment by neumino** [comment]
Use `saveAll`.
http://thinky.io/documentation/api/document/#saveall

**Comment by chovy** [comment]
Does that work even if there are no relations passed? They are optional in my case.

**Comment by chovy** [comment]
@neumino ^

**Comment by neumino** [comment]
If you want to just add a relation, you can just pass the key instead of the whole document.

`saveAll` behaves like `save`. It will create new documents and consider them at not saved and therefore will issue an `insert` command.

In the case of `hasAndBelongsToMany`, if you want to just create a relation, you can just pass the key instead of the whole document.

```
tag = ...
tag.posts = ["postId1", "postId2"]
tag.saveAll({posts: true}) // will not insert new posts.
```

**Comment by chovy** [comment]
Now it says `Error: Cannot build a new instance of `Tag` without an object`

```
ctrl.post = function *(next){
  var data = this.request.body;

  var tagIds = data.tags.map(tag => {
    return tag.id;
  });

  data.tags = tagIds;

  var post = new Post(data); //this is where the error occurs
  var newPost = yield post.saveAll({ tags: true }); //save joins

  this.body = newPost;

  yield next;
};
```

**Comment by chovy** [comment]
This is the best I could do that works. Seems a bit hacky to mutate the data that is posted.

https://gist.github.com/chovy/9be6b15ad846b7a2cc10

**Comment by neumino** [comment]
This is by design. When you save a new relation by just providing the key, thinky does not hit the joined table. For now you have to fetch the document again like you did.

A better solution would be to implement #115

**Comment by chovy** [comment]
How would I handle a PUT request where I want to update and object, and then do a join for the provided tag ids?

I have this so far:

```
ctrl.put = function *(next){
  var id = this.params.id;
  var data = this.request.body;
  var tags = data.tags;

  delete data.tags;
  data.updatedAt = new Date();

  var post = yield Post.get(id).update(data);

  post.tags = tags;

  //how do I update the `Post_Tag` table here with the new tag list?
  //I also want to delete the old tag ids if they are not present in this new list

  var result = yield Post.get(post.id).getJoin({ tags: true });

  this.body = result;

  yield next;
};

```
