### ISSUE TITLE
handling 'internal' properties

### ISSUE THREAD

**Issue by chrisspiegl** [neumino/thinky#20]
It would be great if there would be a way to specify values as not publicly presentable.

For example the `password` in a `User` model. You can interact with it in the User model but can not request it from the outside.

**Comment by mkorablin** [comment]
Hi, @neumino, I've been trying to find a way to do what @cspiegl wanted and `defineStatic` doesn't provide a solution. Looking up a user using hashed password in the DB only works if you are not adding salt or using the same salt every time, either of which are not for security. Therefore, you need to retrieve the whole document before you can verify hashed password.

In theory I agree that it would be nice if hashed password is checked in the DB and is never returned, but it doesn't seem that rethinkDB currently supports this.

I noticed similar issue came up several times. I think providing `toJSON` method is an easy way to resolve various issues of eliminating fields for client use. The actual exclusion of the fields can be done by each client.

**Comment by neumino** [comment]
Can you provide a snippet of what you want to do? (and what you currently do)?

**Comment by mkorablin** [comment]
Sure. During authentication I'd like to do the following:

    User.filter({'email' :  email}).limit(1).nth(0).default(false)
        .then(function(user) {
            if (!user) {
                return done(null, false, {'message': 'Email or password are incorrect'});
            }
            var newUser = new User(user);
            if (newUser.isValidPassword(password)) { // This is where I check the hash
                return done(null, _.omit(newUser.toJSON(), 'password'));
            } else {
                return done(null, false, {'message': 'Invalid password'});
            }
        })

Right now instead of

    return done(null, _.omit(newUser.toJSON(), 'password'));

I have to do

    return done(null, user);

But `user` object contains field `password` in it as well.

Right now locally I added the following `toJSON` method to document: 

    Document.prototype.toJSON = function() {
      var result = {};
      for (var key in this) {
        if (this.hasOwnProperty(key)) {
          result[key] = this[key];
        }
      }
      return result;
    }

but maybe there's a better way to do this

To give you an idea why this came up, the password is hashed like this:

    bcrypt.hashSync(password, bcrypt.genSaltSync(8));

Therefore hashing the same string twice produces different result. This means, I can't query the db using `{ password: hashedPassword }`.

**Comment by neumino** [comment]
Hum, I just realized that my answer was not sent.

You could do something like this:
```
User.define('toPublic', function(doc) {
    delete doc.password;
    return doc;
})
```
And then just call
```
return done(null, doc.toPublic())
```

**Comment by mkorablin** [comment]
Thanks, @neumino.
