### ISSUE TITLE
Options priority are sometimes wrong

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#203]
See https://github.com/neumino/rethinkdbdash/issues/75

`parse` in `schema.js` should set the properties, and we shouldn't have to propagate them after.
See https://github.com/neumino/rethinkdbdash/issues/75

**Comment by neumino** [comment]
@zlls -- I just released a fix in 1.16.9, it should work fine now. Your understanding of how the options work is right.

**Comment by zlls** [comment]
That was fast! Thanks for fixing and sorry for posting in the wrong repository. Don't know how this happened.
