### ISSUE TITLE
Setup a Gitter room for Thinky

### ISSUE THREAD

**Issue by mindjuice** [neumino/thinky#206]
Consider setting up a Gitter room (http://gitter.im) for people to ask questions about Thinky instead of using the Issues list for questions about usage.  You can add the Gitter badge to the README.md file to make it easy for people to click over the Gitter room.

**Comment by neumino** [comment]
The problem about setting up a gitter room is that it requires people to hang out there.
I'm usually hanging out on irc.freenode.org/rethinkdb
Some people there can also help with thinky.

**Comment by neumino** [comment]
I'm not really opposed to opening a room, but I'm worry that it will feel really empty.

**Comment by mindjuice** [comment]
It probably would be empty, true, but questions can be answered later too whenever people come on.  I just have this reservation about asking questions in the GitHub Issues that are just about usage of a project, and not actually bugs or requests for enhancement.

**Comment by mindjuice** [comment]
The alternative is that I ask usage questions here in the GitHub Issues list. :-)

**Comment by bplatz** [comment]
I think gitter is a good option, and I've used it for several projects. I don't think there is an expectation that questions get answered immediately, it is just a nice surprise when they do. I've also used its search feature to find solutions to problems, which works well.

**Comment by neumino** [comment]
Ok, I'll try to set that up tomorrow :)

**Comment by chovy** [comment]
I'm on gitter for a few projects, I notice more of the .NET folks flocking to it (open source guys are usually familiar with freenode/irc). But Gitter does have an IRC network which is cool. irc.gitter.im (you have to get a key there).

I think if you don't want to be in both channels, you should maybe tell people to go in #rethinkdb on freenode.

**Comment by neumino** [comment]
Does this work https://gitter.im/neumino/thinky ?

**Comment by neumino** [comment]
Ok, updated the Readme and the FAQ to point to irc.freenode.org/rethinkdb and https://gitter.im/neumino/thinky
:)
