### ISSUE TITLE
Document retrieved event is not emitted when document is fetched through a join

### ISSUE THREAD

**Issue by Tlvenn** [neumino/thinky#207]
Title says pretty much all, right now, Thinky does not emit the 'retrieved' event when a document is fetched from the database implicitly through a join of another entity.

**Comment by primitive-type** [comment]
I have just come across a very related issue, but in a slightly different use case. Since the ```get``` command [throws an error](http://thinky.io/documentation/api/query/#reql) rather than returning ```null```, I think [```getJoin```](http://thinky.io/documentation/api/query/#getjoin) should exhibit similar behavior. I'm not sure whether the error thrown should be ```DocumentNotFound``` or ```ValidationError```, but one of those seems appropriate to me.

**Comment by Tlvenn** [comment]
Hi @primitive-type,

I honestly fail to see how those 2 are related ;)

As for your case, it's natural and expected that ```get``` is throwing an error because the lookup is by the primary key so you are expecting the document, it's not a search at all. As for joins, this is a totally different scenario, for a given model, some documents will have some joins , some others will not which is perfectly normal.

There is a reason why when you declare the relation, one side is named 'hasOne/hasMany' and the other side is name 'belongsTo' :) They cannot belong to each other.

Enforcing a minimum cardinality of 1 of both side of a relation would be pretty tricky to do and would probably raise the question of why those 2 models are not a single document in the first place. Remember there is no transaction so to speak outside the boundary of a document so you could very easily save one and not the other.

**Comment by Tlvenn** [comment]
Ok I do see the parallel, i was stuck on how unrelated they are :) it would had been best to open a new issue imho.

**Comment by primitive-type** [comment]
@Tlvenn I agree. I've opened up a separate issue in #208 with a slightly better explanation of the issue I'm describing. Sorry about that.

**Comment by Tlvenn** [comment]
@neumino any feedback on this issue plz? If the fix is simple, would be very handy for what I am dealing with at the moment. Merci par avance.

**Comment by neumino** [comment]
Arg sorry, I wrote an answer, but I guess I failed at submitting it. Yes for now if you have `A.hasOne(B, ...)`, and you fetch a document from A, you won't get a 'retrieve' event for B.

I think it's easy to fix, I just have to recurse in the documents. I'll push a fix in a few minutes.

**Comment by neumino** [comment]
Done, @Tlvenn you can find it in 1.16.11 :)

**Comment by Tlvenn** [comment]
Thanks a lot @neumino  !
