### ISSUE TITLE
Migration / Update Schema

### ISSUE THREAD

**Issue by misticini** [neumino/thinky#211]
Hello,

I've defined an initial schema for my User Tables. But now, i have to add more attributes to my schema. There is anyway to update a model schema and add the new attributes to all documents already present, with a default value?

Regards

**Comment by neumino** [comment]
Hum, there's not an automatic way to do it now. But you can do two things:

1. If you want to immediately update your data, you can run something like

```
var thinky = require('thinky')();
var Model = thinky.create(...);

// Suppose you want to add a new field age to -1 by default:
Model.update({age: -1}).run()
```

2. You can add default to your schema, and the next time the document will be loaded, the default will be set, and if you save it, you will save the default value.

**Comment by misticini** [comment]
Thank you neumino :)

And lets suppose that now i want to remove the age field from all documents (again, update the schema from previous version). How can i do that?

Regards

**Comment by neumino** [comment]
If you want to remove the field age, you can also do two things:
1. Set the field to `type.virtual()`. The field will be loaded without problem, but the next time the document will be saved, the field will be removed.

2. If you immediately want to remove the field from all the documents, you can run:
```
Model.replace(r.row.without("age")).execute()
```
