### ISSUE TITLE
Defining a schema

### ISSUE THREAD

**Issue by misticini** [neumino/thinky#212]
Hello,
I have this error defining a schema: 
```
object: type.string(),
	        ^
ReferenceError: Type is not defined
    at Object.<anonymous>
```
My definition of schema is the following:

```
var thinky = require('../thinky.js');
var User = require('./user.js');

var Namespace = thinky.createModel('Namespace', {
	id: {_type: String},
	object: type.string(),
	name: type.string(),
	userId: type.string()
});

Namespace.belongsTo(User, "user", "userId", "id");

module.exports = Namespace;
```

I only can define schemas if i create the type object by code, like its visible on the example if id attribute.

Regards

**Comment by neumino** [comment]
Did you define type?
```
var type = thinky.type
```

**Comment by misticini** [comment]
Oh, sorry :(

It's first time that i'm using thinky and i didnt see that part on the examples :(

Thank you, solved!

**Comment by neumino** [comment]
No problem :)
