### ISSUE TITLE
Update/replace may throw an error

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#214]
For update/replace that doesn't change any document, the field `changes` may not be returned.

I added a few check for 2.0, but it may not always be enough. This is also quite annoying as you can't do a update/get in an atomic way, which make building the `update` route of a REST API a bit annoying.

I'll fix the bug for now and see with RethinkDB if it's possible to revert this behavior.

**Comment by neumino** [comment]
Fixed in 2.0.1

**Comment by neumino** [comment]
See https://github.com/rethinkdb/rethinkdb/issues/4068 to restore the previous behavior.

**Comment by marshall007** [comment]
@neumino can you tag and release `v2.0.1`?

**Comment by neumino** [comment]
Arg sorry it looks like I failed to release this -_-
I'll release it as soon as I get home tonight.

**Comment by marshall007** [comment]
Also, I just noticed `Model.save()` has the same problem (see [`lib/model.js#L1004`](https://github.com/neumino/thinky/blob/v2.0.0/lib/model.js#L1004)).

**Comment by neumino** [comment]
Fixed in 2.0.2.

So now `update`/`replace` may return `undefined`, but no error is thrown.
