### ISSUE TITLE
Static model creation

### ISSUE THREAD

**Issue by shaoner** [neumino/thinky#215]
Hi,

I'm wondering why a model needs a thinky instance to be initialized before its creation?

```javascript
var thinky = require('thinky')();
var type = thinky.type;

var Post = thinky.createModel("Post", {
    id: type.string(),
    title: type.string(),
    content: type.string(),
    idAuthor: type.string()
}); 
```

I mean `thinky.createModel` could register the model and delays everything relative to the connection when the connection is actually established (like creating the table/database etc) just like Mongoose does.

It would allow to use `var Post = require('./models/post');` without wondering when thinky is connected.

Notice that I'm aware of this singleton method:
```javascript
// file: util/thinky.js
var thinky = require('thinky')({
    // thinky's options
});
module.exports = thinky;
```

However if you get your thinky options asynchroneously, then you're screwed and cannot require your models the same way.

A work around would be to load all models in a map when initializing thinky and require this map of models instead of a model itself but it's not really ideal IMO.
This work around is actually the (bad) [recommended way](https://github.com/sequelize/sequelize/blob/master/examples/using-multiple-model-files/Task.js) to use models with [sequelize](https://github.com/sequelize/sequelize) because you have to initialize a connection prior to defining your models and compared to Mongoose it's not really user friendly as you cannot even import the model in your application apart from being ugly to write.

I don't know if there is a plan for such a thing? I could even work on a patch if needed.
I understand that this implies a big change in the API and from what I see in lib/thinky.js, changes would be to:
* Add a connect method with a config argument, which initializes rethinkdbdash etc.
* Remove stuff relative to a connection in the Thinky constructor 
* Export new Thinky() directly

This would allow to explicitly call `thinky.connect(config)` from anywhere. Each model would be able to use `var thinky = require('thinky');` and could be retrieved from anywhere by just using `require` without wondering if thinky is connected or not.

**Comment by neumino** [comment]
Helo @shaoner, thanks for the feedback.

So the main reason why you have to call `thinky` and not call `thinky.connect(...)` is mostly because
- `thinky` uses `rethinkdbdash` and that you need to call `rethinkdbdash` to start it.
-  It's similar to how `express` and `koa` work.

About needing to asynchronously load the options, there are a few things to note:
- If you need it to load from a file, you could still use a synchronous `fs` method
- If you don't want to use a synchronous method, you can have `thinky.js` return a promise.
- The main reason you would need to load some config would be find all the servers to connect to, but since 2.0, `rethinkdbdash` will automatically spread its connection to all the servers.

I'm not strongly opposed of having to call `connect` on the module, but:
- It's a non backward compatible change, so it's more work/more complexity to support a lazy initialization.
- It's a decent chunk of work I think and the benefits are relatively small.

I have to dig a bit more to see exactly how much work it would be but for now there are a few more important things I would like to fix first on thinky.

**Comment by shaoner** [comment]
Hi @neumino,

I completely understand your concerns and your priorities, and I'm just glad we can discuss about this.

> So the main reason why you have to call thinky and not call thinky.connect(...) is mostly because
> * thinky uses rethinkdbdash and that you need to call rethinkdbdash to start it.
> * It's similar to how express and koa work.

Yes, but you could call rethindbdash in `connect` and initialize thinky stuff relative to rethinkdbdash in there too. Then indeed, express() returns a new Express instance but it's up to the user to actually "start" the express app whenever he wants.

> * If you need it to load from a file, you could still use a synchronous fs method

Yes of course, but this can be trickier than it looks. Some configuration systems are meant to be loaded asynchronously. This can be done for sure, but it removes the ability to control the lifecycle of your configuration. In a big project, that really matters.

> * If you don't want to use a synchronous method, you can have thinky.js return a promise.

I don't quite understand, it looks like it just creates a new Thinky instance which call rethinkdbdash directly, so you have to give Thinky a config prior to defining your models anyway:

```javascript
function Thinky(config) {
  //...
  self.r = rethinkdbdash(config);
 // ...
}
// ...
module.exports = function(config) {
  return new Thinky(config);
}
```

> * It's a non backward compatible change, so it's more work/more complexity to support a lazy initialization.
> * It's a decent chunk of work I think and the benefits are relatively small.

I agree, I'm just bringing it to the table because it might be something to consider in the future to make Thinky even more pleasant to use.
Thanks for your great work btw.

**Comment by neumino** [comment]
Yes, what I wrote are workarounds not really a proper solution, especially if you need to pull your configuration from let's say CoreOs' etcd.

About my note to do return a promise, you can do:

```
// thinky.js
var Promise = require('bluebird');
module.exporst = new Promise(function(resolve, reject) {
  // asynchronously load stuff...
}).then(function(config) {
  return require('thinky')(config)
})
```
Then you can use
```
var p = require('thinky.js');
p.then(function(thinky) {
    thinky.createModel(...)
});
```
But again, it's a workaround, not a proper solution.

I can see why it can be a bit annoying though. Thanks for the suggestion, I'll keep that in mind and try to do it :)
