### ISSUE TITLE
problem with multiple hasAndBelongsToMany relationship

### ISSUE THREAD

**Issue by andela-omesanni** [neumino/thinky#220]
I have a couple of models that have hasAndBelongsToMany relationship with couple of models. Below is the code

var thinky = require('../../config/thinky');
var type = thinky.type;
var User = require('./user.model');
var Project = require('./project.model');

var Organization = thinky.createModel('Organization', {
  id: String,
  name: String,
  owner: String
}); 

User.hasAndBelongsToMany(Organization, 'organizations', 'id', 'id');
Organization.hasAndBelongsToMany(User, 'members', 'id', 'id');
User.hasAndBelongsToMany(Project, 'projects', 'id', 'id');
Project.hasAndBelongsToMany(User, 'users', 'id', 'id');
Organization.hasMany(Project, 'projects', 'id', 'organization_id');
Project.belongsTo(Organization, 'organization', 'organization_id', 'id');

module.exports = Organization;

From above, a user can belong to many organizations and organizations can have many users. Also a user can be assigned to multiple projects and in turn a project can have many users working on it. Now I noticed a bug in the user model. Anytime i create a new user for example, i see the user has an empty array of organizations but i see no empty array for projects. Even when i add a user to the users array in a particular project, it doesn't reflect in the projects array of that particular user. I would appreciate if u could really help with his as i am currently using rethinkdb for a project i am working on for a client.

Thanks

**Comment by neumino** [comment]
That's because you could have circular references.

Use `getJoin` with the explicit joins to fetch. See http://thinky.io/documentation/api/query/#getjoin

**Comment by andela-omesanni** [comment]
thanks very much, my problem is solved
