### ISSUE TITLE
Does type.object() have to have a schema defined?

### ISSUE THREAD

**Issue by xbenjii** [neumino/thinky#223]
I have a model called `event`, which looks like so:
``` JavaScript
var Event = db.createModel('Event', {
    event: type.string(),
    channelName: type.string(),
    data: type.object().optional().allowExtra(true).allowNull(true),
    isMain: type.boolean()
});
```
The `data` object can vary quite a bit, since the events vary.

Currently getting an error:

> Document failed validation: One of the documents is not valid. Original error: Value for [data] must be an object or null.

**Comment by xbenjii** [comment]
Sorry, just found out what's crashing it. Just seen an event that sends `data` as a string.

**Comment by neumino** [comment]
Sorry I missed this issue.
I opened https://github.com/neumino/thinky/issues/292 for multiple types for a given field. `type.any` should work fine now.
