### ISSUE TITLE
right way to save model with related model

### ISSUE THREAD

**Issue by Proxiweb** [neumino/thinky#225]
Here is the way I do it in express for an api (hasOne)

```javascript
 User.get(req.params.id).getJoin({profile: true}).run().then(function (user) 
          if (!user.profile && typeof req.body.profile !== 'undefined') {
            var profile = new Profile(req.body.profile);
            user.profile = profile;
          } else {
            user.merge(req.body);            
          }
          
          user.saveAll().then(function(user){
                res.status(200);
                res.send(user);    
                return next(); 
          })
);
```
I wonder if there is a better to achieve this... first I tried to only do the ```user.merge(req.body);``` hoping thinky would detect the association datas, but it throws the error ''Object #<Object> has no method '_save''' .

**Comment by neumino** [comment]
Hum, `merge` was created to just merge values, not documents.

I believe this should work fine when the joined document actually exist. It's in the case that the document doesn't exist that things break.

**Comment by neumino** [comment]
For 1-1 relation I guess this is easy to fix.
It's actually tricky to do that for 1-n or n-n relations.
