### ISSUE TITLE
Way to exclude fields?

### ISSUE THREAD

**Issue by jrasanen** [neumino/thinky#226]
Hi,

is there a way to redact sensitive fields from queries?

Like if I want to list all users, I do:
```javascript
  router.get("/", function (req, res) {
    User.run().then(function (users) {
        res.status(200).json(users);
    });
  });
```

But is there a way to exclude fields like "hashed_password" and "email" using Thinky? In my example, I would have to iterate all the results deleting sensitive fields before returning the json.

Thanks!

**Comment by jrasanen** [comment]
Found the answer, you have to use raw ReQL-query and pluck only the necessary fields

Example:
```javascript
    router.get("/", function (req, res) {
      var p = r.table(User.getTableName()).pluck("id", "firstName", "lastName", "createdAt");
      p.then(function (users) {
          res.status(200).json(users);
      });
    });
```

**Comment by neumino** [comment]
You can just use it on the model
```
User.without('hash', 'emal').run()
// or
User.pluck('id', 'firstName', 'lastName', 'createdAt').run()
```

**Comment by jrasanen** [comment]
Ah, right! Thanks.

**Comment by jrasanen** [comment]
I noticed, If I have email and password set as "required" to the model, this code throws an exception **"Possibly unhandled Document failed validation: Value for [email] must be defined."**
 	
	User.defineStatic("getView", function() {
	    return this.without('hashed_password').without('email');
	});

	router.get("/:id", function (req, res) {
	  var userId = req.params.id;
	  User.get(userId).getView().run().then(function (user) {
	      return res.status(200).json(user);
	  })
	});
