### ISSUE TITLE
Validator returns only Error for one Field

### ISSUE THREAD

**Issue by iamtimde** [neumino/thinky#228]
Good evening,

I have a little challenge with the validation. If I fill 2 fields wrong, I just get an error for the first field, but i should get 2 Errors returned for both fields.

```javascript
var User = thinky.createModel("Users", {
  id: type.string(),
  username: type.string().required(),
  email: type.string().email().required(),
  password: type.string().required(),
  createdAt: type.date().default(r.now())
},
{
  pk: "username"
});
```
```javascript
{
    
    "email": "me@abc.de",
    "passwordE": "Test",
    "usernameE": "ne3tlope2"
}
```

In this Case i got: "Value for [username] must be defined." but i want both ;-)

Thank you
Tim

**Comment by neumino** [comment]
Yea, someone mentioned that some time ago. Thinky currently just throw errors, we could gather all data and eventually throw all of them at the same time.

**Comment by iamtimde** [comment]
that would be nice or isnt that an option?

**Comment by neumino** [comment]
Closing in favor of https://github.com/neumino/thinky/issues/328 since there's a bit more info there.
