### ISSUE TITLE
Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by cschram** [neumino/thinky#230]
When stringifying an instance of a thinky model (to return as JSON) I'm running into this error:

```
TypeError: Cannot read property 'r' of undefined
    at new Query (/home/corey/projects/drawgaiden/rest-server/node_modules/thinky/lib/query.js:20:40)
    at Model.(anonymous function) [as toJSON] (/home/corey/projects/drawgaiden/rest-server/node_modules/thinky/lib/model.js:939:27)
    at Object.stringify (native)
    at ServerResponse.json (/home/corey/projects/drawgaiden/rest-server/node_modules/express/lib/response.js:233:19)
    at /home/corey/projects/drawgaiden/rest-server/src/core/endpoint.js:94:17
```

**Comment by neumino** [comment]
Sorry I missed that. I'll take a look tonight.

**Comment by neumino** [comment]
Hum, @cschram how did you get that error?
Documents can be stringified, Model currently cannot, but I don't get the same error as yours.

**Comment by cschram** [comment]
It's happened to me in certain situations when trying to convert a document
to JSON, but I'm having a hard time getting an exact scenario to reproduce
it. I'll try more and see what I can get you.

**Comment by csaintc** [comment]
:+1: encountering the same issue

**Comment by neumino** [comment]
Snippet?

**Comment by chrisfosterelli** [comment]
Not sure if this is related, but I appear to be running into this when I try and call a lodash function on a thinky model before sending it to the client:

```javascript
var user = new User(req.body);
user = _.omit(user, 'school');
res.send(user);
```

Gives me:
```
TypeError: Cannot read property 'r' of undefined
    at new Query (/Users/chrisfosterelli/workspace/memoryleaf/sms/node_modules/thinky/lib/query.js:20:40)
    at Model.(anonymous function) [as toJSON] (/Users/chrisfosterelli/workspace/memoryleaf/sms/node_modules/thinky/lib/model.js:712:25)
    at Object.stringify (native)
    at ServerResponse.json (/Users/chrisfosterelli/workspace/memoryleaf/sms/node_modules/express/lib/response.js:242:19)
    at ServerResponse.send (/Users/chrisfosterelli/workspace/memoryleaf/sms/node_modules/express/lib/response.js:151:21)
    at /Users/chrisfosterelli/workspace/memoryleaf/sms/server/staff/router.js:745:7
    [....]
```

If I don't call the lodash function, everything works. Is there a way to convert a document to a pure object (not a JSON string)?

**Comment by neumino** [comment]
Can you paste a full script?

Also does it work if you do `delete user.school`? What about `user.school = undefined`?

**Comment by neumino** [comment]
Didn't you forget the new keyword?

**Comment by chrisfosterelli** [comment]
Here is an entire script to reproduce:

```javascript
var thinky  = require('thinky')();
var express = require('express');
var _       = require('lodash');

var User = thinky.createModel('User', {
   id       : String,
   email    : String,
   password : String
});

var app = express();

app.get('/', function(req, res) {
  var user = new User({
    email    : 'test@test.test',
    password : 'testpassword'
  });
  user = _.omit(user, 'password'); // Error caused by this line
  res.send(user);
});

app.listen(8080);
```

Using `delete` or setting the value to `undefined` works, but I want to use something like `_.omit` because it returns a new object. I don't want to edit the original object in my use case.

**Comment by chrisfosterelli** [comment]
I'm not sure what you mean regarding forgetting the new keyword.

**Comment by neumino** [comment]
Ok, the issue is in loadash/undescore.

`omit` doesn't just remove a field. It flattens all the property in the prototype and remove one.
Typically if you print `user` after `_.omit(...)` you will see that you don't have what you are expecting.

**Comment by chrisfosterelli** [comment]
Ah yes, that makes sense. So is there no way to convert a thinky document
to a plain object?

**Comment by neumino** [comment]
There's no shortcut at the moment, but you can manually do it (or use `define`).
