### ISSUE TITLE
Allow formatting response

### ISSUE THREAD

**Issue by vjpr** [neumino/thinky#240]
I want to return `Point`s to my client in the format of `[lat, lng]`. At the moment they are:

```
"$reql_type$": "GEOMETRY",
"coordinates": [
  49.4186,
  8.67689
],
  "type": "Point"
```

Is there any way to specify this for a nested join? Or do I just use something like `jsonpath` to format my responses to my liking. Bookshelf has `format`/`parse` commands for this purpose.

**Comment by neumino** [comment]
You can add a hook after retrieving and before saving to format a ReQL point to any format you want (including `[lat, lng]` - note that in RethinkDB it's `[lng, lat]`).
See http://thinky.io/documentation/api/model/#pre and http://thinky.io/documentation/api/model/#post
