### ISSUE TITLE
Value for [createdAt] must be a string or null.

### ISSUE THREAD

**Issue by chovy** [neumino/thinky#243]
Getting this error `Value for [createdAt] must be a string or null.` when using an example:

 ` createdAt: type.string().default(r.now()),` in my schema.

**Comment by bentranter** [comment]
I think there's a mistake in the docs. I tried this with `createdAt: type.date().default(r.now())` and didn't get an error. If it is an error in the [docs](http://thinky.io/documentation/api/thinky/#createmodel), it's in the `createModel` section at the `Post` example.

I made a quick gist to compare the effects of `type.string().default(r.now())` and `type.date().default(r.now())`: https://gist.github.com/bentranter/471954731bbf9e00db02

**Comment by neumino** [comment]
Thanks @bentranter for looking into it, this was indeed the problem.

It's fixed with https://github.com/rethinkdb/rethinkdb/issues/4282#issuecomment-105718709 and pushed live
