### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by chovy** [neumino/thinky#244]
can I download the documentation at thinky.io somewhere?

I'm going out of town and won't have internet access for a week, but would still like to work locally on my rethink project.

**Comment by neumino** [comment]
You can checkout the `gh-pages` branch.

**Comment by neumino** [comment]
And then run jekyll. The docs are hosted on github.io

**Comment by neumino** [comment]
`jekyll serve` to be more precise (you need to install jekyll and ruby though).
Or you can read the markdown files.

**Comment by chovy** [comment]
beautiful! thank you!
