### ISSUE TITLE
Documentation correction 

### ISSUE THREAD

**Issue by timhaak** [neumino/thinky#246]
Sorry could not find the site in github other wise would have sent a pull request.

Correction for the site at 

http://thinky.io/documentation/api/query/#execute

User.map(r.row("id")).execute().then(function(cursor) {
    cursor.each(function(userId) {
        console.log(userId);
    }
})

Should be

User.map(r.row("id")).execute().then(function(cursor) {
    cursor.each(function(err, userId) {
        console.log(userId);
    });
});

**Comment by neumino** [comment]
Thanks @timhaak -- I just pushed a fix for that.
The docs are in the branch gh-pages (the website is hosted on GitHub)
