### ISSUE TITLE
saveAll subdocument duplicate Entry

### ISSUE THREAD

**Issue by iamtimde** [neumino/thinky#248]
Hey neumino,

i have a Problem with a Subdoc:

```javascript
var account = new User.Account({});

  var user = new User.User({
    "email": req.body.email,
    "password": req.body.password
  });

  try {
    user.validate();
  } catch(err) {
    if(err.message === "Value for [password] must be longer than 8.") {
      return next(new ApiError(3002));
    }
    return next(new ApiError());
  }

  account.user = user;

  account.saveAll().then(function(result) {
    res.status(201).json({"message": result});
    return next();
  }).error(function(err) {

    if(err.message.indexOf("Duplicate primary key") > -1) {
      return next(new ApiError(3001));
    }

    // delete all Account without a User

    return next(new ApiError());
  });
```

saveAll creates the Entry in Account, but the User fails and returns my Error. How can i prevent thinky from creating the Account without the User? Can i delete it? I cant get the id from Account on
the error-Function?

Thank you so much
Tim

**Comment by neumino** [comment]
Hum, yea you don't get back the id of the account that was just created.

I can think of a few solutions:
1.You can filter the account based on the email/password and then delete it.
2. you can save tie `account` to `user` and call `user.saveAll()` instead of `account.saveAll` (you have to create the opposite relation hasOne <-> belongsTo)
3. Call `user.save()` first , and then `account.saveAll`

**Comment by iamtimde** [comment]
Thank you, 

i took number 3 ;-) becuase Email is a pk, i need the Email to be unique and changeable later, thats why i tied all to the account. I can create a new User and swap the User for an account. I hope that is the right way in rethinkdb to do this.

```javascript
var account = new User.Account({});

  var user = new User.User({
    "email": req.body.email,
    "password": req.body.password
  });

  user.save().then(function(user) {
    account.user = user;
    account.saveAll().then(function(result) {
      res.status(201).json({"message": result});
      return next();
    }).error(function() {
      return next(new ApiError());
    });
  }).error(function (err) {
    if(err.message.indexOf("Duplicate primary key") > -1) {
      return next(new ApiError(3001));
    }
    if(err.message === "Value for [password] must be longer than 8.") {
      return next(new ApiError(3002));
    }
    return next(new ApiError());
  });
```
