### ISSUE TITLE
Editing a model, removing or including pk. Does not work

### ISSUE THREAD

**Issue by diego04** [neumino/thinky#249]
Editing a model either by removing or including pk does not work: not sure if a bug or an enhancement.

This is a sample code that has a commented pk.

var Post = thinky.createModel("Post", {
    title: type.string(),
}, //{pk: title}
);

**Comment by neumino** [comment]
You can't change the primary key of an existing table. This is a constraint of RethinkDB, and is as far as I know a constraint in any other databases.
You can't randomly change the primary key of a table.

**Comment by diego04** [comment]
Right on, thanks
