### ISSUE TITLE
recent change broke the use of bluebird's spread method

### ISSUE THREAD

**Issue by mbroadst** [neumino/thinky#250]
As of version 2.0.4+, the below test case does not work:

```
it('should spread filter and count queries', function() {
    var User = thinky.createModel(modelNames[0], {id: String}, {init: false});

    var query = User;
    query = query.orderBy(r.desc('id'));
    query = query.slice(0, 1);

    var countQuery = query;

    return Promise.all([
      query.run(),
      countQuery.count()
    ])
    .spread(function(results, total) {
      assert(results !== undefined);
      assert(total !== undefined);
    });
  });

```

commenting out this branch passes the test: https://github.com/neumino/thinky/blob/master/lib/query.js#L565 (introduced with https://github.com/neumino/thinky/commit/e4b490dc79a9df5a574f9f3b32a7e6cfcf843df7)

**Comment by neumino** [comment]
This is actually working as expected.

If you yield a query, we'll call run on it. We use to call execute by mistake and https://github.com/neumino/thinky/commit/e4b490dc79a9df5a574f9f3b32a7e6cfcf843df7 fixed it.

This works
```
it('should spread filter and count queries', function() {
    var User = thinky.createModel(modelNames[0], {id: String}, {init: false});

    var query = User;
    query = query.orderBy(r.desc('id'));
    query = query.slice(0, 1);

    var countQuery = query;

    return Promise.all([
      query.run(),
      countQuery.count().execute()
    ])
    .spread(function(results, total) {
      assert(results !== undefined);
      assert(total !== undefined);
    });
  });
```

Or you can drop the first `run`

```
it('should spread filter and count queries', function() {
    var User = thinky.createModel(modelNames[0], {id: String}, {init: false});

    var query = User;
    query = query.orderBy(r.desc('id'));
    query = query.slice(0, 1);

    var countQuery = query;

    return Promise.all([
      query,
      countQuery.count()
    ])
    .spread(function(results, total) {
      assert(results !== undefined);
      assert(total !== undefined);
    });
  });
```

**Comment by neumino** [comment]
Added a test in 98e625422d8a0fa66302f1a43a90e0991a5f7838

**Comment by mbroadst** [comment]
You should mention this somewhere, as this change breaks semver imho

**Comment by mbroadst** [comment]
That or provide a function to emulate the old behavior and deprecate it?

**Comment by neumino** [comment]
I'll mention that in the releases

**Comment by mbroadst** [comment]
for completeness sake, and anyone who might end up back on this issue, you can only solve this with the first solution: 
```
      query.run(),
      countQuery.count().execute()
```
this does not work:
```
      query,
      countQuery.count()
```

**Comment by neumino** [comment]
Bad copy/paste. I updated my response there.
This is what I wanted to write:
```
    return Promise.all([
      query,
      countQuery.count().execute()
    ])
```

Basically the issue is not about `spread`, but just what the queries return. `query` return documents and can be yielded, while `query.count()` returns a number (and not a document) and cannot be yielded (and call `run()` under the hood)
