### ISSUE TITLE
Read query result in batches

### ISSUE THREAD

**Issue by xpepermint** [neumino/thinky#255]
I found this in RethinkDB docs:

>If the table contains a large number of documents a query will not return all of them at once, which would saturate the network and/or require a lot of memory on the client. Instead the query will return the results in batches and fetch more data as needed.

I need to set `maxBatchRows` in this case because the default value is set to `unlimited`. Does this work with Thinky?

**Comment by neumino** [comment]
I just looked at the code. You can set the option in `run` or `execute`, but I'm pretty sure this is not something you really need.

The default value is not `unlimited`. Thinky via rethinkdbdash retrieves all the batches, it doesn't seem that only one batch is actually sent.

**Comment by xpepermint** [comment]
Aha, ok... will test again. Thanks.
