### ISSUE TITLE
filter using match doesn't seem to work for me

### ISSUE THREAD

**Issue by chovy** [neumino/thinky#256]
The doc passed to the filter callback has no attributes.

```
    var result = yield Tag.orderBy({index: "createdAt"}).filter(function(doc){
      return doc.name.match(matches.name);
    });
```

**Comment by neumino** [comment]
You can't use `.name` as we can't overload (yet?) `.` in JavaScript.

Use `return doc('name').match(matches.name)` instead.

**Comment by chovy** [comment]
crap, i copied wrong from the docs. Sorry about that.

**Comment by neumino** [comment]
No problem :)
