### ISSUE TITLE
Some methods in the change feed documentation don't seem to be working correctly

### ISSUE THREAD

**Issue by jeffquach** [neumino/thinky#257]
I was looking through the thinky change feed documentation and experimented with your sample code but it seems that "isSaved()" on this method call: "doc.isSaved()" doesn't seem to work.  This is the code that I am using locally and I pretty much copy and pasted your example in the API docs except I changed 'User' to 'Game' for the model:

    Game.get("3851d8b4").changes().then(function(doc) {
      console.log();
      console.log(JSON.stringify(doc, null, 2));
      doc.on('change', function(newDoc) {
        // doc === newDoc === this;
        if (doc.isSaved() === false) {
          console.log("The document was deleted.");
        }
        else if (doc.getOldValue() == null) {
          console.log("The document was inserted.");
        }
        else {
          console.log("The document was updated.");
          console.log("Old value:");
          console.log(stringify(doc.getOldValue()));
          console.log("New value:");
          console.log(stringify(doc));
        }
      });
      doc.on('error', function(error) {
        console.log(error);
        process.exit(1);
      });
    }).error(function(error) {
      console.log(error);
      process.exit(1);
    });

And whenever I make a change to that specific document in the database this error pops up:

    "Possibly unhandled TypeError: undefined is not a function"

I'm guessing that error is in reference to the "doc" object returned in the callback being undefined and the "isSaved()" method can't be invoked on an undefined object.

Also the object return from the callback in the range feed does the same thing.

I did some experimentation and managed to get the change feed working for a single record by doing this: 

    Game.get("3851d8b4").changes().then(function(feed) {
    	feed.each(function(error, doc) {
    	    if (error) {
    	      console.log(error);
    	      process.exit(1);
    	    }
    	    console.log("$$$ doc is $$$");
    	    console.log(doc);
    	});
    }).error(function(error) {
      console.log(error);
      process.exit(1);
    });

When I ran the code above the output show the new and old values.

Also another issue I noticed was the API docs mention you can use "getFeed()" to get a feed and "closeFeed" to close a feed for a document but I couldn't get either of those to work without throwing an error.  When I tried running "closeFeed()" on a document I got this error:

    "TypeError: undefined is not a function"

Are these actual bugs or problems in the code, or am I using the methods incorrectly?

Thanks for your time!

**Comment by neumino** [comment]
Did you define `stringify`?
Could you copy the stacktrace and your whole script?

This works for me:

```
var thinky = require('./lib/thinky.js')();
var type = thinky.type;


var Game = thinky.createModel('Game', {id: String, score: Number, game: String});

var id = 'test'+Math.floor(Math.random()*1000)
var game = new Game({id: id, game: 'CS', score: 10});



Game.get(id).changes().then(function(doc) {
  console.log();
  console.log(JSON.stringify(doc, null, 2));
  doc.on('change', function(newDoc) {
    // doc === newDoc === this;
    if (doc.isSaved() === false) {
      console.log("The document was deleted.");
    }
    else if (doc.getOldValue() == null) {
      console.log("The document was inserted.");
    }
    else {
      console.log("The document was updated.");
      console.log("Old value:");
      console.log(JSON.stringify(doc.getOldValue()));
      console.log("New value:");
      console.log(JSON.stringify(doc));
    }
  });
  doc.on('error', function(error) {
    console.log(error);
    process.exit(1);
  });

  game.save().then(function(game) {
    console.log("--- Inserted");
    game.score = 20;
    return game.save();
  }).then(function(game) {
    console.log("--- Updated");
    game.delete();
  }).then(function(game) {
    console.log("--- Deleted");
  });
}).error(function(error) {
  console.log(error);
  process.exit(1);
});
```

Output
```
{}
The document was inserted.
--- Inserted
The document was updated.
Old value:
{"game":"CS","id":"test220","score":10}
New value:
{"game":"CS","id":"test220","score":20}
--- Updated
--- Deleted
The document was deleted.
```

**Comment by jeffquach** [comment]
It's weird, I'm not getting the same errors that I was getting last night instead I'm getting this error now:

    Possibly unhandled ReqlDriverError: You cannot serialize a AtomFeed to JSON. Retrieve data from the cursor with `each` or `next`.

Here's the code that I'm using.  This is my 'Game' model in game.js:

    var thinky = require('../util/thinky.js');
    var type = thinky.type;
    var r = thinky.r;
    var User = require('./user');
    
    var Game = thinky.createModel("Game",{
        id: type.string(),
        status: type.string().required(),
        category: type.string().required(),
        metadata: type.string().required(),
        name_of_room: type.string().required(),
        user_id: type.string().required(),
    	date_created: type.date().default(r.now())
    });
    
    User.hasMany(Game,"games","id","user_id");
    Game.belongsTo(User,"user","user_id","id");
    
    module.exports = Game;

This is my controller in "game_controller.js":

    var Game = require('../models/game');
    var crypto = require('crypto');
    
    var stringify = function(doc) {
      return JSON.stringify(doc, null, 2);
    }
    
    exports.create = function(req,res){
    	var requestBody = req.body;
    	crypto.randomBytes(28, function(ex, randomBytes) {
    		if (ex) throw ex;
    		var newGame = new Game({
    			id:"1",
    			status: "open",
    		    category: requestBody.category,
    		    metadata: requestBody.metadata,
    		    name_of_room: requestBody.username+"-"+randomBytes.toString('base64'),
    		    user_id: requestBody.user_id
    		});
    		Game.get(newGame.id).changes().then(function(doc) {
    		  console.log();
    		  console.log(JSON.stringify(doc, null, 2));
    		  doc.on('change', function(newDoc) {
    		    // doc === newDoc === this;
    		    if (doc.isSaved() === false) {
    		      console.log("The document was deleted.");
    		    }
    		    else if (doc.getOldValue() == null) {
    		      console.log("The document was inserted.");
    		    }
    		    else {
    		      console.log("The document was updated.");
    		      console.log("Old value:");
    		      console.log(JSON.stringify(doc.getOldValue()));
    		      console.log("New value:");
    		      console.log(JSON.stringify(doc));
    		    }
    		  });
    		  doc.on('error', function(error) {
    		    console.log(error);
    		    process.exit(1);
    		  });
    		  newGame.save().then(function(game) {
    		    console.log("--- Inserted");
    		  }).then(function(game) {
    		    console.log("--- Updated");
    		  }).then(function(game) {
    		    console.log("--- Deleted");
    		  });
    		}).error(function(error) {
    		  console.log(error);
    		  process.exit(1);
    		});
    	});
    }
    exports.get = function(req,res){
    	Game.get("813cm131-7b0e-407c-bd9d-5bQ0889zab42").changes().then(function(doc) {
    	  console.log();
    	  //console.log(JSON.stringify(doc, null, 2));
    	  doc.on('change', function(newDoc) {
    	    // doc === newDoc === this;
    	    if (doc.isSaved() === false) {
    	      console.log("The document was deleted.");
    	    }
    	    else if (doc.getOldValue() == null) {
    	      console.log("The document was inserted.");
    	    }
    	    else {
    	      console.log("The document was updated.");
    	      console.log("Old value:");
    	      console.log(stringify(doc.getOldValue()));
    	      console.log("New value:");
    	      console.log(stringify(doc));
    	    }
    	  });
    	  doc.on('error', function(error) {
    	    console.log(error);
    	    process.exit(1);
    	  });
    	}).error(function(error) {
    	  console.log(error);
    	  process.exit(1);
    	});
    }

This is in my routes.js file:

    var express = require('express');
    var router = express.Router();
    var gameController = require("./controllers/game_controller");
    
    router.post("/game/create",gameController.create);
    router.get("/game/get",gameController.get);
    
    module.exports = router;

This error:

    Possibly unhandled ReqlDriverError: You cannot serialize a AtomFeed to JSON. Retrieve data from the cursor with `each` or `next`.

that I mentioned above seems to be called from the stringify function that you defined in your API docs.  

And this is the accompanying stack trace on the 'create' method in the 'game_controller.js' when I try to post data to it and initiate the change feed:

    Possibly unhandled ReqlDriverError: You cannot serialize a AtomFeed to JSON. Retrieve data from the cursor with `each` or `next`.
    at Cursor.toJSON (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/rethinkdbdash/lib/cursor.js:46:11)
    at Object.stringify (native)
    at /Users/jeff/share/node/cheddaServer/controllers/game_controller.js:39:22
    at tryCatch1 (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:934:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/async.js:38:14)

For the 'create' method in my controller I pretty much copy and pasted the example that you responded with except I took out a few lines that were not relevant to my model.  Also even if I comment out  this line causing the error:

    console.log(JSON.stringify(doc, null, 2));

I can initiate the change feed, but it doesn't respond to changes.  For the 'create' method this is the output I get in the terminal:

    --- Inserted
    --- Updated
    --- Deleted

When I run a command such as this from the rethinkDB web GUI:

    r.db('chedda').table('Game').filter({category:"Basketball",metadata:"1"}).update({status:"closed"})

the terminal output remains the same with nothing showing the 'old_val' or 'new_val'.

You'll also notice for the 'get' method in the 'game_controller.js' file I hardcoded an ID stored in the database just to test things out, but I still get the same 'stringify' error:

    Possibly unhandled ReqlDriverError: You cannot serialize a AtomFeed to JSON. Retrieve data from the cursor with `each` or `next`.
    at Cursor.toJSON (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/rethinkdbdash/lib/cursor.js:46:11)
    at Object.stringify (native)
    at /Users/jeff/share/node/cheddaServer/controllers/game_controller.js:127:21
    at tryCatch1 (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/promise.js:934:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/Users/jeff/share/node/cheddaServer/node_modules/thinky/node_modules/bluebird/js/main/async.js:38:14)

And when I comment out the 'stringify' method the same thing happens for the 'create' method in my controller, no output when a change is made to the specific record.

I am running rethinkDB on mac OS X using the Yosemite OS, 'rethinkdb -v' outputs this:

    rethinkdb 2.0.2 (CLANG 6.1.0 (clang-602.0.53))

Hope this helps.

Thanks for the quick response!

**Comment by neumino** [comment]
You're probably running an old version of thinky. Try updating it.

If it doesn't work, add `.run()` after `changes()` and before `then`. It should work.

**Comment by jeffquach** [comment]
Wow thanks, updating thinky worked, should've thought about that earlier.  Thanks again for the prompt help and keep up with the great work on thinky!
