### ISSUE TITLE
Rename table

### ISSUE THREAD

**Issue by 5an1ty** [neumino/thinky#267]
How do I rename a table? I know this would be destructive for the model etc, but I manage that in the update script I'm writing...

According to rethinkdb I should be able to execute:
    r.db('mydb').table_config('mytable').update({"name": 'newtablename'});

but when I try:
    thinky.r.db('mydb').table_config('mytable').update({"name": 'newtablename'});

I get undefined function error. I thought thinky exposes everything that r offers?

Edit: nevermind the functionality is available with:
thinky.r.db('mydb').table('mytable').config().update({"name": 'newtablename'});

**Comment by neumino** [comment]
Yep, `table_config` is not a valid command.
