### ISSUE TITLE
add update, delete examples to hasAndBelongsToMany docs

### ISSUE THREAD

**Issue by chovy** [neumino/thinky#269]
http://thinky.io/documentation/api/model/#hasandbelongstomany

There is a good example for creating and reading, but missing updating and deleting a `hasAndBelongsToMany` relationship.

Can someone add the examples for the full CRUD operations to the docs?

**Comment by neumino** [comment]
There's no updating such relation right?

```
User.hasAndBelongsToMany(User, 'friends', 'id, 'id');

User.getJoin({friends: true}).then(function(user) {
  user.friends = [];
  user.saveAll({friends: true}) // remove all the relations
})
```

**Comment by neumino** [comment]
There's removeRelations, but it's not ready for prime time. And I just remembered about the fact that I have to finish it ;)

**Comment by MarkHerhold** [comment]
+1 On the topic, I would love an example of how to add a relation to a new object/doc referencing an existing one with a `n:n` relation.

e.g.
```js
var doc = { name: 'new obj', relatedThings: [ 'it would be nice to include the model of the related thing or query', 'and a second one if needed' ] };
(new Model(doc)).saveAll();
```

I realize I could manually create the relation by adding a document in the `n:n` relation table, but that seems like a hack.

**Comment by nfantone** [comment]
>  I would love an example of how to add a relation to a new object/doc referencing an existing one with a n:n relation.

Same over here. I've struggling with this myself and I couldn't find a way to make it work. Docs didn't help, either.

In my model, I have `Metric` and `Report` entities, sharing a _many-to-may_ relationship. `Report`s are created by adding metrics to them from a fixed set of `Metric`s. Those always exist beforehand and I do _not_ have the need to store them. I do, however, need to save the _relationships_ between a new `Report` and its array of `Metric`s.

In the [Relations](https://thinky.io/documentation/relations/) section of the documentation it states that:

> Note: A notable exception is for `hasAndBelongsToMany` relations. **In this case you can provide an array with keys to link**. saveAll will only create the relations between the document and not verify that the document actually do exist.

Couldn't really grasp what that means. Is it implying that I could, potentially, save something like this?

```Javascript
var report = new Report({..., metrics: ["8883ec63-8b68-45cb-9e42-fd7f97a2661a", ...] };
```

Trying to `save()` that ends with a

```sh
Error: Cannot build a new instance of `metric` without an object
```

And providing an array of objects, such as:

```Javascript
var report = new Report({..., metrics: [{"id": "8883ec63-8b68-45cb-9e42-fd7f97a2661a"}, ...] };
```

Ends up complaining about pk duplicity:

```
Possibly unhandled Error: Duplicate primary key `id`:
```

**Comment by nfantone** [comment]
@neumino I'm opening a new issue for my last comment, if you don't mind.

**Comment by gjuchault** [comment]
Relations must be added after object creation (setter). This is not
documented but it should

**Comment by nfantone** [comment]
@gjuchault Could you elaborate on that? Maybe on the issue I have just opened (#309)?

**Comment by neumino** [comment]
This should make things simpler (in 2.1.1):

http://thinky.io/documentation/api/query/#addrelation
http://thinky.io/documentation/api/query/#removerelation
