### ISSUE TITLE
Is it possible to inject model fields after definition

### ISSUE THREAD

**Issue by pthm** [neumino/thinky#270]
After I have called createModel is it possible to inject extra fields into the model schema?

**Comment by neumino** [comment]
You can inject extra fields in a document if your settings don't enforce extra fields, but not in the model.

Why would you do that?

**Comment by pthm** [comment]
I have fields thats are the same across all models, wanted a way to easily inject them into all models and future models that might be added to the system.

**Comment by rasapetter** [comment]
Maybe something like this could work? (not tested)

```javascript
var baseSchema = {
  version: Thinky.type.number().integer().default(0),
  createdAt: Thinky.type.date().default(r.now())
};

var Stuff = Thinky.createModel('stuff', _.merge(baseSchema, {
  foo: Thinky.type.string()
}));

var Junk = Thinky.createModel('stuff', _.merge(baseSchema, {
  bar: Thinky.type.string()
}));
```

**Comment by neumino** [comment]
Closing as duplicate of #201
