### ISSUE TITLE
Validators and group/ungroup operations

### ISSUE THREAD

**Issue by ondreian** [neumino/thinky#272]
Hey,

When running a `group()` operation followed by an `ungroup()` operation thinky appears to try to enforce the defined model validators on the group, instead of the elements inside of the reduction.

Here is the example output from a simple test I wrote to recreate the bug

```
C:\dev\nodejs\playground\thinky-bug>npm test
> thinky-bug@0.0.0 test C:\dev\nodejs\playground\thinky-bug
> node test.js

threw!
[Error: The results could not be converted to instances of `things`
Detailed error: Value for [name] must be defined.]
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

The associated code to recreate this can be found [in this repo](https://github.com/ondreian/thinky-bug-recreation)

**Comment by neumino** [comment]
Yes, I didn't implemented any special case for `ungroup`, only `group` I think.

`group` returns a special format that thinky can detect and therefore parse the documents and not the group.
If you run `ungroup`, RethinkDB returns a normal stream, so thinky doesn't know that this is the result of a group operation anymore.


We should override `ungroup` have it flip a flag in `Query`. And we should check this flag to properly parse these group/ungroup queries

**Comment by neumino** [comment]
Thanks for the report

**Comment by marshall007** [comment]
> We should override `ungroup` have it flip a flag in `Query`. And we should check this flag to properly parse these group/ungroup queries

@neumino maybe it makes sense to automatically disable validation for everything but `.get()`, `.getAll()`, and `.filter()`. That would also fix #186. Then we could just provide a way to explicitly re-enable validation, maybe as an optarg to `.run()`.

**Comment by marshall007** [comment]
Also note that this would be a breaking change for people that are doing something along the lines of `.group(...).nth(0).ungroup()` and can actually expect the results to be valid model instances.

**Comment by ondreian** [comment]
@neumino Thanks for this fix!
