### ISSUE TITLE
IDs not generated for some nested models

### ISSUE THREAD

**Issue by MarkHerhold** [neumino/thinky#273]
I hit an issue where an ID was not being generated for some nested models.

I have three models: Bookshelf, Book and Author. A bookshelf has books (`1:n`), and Book and Author are `n:n`. All models are relatively simple.

```js
Bookshelf.hasMany(Book, "books", "id", "bookshelfId");
Book.hasAndBelongsToMany(Author, "authors", "id", "id");
```

Here is my nested bookshelf JSON doc.
```js
const bookshelf = {
    name: 'Bookshelf',
    books: [
        {
            name: 'Book A',
            description: 'The first book in the array',
            authors: [{
                name: 'Author A',
            }],
        },
        {
            name: 'Book B',
            desc: 'The second book in the array',
            authors: [{
                name: 'Author B',
            }],
        }
    ]
};
```

I create a document by instantiating the Bookshelf model and calling `saveAll()`.
```js
var shelf = new Bookshelf(bookshelf);
var result = yield shelf.saveAll();
```

This is what results. There is no id generated for `Author A`
```js
{
    "name": "Bookshelf",
    "books": [{
        "name": "Book A",
        "description": "The first book in the array",
        "authors": [{
            "name": "Author A"
            **NO ID GENERATED HERE**
        }],
        "bookshelfId": "4cb68d11-88d7-464f-9f28-859714e1d136",
        "id": "9d53b935-38a9-47c0-b09a-38e8d98fe810"
    }, {
        "name": "Book B",
        "desc": "The second book in the array",
        "authors": [{
            "name": "Author B",
            "id": "3431075a-3249-4f53-93e2-8e40a08930fa"
        }],
        "bookshelfId": "4cb68d11-88d7-464f-9f28-859714e1d136",
        "id": "db6749bf-a9a3-4d3f-b621-70f8b21ed3ef"
    }],
    "id": "4cb68d11-88d7-464f-9f28-859714e1d136"
}
```

In the DB, the
* `Author` table contains only the `Author B` document. `Author A` does not exist.
* `Book` table contains both books, `Book A` and `Book B` as expected.
* `Author_Book` table contains only one document linking `Book B` to `Author B`

The generation of the ID between `Author A` and `Author B` appears to be indeterministic. Either may be generated but never both.

**Comment by neumino** [comment]
Try `shelf.saveAll({books: { authors: true}});

`saveAll`, `getJoin` does not recurse on documents from the same type - thought it could be improved for `saveAll` by tracking references to documents instead.

**Comment by MarkHerhold** [comment]
Wow I didn't realize so many people hit the same thing. I did search the issue tracker before adding this issue, but I didn't see anything relevant. I will make a note to always use a parameter.

I'll also try out the suggestion tonight or tomorrow and report back. Thanks @neumino!

**Comment by MarkHerhold** [comment]
That did the trick. Thanks!
