### ISSUE TITLE
Deprecate/remove saveAll/getJoin without argument

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#274]
The idea was pretty nice I think, but too many people seem to trip on why something is not fetched/not saved.
- https://github.com/neumino/thinky/issues/273
- https://github.com/neumino/thinky/issues/220
- https://github.com/neumino/thinky/issues/130
- Etc.

**Comment by marshall007** [comment]
Might be even better if there were just some way on `Model` to define which relations should be joined by default. It should still probably throw if no default is configured and you call `getJoin` with no argument though.

**Comment by neumino** [comment]
@marshall007 -- So one thing I've been doing (and found nice) is defining some static methods for some models like

```
Users.defineStatic('getPosts', function() {
  return this.getJoin({posts: true})
})
```

It seems reasonable to provide a way for default relations to fetch though.

**Comment by neumino** [comment]
There shouldn't be a reference to `getJoin`/`saveAll` without argument.

I'll add a warning at some point when getJoin and saveAll will be called without argument and eventually make `saveAll()` (without argument) the same as `save()` and `getJoin()` (without argument) as a no-op.
Please do not use `getJoin`/`saveAll` without argument. This should also simplify a decent chunk of code.

**Comment by neumino** [comment]
Docs were updated a few weeks ago.

Calling `getJoin` and `saveAll` without argument still works, but it should be considered as deprecated.
