### ISSUE TITLE
Support for includeStates option on changefeeds

### ISSUE THREAD

**Issue by primitive-type** [neumino/thinky#283]
When setting the ```includeStates``` option to ```true``` for a changefeed, thinky gives me the following error: ```[Error: Cannot build a new instance of `Model` without an object]```. My particular use case is for a range feed on a table. 

I believe this would be helpful for writing tests around logic that happens within a changefeed, among other things.

**Comment by neumino** [comment]
Fixed in `next`, will be release once I'm done doing a pass on the current issues

**Comment by neumino** [comment]
In 2.0.12
