### ISSUE TITLE
id is not on the result object

### ISSUE THREAD

**Issue by gjuchault** [neumino/thinky#287]
Hi.

When I'm saving multiple instances through `Promise.all()`, id are not set in the result objects.

Model definition :
```js
let Article = thinky.createModel('Article', {
    name:      String,
    stock:     Number,
    createdAt: type.date().default(new Date()),
    editedAt:  Date,
    isRemoved: type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra: 'remove',
    enforce_type: 'strict'
});

Article.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

Article.ensureIndex('name');
Article.ensureIndex('createdAt');
Article.ensureIndex('editedAt');
```

Code treating the process :
```js
if (Array.isArray(req.body)) {
    insts = req.body.map(data => {
        return new Article(data);
    });
} else {
    insts = [
        new Article(req.body)
    ];
}

let allDone = insts.map(inst => inst.saveAll());
Promise.all(allDone)
    .then(() => {
        if (insts.length === 1) {
            insts = insts[0];
        }
        return res
            .status(200)
            .json(insts)
            .end();
    })
```

And the result of the request being :
```js
{ name: 'XXXX',
  stock: 0,
  createdAt: '2015-07-12T09:03:13.570Z',
  isRemoved: false,
  editedAt: '2015-07-12T09:03:47.410Z' }
```

Or an array of thoses if I sent an array of articles.

Why isn't `id` present ?

**Comment by neumino** [comment]
Because you didn't specified it in your schema and because you have `enforce_extra: 'remove'`.

Adding `id: type.string().optional()` should fix your problem.

**Comment by gjuchault** [comment]
Ok, this works. Thanks :)

**Comment by gjuchault** [comment]
Again, I guess this is the same problem for relationships.
*`Article.hasOne(Category, 'category', 'categoryId', 'id');`*
I'm now trying to create a new Article directly with relationships.
Either
```js
let inst = new Article({
   name: ...,
   stock: ...,
   category: {
      ...
   }
});
```

Or
```js
let inst = new Article({
   name: ...,
   stock: ...,
   categoryId: '...'
});
```

Does not work. Should I use the same method (adding `categoryid: type.string().optional()`) ?
What if this is a relationship like : `Article.hasAndBelongsToMany(Category, 'categories', 'id', 'id');` ? How can I create directly instances with relationships ?

**Comment by MarkHerhold** [comment]
https://thinky.io/documentation/api/model/#hasone

If you are using `hasOne` when `Article` is your *`Model`* and `Category` is your *`OtherModel`* (just as you have your relation), the `Category` model will contain the `articleId`. The `Article` model will **NOT** contain the `articleId`.

`Article.hasOne(Category, 'category', 'id', 'articleId');`

```js
new Article({
    id: 1234,
    name: ...,
    stock: ...,
})
```

```js
new Category({
    id: 'category5',
    articleId: 1234
})
```

When joined:
```js
{
    id: 1234,
    name: ...,
    stock: ...,
    category: {
        id: 'category5',
        articleId: 1234
    }
}
```
---
It might be easier to think of `hasOne` as "hasOneChild". So in the example in the docs, the `User` model has one child `Account` model.

**Comment by gjuchault** [comment]
Just edited my post, it was Category hasMany Articles and Article belongsTo Category. 
I have like 15 models with many relationships. And it seems that as thinky is recursive with getJoin, if one of the relationship is wrong on the descendent, it will not getJoin the initial relation at all. 
I managed to ses that by enabling only two models and their relationship, then à third, etc. I'll update this if I find what is the cause of that

**Comment by neumino** [comment]
You probably have circular relations in which case you must explicitly set
the relations you want to retrieve.

**Comment by gjuchault** [comment]
I do have circular relationships. I'm debugging on getJoin.
I see gotModel just have plain model as key :
```js
{ Fundation: true,
  Group: true,
  Price: true,
  Period: true,
  Purchase: true,
  Point: true }
```

(These are my models).
Fact is, if this is circular (just what you said 5 minutes ago), how cant it works ? It stops reimporting the same model even if the source is different.
So if I have
A hasMany B
   B hasMany D
A hasMany C
   C hasManyD

Well, A.getAll() will not work completly as C will not have D in the result object.

**Comment by gjuchault** [comment]
Opening a new error for this
