### ISSUE TITLE
findOrCreate

### ISSUE THREAD

**Issue by Thor99** [neumino/thinky#288]
Hi! You could implement a findOrCreate method, like mongoose has. Thanks!

**Comment by MarkHerhold** [comment]
I don't think mongoose has such a thing. Are you talking about a mongoose plugin? Link?

**Comment by Thor99** [comment]
Sorry, it's a plugin that adds that to mongoose :p https://github.com/drudge/mongoose-findorcreate

**Comment by neumino** [comment]
What's the use case behind find and create?
Note that this can work only by using the primay key.

**Comment by MarkHerhold** [comment]
@neumino I actually had a need for this not long ago. I needed to record that an event completed but didn't want multiple records of the same event completing.

I also needed this to happen on a secondary index so I ended up just getting the elements on that index and if none existed, created the doc.

I'd almost rather see this as a thinky "plugin" than a core function, just as mongoose has.

**Comment by neumino** [comment]
@MarkHerhold -- in this case you can use the primary key for uniqueness and just call `save` - if it fails it's because the document is already there.

**Comment by MarkHerhold** [comment]
Right. I think you read my comment a bit fast - my issue was doing this with a secondary index. I don't think @Thor99 specified if his issue was with a primary or secondary index.

**Comment by neumino** [comment]
Hum, so the thing is that there's no way to safely do that without a primary index.

Mongo gives you "unique" indexes, but they don't work as soon as you shard,..

**Comment by MarkHerhold** [comment]
Right, but people want to do this any way and will take the risks of consistency. If an existence check is performed right before creation then the risk of duplication is likely quite small for most projects and deemed a manageable risk. I am taking one. That's just how it is.

If this were a super important constraint, everyone would be using ACID databases, not NoSQL/BASE ones, but there is a huge marked for NoSQL, so that gives you a pretty good clue.

**Comment by neumino** [comment]
The solution for that would be to wait for https://github.com/rethinkdb/rethinkdb/issues/4068 to be fixed again and use

```
Model.get(pk).replace(value).run()
```

The only constraint is that you must use the primary key. A long time ago I thought about adding unique fields (via secondary indexes) but eventually decided not too. Thinky should stay close to RethinkDB and not add things that the datatabase itself cannot do.

Mongo typically provides unique secondary indexes that work only in a non-sharded environment. It works fine at the beginning, but when you decide to shard a table, everything break down and it's really not cool. In RethinkDB even if you do not shard the table, you don't even get this guarantee as there are hash shards under the hood.

**Comment by neumino** [comment]
Actually RethinkDB works fine, the syntax is:
```
Model.get(pk).replace(value, {returnChanges: 'always'}).run()
```
