### ISSUE TITLE
delete function does't pass callback to inner _delete function 

### ISSUE THREAD

**Issue by recitate** [neumino/thinky#293]
``` javascript
Document.prototype.delete = function(callback) {
  return this._delete({}, false, [], true, callback)
}
```

``` javascript
Document.prototype.deleteAll = function(docToDelete, callback) {
  return this._delete(docToDelete, deleteAll, [], true, true, callback)
}
```

Last 3 params of `_delete` expect `deleteSelf`, `updateParents`, and `callback` however the `delete` function doesn't provide an `updateParents` so the `callback` is ignored. 
``` javascript
Document.prototype._delete = function(docToDelete, deleteAll, deletedDocs, deleteSelf, updateParents, callback)
```

I would fix and create a pull request but I'm not sure whether it should be `true` or `false`.

**Comment by neumino** [comment]
Hum, I think `updateParents` should be true if I'm not mistaken.

Typically if you delete a joined document, you want the parent document to update its relation to the deleted document.

Thanks @recitate for catching that.

**Comment by neumino** [comment]
Fixed in `next`. I'm doing a pass on other issues and should release it soon.
