### ISSUE TITLE
merge and saveAll

### ISSUE THREAD

**Issue by palango** [neumino/thinky#296]
It seems like after merging a document with another one one can't use saveAll. Any reasons for that?

**Comment by rafaellopezgtz** [comment]
I have the same problem :C

**Comment by abbshr** [comment]
```coffee
    post = new Post body
    user.posts.push post
    user.saveAll()
```

`user.saveAll()` throws

```
Possibly unhandled TypeError: undefined is not a function
```

**Comment by neumino** [comment]
Can you provide a snippet to illustrate your issue? Do you merge joined documents?
