### ISSUE TITLE
GetAll and getField query

### ISSUE THREAD

**Issue by andrewvy** [neumino/thinky#297]
```
Post.getAll(User.get(1).getField('id', { index: 'author_id' }).run()
```

For some reason, this query results in.. `Possibly unhandled ReqlClientError: MALFORMED PROTOBUF (missing field `type`):`

Even though it works fine if I do it via R.. is there something I'm doing wrong?

**Comment by marshall007** [comment]
@andrewvy I think you're just missing a paren. Perhaps you meant to do this?

```js
Post.getAll(User.get(1).getField('id'), { index: 'author_id' })
Post.getAll(User.get(1)('id'), { index: 'author_id' }) // this works too
```

**Comment by neumino** [comment]
The problem is probably what @marshall007 pointed out.
Feel free to re-open if the issue still persists once the parentheses are fixed.
