### ISSUE TITLE
Close connection after query 

### ISSUE THREAD

**Issue by cadrogui** [neumino/thinky#298]
Hi, there is a way to close a connection after a query, and open a new one before a query?, this because the script never end cause the bd connection.

i use 
```
thinky.r.getPool().drain()
```

but this closes all connections and my script has several promises running and consuming data from bd.

regards.

**Comment by neumino** [comment]
You don't open a connection yourself, do you don't close it yourself.

The connections are automatically managed by the pool provided by the driver (rethinkdbdash).
