### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by felixsanz** [neumino/thinky#305]
Would be nice if the documentation were a single page, instead of sections.

This would enable the search through the whole docs easily.

**Comment by neumino** [comment]
So it's not super-obvious because I didn't write it on the website, but the docs are in the `gh-pages` branch.
If you want a faster search, you can clone the repo, and grep it :)

I'll add a note somewhere that the website is also open source. Thanks for the feedback

**Comment by felixsanz** [comment]
This example is good in my opinion: http://expressjs.com/api.html

It contains a menu but also all docs are contained in the same page so you can F3 to search

I would do a pull request but i don't know where the repository is or if it will be accepted

**Comment by MarkHerhold** [comment]
@felixsanz PR == pull request.
https://help.github.com/articles/using-pull-requests/

**Comment by felixsanz** [comment]
@MarkHerhold WANT, not WHAT lol. I'm asking if a PR will be accepted with the changes

**Comment by MarkHerhold** [comment]
hahahaha. I am so sorry! I need to learn how to read!

**Comment by felixsanz** [comment]
@MarkHerhold you should also learn to mention people. hahahaha.

**Comment by neumino** [comment]
The problem with one big page is that it sucks when you have to scroll up.

If search is what you are looking for, adding a swiftype box is probably better.

**Comment by felixsanz** [comment]
if you want to scroll up just "page Prev" or "index"
