### ISSUE TITLE
Make Savable Copy Parsing type.isDate Value Incorrectly When Value is ISO String

### ISSUE THREAD

**Issue by hqo** [neumino/thinky#306]
Hey,

First of all, awesome work on Thinky so thank you to you and all collaborators for getting it to where it is today.

With that said, I've come across a "bug" relating to how Document.__makeSavableCopy (document.js, line 428) handles ISO string values belonging to attributes of type date (basically where type.isDate() === true).

The test value I'm using is: "2015-08-05T04:00:00.000Z".

In node/js, new Date("2015-08-05T04:00:00.000Z") returns the following value: Wed Aug 05 2015 00:00:00 GMT-0400 (EDT).

However, when it is being parsed by __makeSavableCopy, it seems like the numericDate test returns as a number and so rather than the value being "2015-08-05T04:00:00.000Z" by the time it reaches new Date(doc) (line 444), it becomes 2015, which then results in new Date(2015) and thus the value that's saved to the db is Wed Dec 31 1969 19:00:02 GMT-0500 (EST).

I'm not entirely sure of the purpose of parseInt in there so I can't comment on this issue more than this, but any insight into this would be helpful.

I'm on version 2.0.10

Thank you!

**Comment by neumino** [comment]
This is a bug. I don't remember everything, but I probably just thought that `parseInt('2015-08-05T04:00:00.000Z', 10)` would return `NaN` and not `2015`.

I'll push a fix in a few minutes.

**Comment by hqo** [comment]
Awesome! I'm glad it's not a hard fix to push and thanks a lot.

**Comment by neumino** [comment]
It should be fixed in 2.0.11.
Thanks for digging into the code, it make things faster to fix :)

**Comment by hqo** [comment]
My pleasure and thank you for the quick fix!
