### ISSUE TITLE
Add an existing document to many-to-many relationship

### ISSUE THREAD

**Issue by nfantone** [neumino/thinky#309]
I've struggling with this and I couldn't find a way to make it work. Docs didn't reallt help, either. Conceptually speaking, and given a unidirectional `hasAndBelongsToMany` relation, I need to achieve the following:

* Create an entirely new document with an array of references to another.
* Save the new document and cascade to its children.
* If the child document exists in its own table, just keep the reference as is. **Do not try to create** a new one with the same `id`.

In my model, I have `Metric` and `Report` entities, sharing a _many-to-may_ relationship. `Report`s are created by adding metrics to them from a fixed set of `Metric`s. Those always exist beforehand and I do _not_ have the need to store them. I do, however, need to save the _relationships_ between a new `Report` and its array of `Metric`s.

In the [Relations](https://thinky.io/documentation/relations/) section of the documentation it states that:

> Note: A notable exception is for `hasAndBelongsToMany` relations. **In this case you can provide an array with keys to link**. saveAll will only create the relations between the document and not verify that the document actually do exist.

Couldn't really grasp what that means. Is it implying that I could, potentially, save something like this?

```Javascript
var report = new Report({..., metrics: ["8883ec63-8b68-45cb-9e42-fd7f97a2661a", ...] };
```

Trying to `save()` that ends with a

```sh
Error: Cannot build a new instance of `metric` without an object
```

And providing an array of objects, such as:

```Javascript
var report = new Report({..., metrics: [{"id": "8883ec63-8b68-45cb-9e42-fd7f97a2661a"}, ...] };
```

Ends up complaining about pk duplicity:

```
Possibly unhandled Error: Duplicate primary key `id`:
```

**Comment by gjuchault** [comment]
As I commented on the other issue, Thinky uses a setter or something else
that requires you to add relationships after you've created your main
document.

So,you need to set `metrics` after :

```js
report.metrics = ['id1', 'id2'];
report.saveAll({ metrics: true });
```

**Comment by nfantone** [comment]
Sorry, I'm not following. You are saying that I should save my main document first, _and then_ set its related children before saving. Isn't that exactly what the intention of `saveAll()` is?

From the [docs](https://thinky.io/documentation/relations/):

> We will first save user, then copy user's id in account.userId, then save account.
> Executing account.saveAll({user: true}) will save things in the same order since we need to save user first to fill the foreign key in account. **Using the appropriate order to save documents will be done by thinky**.

**Comment by gjuchault** [comment]
I said it was mandatory to not to put relationships into your model
instanciation.

1. Instanciate report
2. Add metrics
3. Use saveAll

**Comment by nfantone** [comment]
Confirmed not working. It makes no difference if I set my `metrics` array manually or during instantiation. Seems like the issue must be elsewhere. Also, tried setting an array of ids and of model instances.

Let me expand my scenario a bit, so it's clearer for anyone reading.

I have two models, `Metric` and `Report`, defined as follows:

```javascript
var Report = thinky.createModel('report', {
  id: type.string(),
  name: type.string(),
  createdAt: type.date().default(thinky.r.now()),
  dashboard: type.boolean().default(false)
});

var Metric = require('models/metric');
Report.hasAndBelongsToMany(Metric, 'metrics', 'id', 'id');
```

```javascript
var Metric = thinky.createModel('metric', {
  id: type.string(),
  name: type.string(),
  query: type.object(),
  data: type.virtual()
});
```

`metrics` table contains a single document:

```
{
    "id": "8883ec63-8b68-45cb-9e42-fd7f97a2661a",
    "name": "average_daily_rate"
  }
```

And I'm trying to create the following `Report` from a `POST`ed json on an Express server:

```
{
  "name": "Dashboard",
  "dashboard": true,
  "metrics": ["8883ec63-8b68-45cb-9e42-fd7f97a2661a"],
}
```

What I have tried:

* **Saving the document as is**

```javascript
  var report = new Report(req.body);
  report.saveAll({ metrics: true }).then(function (result) {
    res.json(result);
  });
```

_Result_: Fails with:

```sh
Error: Cannot build a new instance of `metric` without an object
    at new model (/home/nfantone/dev/js/2p/mobius-reporting2/node_modules/thinky/lib/model.js:94:13)
```

* **Sending an array of objects instead**

Basically, same `saveAll({ metrics: true })`, but with this body:

```
{
  "name": "Dashboard",
  "dashboard": true,
  "metrics": [{"id": "8883ec63-8b68-45cb-9e42-fd7f97a2661a"}],
}
```

_Result_: Fails with:

```sh
Possibly unhandled Error: Duplicate primary key `id`:
    at model.Document._onSaved (/home/nfantone/dev/js/2p/mobius-reporting2/node_modules/thinky/lib/document.js:812:19)
```

* **Setting the array explicitly**

```javascript
 var report = new Report(_.omit(req.body, 'metrics'));
  report.metrics = req.body.metrics;
  report.saveAll({ metrics: true }).then(function (result) {
    res.json(result);
  });
```

_Result_: This doesn't fail, *but* I couldn't retrieve the joined data, afterwards.

This,

```javascript
  Report.run()
  .then(function (report) {
    res.json(report);
  });
```

Raises:

```sh
Possibly unhandled Error: The results could not be converted to instances of `report`
    at /home/nfantone/dev/js/2p/mobius-reporting2/node_modules/thinky/lib/model.js:900:24
```

And this,

```javascript
  Report.getJoin({ metrics: true }).run()
  .then(function (report) {
    res.json(report);
  });
```

Fetches the report without any `metric` on it:

```
{
  "name": "Dashboard",
  "dashboard": true,
  "metrics": []
}
```

* **Setting an array of models instead of ids**

```javascript
  var report = new Report(_.omit(req.body, 'metrics'));
  report.userId = req.user.id;
  report.metrics = [new Metric({ id: req.body.metrics[0] })];
  report.saveAll({ metrics: true }).then(function (result) {
    res.json(result);
  });
```

_Result_: Again, this does not end up in failure. But final result is similar to my previous attempt. Getting the report back now returns this:

```
 {
    "createdAt": "2015-08-10T15:57:57.808Z",
    "dashboard": true,
    "id": "30582f65-4a3e-4023-9b46-4c9ae70c56e0",
    "metrics": [
      {
        "id": "8883ec63-8b68-45cb-9e42-fd7f97a2661a"
      }
     ]
}
```

With no joined data.

So, _what am I doing wrong_, here? What's the correct way of storing and retrieving things in my case?

Sorry for the long post.

**Comment by gjuchault** [comment]
Okay. I know Thinky's documentation is not very explicit on it. But the examples all works.

```js
var Report = thinky.createModel('report', {
  id: type.string(),
  name: type.string(),
  createdAt: type.date().default(thinky.r.now()),
  dashboard: type.boolean().default(false)
});

var Metric = thinky.createModel('metric', {
  id: type.string(),
  name: type.string(),
  query: type.object(),
  data: type.virtual()
});

// Setting :
var report = new Report(_.omit(req.body, 'metrics'));
report.metrics = req.body.metrics;
report.saveAll({ metrics: true }).then(function (result) {
   res.json(result);
});

// Getting
Report.getAll({ metrics: true }).run().then(function (results) {
  res.json(results);
});

```

**Comment by nfantone** [comment]
Is `getAll` an undocumented override of Rethink's driver? Anyway, your example doesn't seem to work. Have you tried it?

```sh
Possibly unhandled ReqlRuntimeError: Primary keys must be either a number, string, bool, pseudotype or array (got type OBJECT):
    at Connection._processResponse (/home/nfantone/dev/js/2p/mobius-reporting2/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:213:21)
```
 
I believe that's because [getAll](http://rethinkdb.com/api/javascript/get_all/) expects primary keys as argument, and you are passing an object to it (`{ metrics: true }`).

**Comment by gjuchault** [comment]
Okay I did make a mistake that was `getJoin` : https://thinky.io/documentation/api/query/#getjoin

**Comment by nfantone** [comment]
@gjuchault But then, it becomes the _exact same thing_ I explained earlier that didn't work for me. See the **Setting the array explicitly** section of my [previous comment](https://github.com/neumino/thinky/issues/309#issuecomment-129514672).

Doing what you suggested returns an empty array of metrics.

**Comment by gjuchault** [comment]
Could you triple check your input body (could you copy the HTTP request ?) ? Because testing with a dumb example (without coming from body) is working.

```js
var thinky = require('thinky')();

var Foo = thinky.createModel('Foo', {
   id: String,
   foo: String
});

var Foo2 = thinky.createModel('Foo2', {
   id: String,
  foo: String
});

Foo.hasAndBelongsToMany(Foo2, 'foos', 'id', 'id');
Foo2.hasAndBelongsToMany(Foo, 'foos', 'id', 'id');

var foo2 = new Foo2({ foo: 'bar' });
var foo  = new Foo({ foo: 'bar' });

foo.foos = [ foo2 ];

foo.saveAll({ foos: true }).then(function () {
    Foo.getJoin({ foos: true }).then(function (foos) {
        console.log(foos);
    });
});
```

Output :
```
[ { foo: 'bar',
    foos: [ [Object] ],
    id: 'b6ccc5f2-3711-4b89-82e4-a8ca1185f99e' } ]
```

**Comment by nfantone** [comment]
@gjuchault That is not exactly the same scenario that I have. Reasons being:

* My relation is _unidirectional_. That means, no `hasAndBelongsToMany` in the second entity.
* You are creating _two new instances_ of documents. In my case, I'm trying add an _existing document_ to an array inside a _new one_.

So with that in mind, here's an adaptation of your example:

```
var thinky = require('thinky')();
var type = thinky.type;

var Report = thinky.createModel('report', {
  id: type.string(),
  name: type.string(),
  createdAt: type.date().default(thinky.r.now()),
  dashboard: type.boolean().default(false)
});
var Metric = thinky.createModel('metric', {
  id: type.string(),
  name: type.string(),
  query: type.object(),
  data: type.virtual()
});

Report.hasAndBelongsToMany(Metric, 'metrics', 'id', 'id');

var report = new Report({ name: 'foo', dashboard: true });
report.metrics = [ '428245e3-c298-44e8-9a8a-c5952bbf8fea' ];

report.saveAll({ metrics: true }).then(function () {
    Report.getJoin({ metrics: true }).then(function (reports) {
        console.log(reports);
    });
});
```

Where ` '428245e3-c298-44e8-9a8a-c5952bbf8fea'`is the `id` of an existing `Metric`, like:

```
{
    "id": "428245e3-c298-44e8-9a8a-c5952bbf8fea",
    "name": "average_daily_rate"
  }
```

With all that, you get:

```
{ createdAt: Mon Aug 10 2015 23:00:34 GMT-0300 (ART),
    dashboard: true,
    id: '3388e89a-18ed-4fc7-899a-2144aa549c0b',
    metrics: [],
    name: 'foo' }
```

As you can see, `metrics` array is empty and documents are not joined together.

**Comment by neumino** [comment]
Are you sure that your metric document exists?

This works for me:
```
var thinky = require('thinky')();
var type = thinky.type;
var assert = require('assert');

var Report = thinky.createModel('report', {
  id: type.string(),
  name: type.string(),
  createdAt: type.date().default(thinky.r.now()),
  dashboard: type.boolean().default(false)
});

var Metric = thinky.createModel('metric', {
  id: type.string(),
  name: type.string(),
  query: type.object(),
  data: type.virtual()
});

Report.hasAndBelongsToMany(Metric, 'metrics', 'id', 'id');

var ids = [''+Math.random(), ''+Math.random()]

var metric = new Metric({ id: ids[1] });

metric.save().then(function() {
  var report = new Report({ id: ids[0], name: 'foo', dashboard: true });
  report.metrics = [ ids[1] ];

  return report.saveAll({ metrics: true })
}).then(function () {
  return Report.get(ids[0]).getJoin({ metrics: true })
}).then(function (report) {
  assert(report.metrics.length === 1);
  assert.equal(report.metrics[0].id, ids[1]);
  console.log('Done, report:');
  console.log(report);
});


```

**Comment by nfantone** [comment]
@neumino Um... Although, again, the script doesn't quite match my case, I can see that, even after updating things a bit it **does work**.

Here:

```javascript
var thinky = require('thinky')();
var assert = require('assert');
var type = thinky.type;

var Report = thinky.createModel('report', {
  id: type.string(),
  name: type.string(),
  createdAt: type.date().default(thinky.r.now()),
  dashboard: type.boolean().default(false)
});

var Metric = thinky.createModel('metric', {
  id: type.string(),
  name: type.string(),
  query: type.object(),
  data: type.virtual()
});

Report.hasAndBelongsToMany(Metric, 'metrics', 'id', 'id');

var metric = new Metric({ name: 'average_daily_rate' });

metric.save().then(function(result) {
  var report = new Report({ name: 'foo', dashboard: true });
  report.metrics = [ result.id ];
  metric.id = result.id;
  return report.saveAll({ metrics: true });
}).then(function () {
  return Report.getJoin({ metrics: true }).run();
}).then(function (reports) {
  reports.forEach(function (r) {
    assert.equal(r.metrics[0].id, metric.id);
    assert.equal(r.metrics[0].name, metric.name);
    console.log('Report', r);
    console.log('Metrics', r.metrics);
  });
});
```

> Are you sure that your metric document exists?

**Yes**, I'm positive.

![screenshot from 2015-08-11 10 43 47](https://cloud.githubusercontent.com/assets/476069/9199098/dd862994-4016-11e5-8728-c9d77b594acb.png)

I even tried specifying the metric id manually (emulating my previous examples), and it went without issues. Could you spot any obvious differences between _this_ and what I've posted earlier?

**Comment by neumino** [comment]
The script I pasted is a copy of yours, except that I was also creating the metric before (since I didn't have it).

Maybe you have multiple databases and your metric document is in the table metric that is not in the database used by thinky?

**Comment by nfantone** [comment]
>Maybe you have multiple databases and your metric document is in the table metric that is not in the database used by thinky?

I only have that one `test` database. But I'll retry things over and let you know.

As a completely unrelated side note, do I need to call

```javascript
r.getPoolMaster().drain();
```

on my Express server `close` event, using thinky?

**Comment by neumino** [comment]
Yea, you should drain the connection if you don't plan to use thinky anymore.

Back to the issue, I just added the commands `addRelation`, `removeRelation` in 2.1.1
http://thinky.io/documentation/api/query/#addrelation
