### ISSUE TITLE
Close the loop with relations

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#311]
Thinky was designed to work well with saved relations.

People sometimes just want to just save a relation. This leads to multiple issues like https://github.com/neumino/thinky/issues/29, https://github.com/neumino/thinky/issues/245, https://github.com/neumino/thinky/issues/309 etc. 

I'll add a method addRelation and removeRelation that will update only relations. The expectation being that all the documents exists, only the relation is missing.

API:

```
Query.prototype.addRelation(field, joinedDocument);
```
* for hasOne and hasMany, the primary key of joinedDocument is required
* for belongsTo, the primary key or the joined field of joinedDocument is required
* for hasAndBelongsToMany, the primary key or the joined field of joinedDocument is required

The last constraint will be for v1 that Query must return a document so the query is probably something like `model.get(<x>)`

```
Query.prototype.removeRelation(field[, joinedDocument])
```
* for `hasOne` and `belongsTo`, `joinedDocument` is not needed
* for `hasMany` and `hasAndBelongsToMany`, if `joinedDocument` is not provided, all relations will be removed

Same constraint as for addRelation, query must return a document.

**Comment by neumino** [comment]
In 2.1.1

**Comment by esatterwhite** [comment]
@neumino Could you add this explaination to the [documentation](http://thinky.io/documentation/api/document/#addrelation) w/ an example. Would be very helpful.

Thanks.

**Comment by neumino** [comment]
The tests have a few examples
https://github.com/neumino/thinky/blob/master/test/query.js#L832

I'll try to add them on the website.

**Comment by esatterwhite** [comment]
`addRelation` doesn't seem too be on the `Document` class either. `removeRelation` is there.

**Comment by neumino** [comment]
Added in 2.3.5
