### ISSUE TITLE
Nested Attributes with a Null Value Throwing "Cannot read property value of null" Error

### ISSUE THREAD

**Issue by hqo** [neumino/thinky#314]
Looks like Line # 97 in lib/schema.js throws an error on nested attributes that have a null value.

That line attempts to get the value of the attribute's defined nested attribute but if the attribute value itself is null, then a "Cannot read property 'value' of null" error is thrown. 

The attributes schema definition is as follows:
 discount: 
   { _default: [Function],
     _validator: undefined,
     _options: { enforce_type: 'loose' },
     _schema: 
      { value: 
         { _min: -1,
           _max: -1,
           _integer: false,
           _default: [Function],
           _validator: undefined,
           _options: {} },
        description: 
         { _min: -1,
           _max: -1,
           _length: -1,
           _alphanum: false,
           _uppercase: false,
           _lowercase: false,
           _regex: undefined,
           _enum: undefined,
           _default: [Function],
           _validator: undefined,
           _options: {} },
        type: 
         { _min: -1,
           _max: -1,
           _length: -1,
           _alphanum: false,
           _uppercase: false,
           _lowercase: false,
           _regex: undefined,
           _enum: { percentage: true, absolute: true },
           _default: [Function],
           _validator: undefined,
           _options: {} } } },

Am I defining the schema incorrectly?

**Comment by neumino** [comment]
Fixed in 2.1.1

**Comment by hqo** [comment]
You are awesome man! Thanks a lot for the quick turnaround.
