### ISSUE TITLE
delete requires validation

### ISSUE THREAD

**Issue by mbroadst** [neumino/thinky#322]
definition:
```
var User = thinky.createModel('users', {
  username: types.string().required(),
  email: types.string().validator(validator.isEmail)
});
```

action:
```
User.delete().then(function() { console.log("everything was deleted"); });
```

result:
```
     Document failed validation: Value for [username] must be defined.
```

This is overlooked in the tests because of this (dangerous imho) line: https://github.com/neumino/thinky/blob/master/test/model.js#L22

**Comment by neumino** [comment]
This is expected. Here's what happen

`User.delete()` return a query. When you call `then` on it, it calls `run` under the hood, and therefore expect an instance of `User` to be returned.
I believe if you call
```
User.delete().execute().then(function() { console.log("everything was deleted"); });
```
Everything should work :)

**Comment by neumino** [comment]
Feel free to re-open if it's not the case, or to comment if you have more questions.

**Comment by micky2be** [comment]
Hmm, still not working for me after adding `execute`

**Comment by neumino** [comment]
Code?

**Comment by micky2be** [comment]
After playing a bit with the code I had a really weird behavior using Promise.all to delete 2 different stuff (one using deleteAll and the other a delete), everything got deleted but still getting the errors.
I finally make it work using the `execute` on the `delete` call. Now everything is working well.

Thank you @neumino
