### ISSUE TITLE
Connection Pool Failure During Long Test Suite

### ISSUE THREAD

**Issue by primitive-type** [neumino/thinky#323]
I've gotten to the point where my app has over 100 tests, and each one starts up the app from scratch and thinky prints the `Creating a pool connected to localhost:28015` message to the console. Since my tests have grown to be so numerous, the following happens every time I get to the nth test:
```
Entering slow growth mode
Fail to create a new connection for the connection pool. Error:{"message":"Failed to connect to localhost:28015 in less than 20s."}
Possibly unhandled ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
```

This doesn't happen if I remove about 15 tests or if I just run a smaller subset of them. In my RethinkDB terminal window I get the following message whenever the above errors happen in my app's terminal window: `error: accept() failed: Too many open files.`

This is all being run locally on Mac OS X 10.10.4 with RethinkDB 2.1.1 and thinky 2.1.4. Is there anything I can do to resolve this? I've already tried editing `/etc/sysctl.conf` and I currently have the following settings specified there: 
```
kern.maxfiles=500000480
kern.maxfilesperproc=400004576
```

Previously when I used to get the "too many open files" message during tests, just increasing the values in `/etc/sysctl.conf` worked. But now it doesn't seem to have an effect.

**Comment by neumino** [comment]
So this kind of depends what each test is doing.

I guess each time you start your app, you create a new thinky object and thefore create a new connection pool. And by default a pool can go up to 1000 connections. So depending on your load, that can go up pretty fast.

Do you start all your tests in paralllel? If yes you may want to start at most <X> in parallel (X to be defined).
If you don't, make sure that you close the pool at the end of your test with
```
thinky.r.getPoolMaster().drain()
```

If it doesn't fix your issue, could you share a bit the load in your test. Is it just normal queries? Or changefeeds too?

**Comment by primitive-type** [comment]
@neumino The tests are run serially, not in parallel. When I tried draining after each test, I got a similar `Possibly unhandled ReqlDriverError: None of the pools have an opened connection and failed to open a new one.` message each time. In order to attempt diagnosing the problem, I logged the following after each test runs in my suite:

```
thinky.r.getPoolMaster().getLength()
thinky.r.getPoolMaster().getAvailableLength()
```
Both of these values stayed consistently below 120. The highest values logged were 112 and 106, respectively. The average was closer to 90 for both. There are no changefeeds currently in my app. My queries are all pretty standard, mostly simple CRUD stuff for an API I'm developing. 

Additionally, I'm pretty sure (and currently trying to confirm) that the particular point at which everything crashes is arbitrary. In other words, I don't think it matters which test is currently running when I get the `Entering slow growth mode` message. The culprit seems to be how long the tests have been running or how many tests there are total.

**Comment by neumino** [comment]
Where is the too many files open showed? In the container? Or outside the contained?

**Comment by neumino** [comment]
Do you set the max open files parameters in the appropriate place (or both)?

**Comment by primitive-type** [comment]
@neumino These errors only occur when I'm not using Docker. In my Mac's Terminal tab which is running RethinkDB I see the `error: accept() failed: Too many open files` message. In the separate Terminal tab which is running my application, I get the message about slow growth and failure to open a new connection for the pool.

If I run my tests in a Docker container (on the same machine), everything works perfectly. 

I set the max open files parameters in `/Library/LaunchDaemons/limit.maxfiles.plist` and `/Library/LaunchDaemons/limit.maxproc.plist` according to the instructions at http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/. I also tried setting them previously in both `/etc/sysctl.conf` and `/etc/launchd.conf` per http://superuser.com/a/830625 and many other online resources found via extensive Googling. Nothing so far has worked, so I've been using the workaround on just using Docker for running my application locally. Admittedly, this is just a minor inconvenience, but I would still really like to know why this is occurring and potentially fix it if it has something to do with the way my app is interacting with the database.

**Comment by subblue** [comment]
I had the same errors when using ```mocha --watch``` to automatically rerun my test suite on file changes.
For the moment I've reverted to just running the tests manually on demand, but it would be nice if there was a safe way to reset the models and connections on each run.

**Comment by sandcastle** [comment]
This issue is also affecting me with only 77 tests in my API suite.

**Comment by neumino** [comment]
This is probably an issue with your system. There are two things that could help:
- Import thinky with `max` and `buffer` reduced (like 10/5)
- Increase the number of open files allowed on your system

**Comment by iambumblehead** [comment]
I'm also experiencing this issue. It prevents me from adding automated tests around my application.

I'm trying to drain the pools created during the tests in order to complete the test process, but this error is always shown,

`Unhandled rejection ReqlDriverError: None of the pools have an opened connection and failed to open a new one.`

This would be fine if I could hide the message, but it is printed from a different stack and always appears in the test results with a long stack trace.

**Comment by neumino** [comment]
Are you draining the pool after your tests are done?

**Comment by iambumblehead** [comment]
I resolved this issue by updating my application to use a shared thinky instance --draining the pool for that single instance works every time.

**Comment by primitive-type** [comment]
@iambumblehead What do you mean by using a shared thinky instance? I had tried draining the pool before and after tests, but that never made a difference.

**Comment by YannisMarios** [comment]
@primitive-type ... Did you manage to solve this issue with automated tests?

I have the same problem :
Error: ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
