### ISSUE TITLE
execute should not force a cursor

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#325]
Not quite sure why we do. I believe it's a relic from the past (when thinky was using rethinkdb and not rethinkdbdash)

**Comment by neumino** [comment]
Actually it's probably more a mistake. `cursor = false` should be set when we call run. Not the opposite.
Fixed in fabf210db4865d7bf3a53ca482ea55b881b5333c

**Comment by neumino** [comment]
In 2.1.5

**Comment by Vassi** [comment]
This was driving me insane because on one computer cursor.toArray() was working and on another it was blowing up. My NPM packages were not the same. Nice to not have to take a cursor anymore =)
