### ISSUE TITLE
When using batch insert, documents are not validated

### ISSUE THREAD

**Issue by FLamparski** [neumino/thinky#330]
I have an array of documents `xs`. `Stuff.insert(xs, {error: 'replace'})` inserts xs into the table, but allows invalid documents to be inserted. They then cause errors on retrieval. I'm using the current npm version of thinky.

**Comment by neumino** [comment]
Can you provide a script that insert non valid docs?

**Comment by neumino** [comment]
Do you have asynchronous hooks?

**Comment by FLamparski** [comment]
No, I'm just defining a model schema. In particular, I'm defining a field
in a nested object to be string().enum([...]), however the batch insert
lets this field have a value not in the enum.

**Comment by neumino** [comment]
`insert` is the ReQL command and doesn't do validation. Use `Model.save` or use `doc.save`.
