### ISSUE TITLE
r.branch with models

### ISSUE THREAD

**Issue by AusIV** [neumino/thinky#331]
Should I be able to use r.branch with models?

I've tried a couple of different ways. Running

    r.branch(
        models.Model.filter({value: 'test'}).count().gt(0), 
        true, 
        false).run().then(
            function(result){console.log(result)}
        ).catch(
            function(err){console.log(err.message)})

If Model is a simple field with no relationships, I get:

    ReqlDriverError: Cannot convert `r.table("Model")` to datum.. in:
    r.branch({
        _model: undefined,
        _r: undefined,
        _query: r.table("Model").filter({
            value: "test"
        }).count().gt(0),
        _ungroup: false,
        _pointWrite: false
    }, true, false)

But if Model is a field that has relationships I just get:

    RangeError: Maximum call stack size exceeded

If I use r.table(Model.getTableName()) instead of Model, everything works okay, so I have a work around, but it seems messy.

Additionally, I'm wondering if there's any way I can insert a model as the condition of a branch. Since instance.save() doesn't have to be followed with a .run(), it would evaluate when the branch was being built, instead of happening if the condition was met.

**Comment by neumino** [comment]
You should use `execute` instead of `run` in your first snippet. Use `run` only when you return an instance of the Model that starts the query.

**Comment by AusIV** [comment]
I tried that, but then I get

    r.branch(...) has no method execute.

**Comment by neumino** [comment]
Oh sorry, I forgot about that.

You can do:
```
r.branch(
    models.Model.filter({value: 'test'}).count().gt(0)._query, 
    true, 
    false).run().then(
        function(result){console.log(result)}
    ).catch(
        function(err){console.log(err.message)})
```

Or
```
models.Model.filter({value: 'test'}).count().gt(0).branch(true, false).execute()
    .then(
        function(result){console.log(result)}
    ).catch(
        function(err){console.log(err.message)})
```
