### ISSUE TITLE
Thinky attempts to validate deleted doc results

### ISSUE THREAD

**Issue by MarkHerhold** [neumino/thinky#333]
It seems to me that Thinky is validating the document results (deleted, errors, inserted...) on a delete operation against model schema.

This isn't my exact code, but you will get the idea:
```js
var Model = thinky.createModel(this.tableName, {
            id: type.string().required(), // some unique id
            color: type.any().required()
        });

var result = yield Model.getAll('group1', { index: 'groupIndex' }).filter({ color: 'green' }).limit(1).delete()
```

That eventually throws an error saying `Document failed validation: Value for [id] must be defined.`

I put in a breakpoint at [util.js#L263](https://github.com/neumino/thinky/blob/master/lib/util.js#L263) and traced the stack back to [object.js#L136](https://github.com/neumino/thinky/blob/master/lib/type/object.js#L136).

Thinky is calling

```js
schema["id"].validate(object["id"], "[id]", undefined)
```
where `schema["id"]` evaluates to `TypeString` (as expected) and `object["id"]` evaluates to `undefined` (not as expected). The object Thinky is trying to validate is actually the normal query result from RethinkDB.
```js
{"deleted":1,"errors":0,"inserted":0,"replaced":0,"skipped":0,"unchanged":0}
```

Is this expected behavior or am I doing something stupid? It makes little sense to me that Thinky would try to validate the delete result object against the model schema.

RethinkDB 2.1.2
Thinky 2.1.6 (rethinkdbdash 2.1.7)

**Comment by neumino** [comment]
Call execute after delete not run since your query doesn't return an instance of the model.
