### ISSUE TITLE
addRelation throws "has no method .run()" error

### ISSUE THREAD

**Issue by kheide** [neumino/thinky#335]
addRelation throws the following error
```
TypeError: Object [object Promise] has no method 'run'
```

Workaround is to do:
```
Users.get(ID).run().then(function (user) {
user.roles.push(roleId);
user.save();
});
```

Is this intentional?

**Comment by neumino** [comment]
You don't need to call `run` on `addRelation`. There was a bug in the docs that I just fixed.
