### ISSUE TITLE
sharding, replication, durability settings for tables

### ISSUE THREAD

**Issue by mwielbut** [neumino/thinky#337]
Is it possible to specify these settings in Thinky or do they need to be maintained after-the-fact via server administration?

**Comment by neumino** [comment]
Hum it's currently not possible. It's doable though to create tables with the appropriate settings. Changing the config if the table already exists is probably a bad idea though.

**Comment by recitate** [comment]
Exactly. Would a great to be able to specify "create" options so we don't need to remember to go into the database each time a new model is created and adjust them manually. Updating seems risky and overkill.

**Comment by mwielbut** [comment]
Exactly. Would a great to be able to specify "create" options so we don't need to remember to go into the database each time a new model is created and adjust them manually. Updating seems risky and overkill.

**Comment by MarkHerhold** [comment]
I think this issue can be closed. `thinky.createModel(tableName, schema, options);` has the options parameter which takes a key called `table` which gets passed to rethinkdbdash's tableCreate function specifying shard and replication settings.

See the `options.table` param in the [docs](https://thinky.io/documentation/api/thinky/#createmodel).

**Comment by neumino** [comment]
Y

**Comment by esatterwhite** [comment]
@neumino Is there a way to specify durability settings on the `save()` / `saveAll()` call on a document?

**Comment by neumino** [comment]
@esatterwhite -- no, it's currently not available. It's just a matter about properly passing the option to the write operation I think.
