### ISSUE TITLE
where to use run() method?

### ISSUE THREAD

**Issue by almasakchabayev** [neumino/thinky#343]
Could you please suggest some guidelines on where to use run() method. Docs are not very clear about it.

**Comment by almazyankudapropal1** [comment]
Almazyan kuda ty propal?

**Comment by almazyankudapropal1** [comment]
napishi mne

**Comment by neumino** [comment]
@almasakchabayev -- Use `run` when your query returns instances of your model, and `execute` otherwise.

**Comment by almasakchabayev** [comment]
but I do not have to use run(), right? for instance: 
```
return await UserModel; // returns all users as models
```

**Comment by almasakchabayev** [comment]
Could you please elaborate in context of async/await, is it same behaviour for both

Tnank you and sorry for so many questions, just moved from sql straight to rethinkdb/thinky...

**Comment by neumino** [comment]
If you await/yield on a query, it will automatically run it for you and return the promise.

If you want to call `execute`, you have to explicitly calling it with await/yield.
