### ISSUE TITLE
how to retrieve only joined documents of the given model

### ISSUE THREAD

**Issue by almasakchabayev** [neumino/thinky#345]
Model.getJoin(modelToGet) retrieves all fields of the Model and assigns all the joined documents to the property. i.e
```
Post.get("0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a").getJoin().run().then(function(result) {
  /*
  result = {
    id: "0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a",
    title: "Hello World!",
    content: "This is an example.",
    idAuthor: "3851d8b4-5358-43f2-ba23-f4d481358901",
    author: {
      id: "3851d8b4-5358-43f2-ba23-f4d481358901",
      name: "Michel",
      email: "orphee@gmail.com"
    }
  }
  */
});
```
But how to retrieve only the joined documents as an array? i mean I do not need all properties of Model, just joined documents as array, i.e.:
```
Post.get("0e4a6f6f-cc0c-4aa5-951a-fcfc480dd05a").getJoin().ignore().run().then(function(result) {
  /*
  result = {
      id: "3851d8b4-5358-43f2-ba23-f4d481358901",
      name: "Michel",
      email: "orphee@gmail.com"
    }
  */
});
```

**Comment by neumino** [comment]
The short answer is "You cannot". I guess your question is driven by some performance concern, but you probably have to load the document you don't want to return anyway, so returning it is not going to cost much.
