### ISSUE TITLE
Bug: null doesn't fail validation required()

### ISSUE THREAD

**Issue by avimar** [neumino/thinky#348]
```
var thinky= require('thinky')();
var type = thinky.type;

var MyNumber = thinky.createModel("MyNumber", {
	number:			type.number().integer().min(1000000).max(99999999999999999999).required()
	}, {pk: 'number'});


MyNumber({number:null, account: 'ee46e031-636c-4e3d-b115-0ceb958f11d1'}).save().then(console.log).catch(console.error);
//[Error: Primary keys must be either a number, string, bool, pseudotype or array (got type NULL):
null]
MyNumber({number:10, account: 'ee46e031-636c-4e3d-b115-0ceb958f11d1'}).save().then(console.log).catch(console.error);
//{ [Document failed validation: Value for [number] must be greater than 1000000.] message: 'Value for [number] must be greater than 1000000.' } <-- expected
```

Null somehow passes the integer required and the error comes back from rethink and somehow passes validation.

Second test: I left out the pk:'number' and it actually inserted, as expected:
```
{ number: null,
 account: 'ee46e031-636c-4e3d-b115-0ceb958f11d1',
 id: '0d2c5c60-b800-470b-968f-0b2bbf8d4908' }
```

**Comment by neumino** [comment]
This was a doc issue, I just updated the schema page.

`required` just check for undefined. If you want to forbid `null`, you have to use `allowNull(false)`

**Comment by avimar** [comment]
wow that's seriously unexpected.
If I define a validation and say it's required, then doesn't that mean it also has to fit the validation? Why doesn't it fail number().integer() validation??

**Comment by neumino** [comment]
Because if we were trying to validate `null` against any type or any property, it would always fail, making `null` never a valid value.

By default `null` is a valid value for all types. Use `allowNull(false)` if you don't want that. `required` just check for `undefined` values.
