### ISSUE TITLE
Generate your own id attribute for new documents

### ISSUE THREAD

**Issue by jondubois** [neumino/thinky#359]
I would like to create a new document using:

```
var post = new Post({
    id: 'mycustomid',
    title: "Hello World!",
    content: "This is an example."
});

post.save();
```

But when I run this, it creates two documents in the 'Post' table (which is incorrect): One of the documents has the id 'mycustomid' (as expected) and the other document is identical except it has an id (uuid) generated by thinky (which I don't want for my particular use case).

How can I generate my own id for a new document without Thinky creating a duplicate?

**Comment by neumino** [comment]
I'm not sure what you do, but this is probably an issue with some of your code. If I run your script I get only one document with the primary key `mycustomid`

**Comment by jondubois** [comment]
@neumino Ah, yes it was my code, thanks!
