### ISSUE TITLE
Proposal: Avoid table/db name conflicts in fully connected clusters

### ISSUE THREAD

**Issue by tlperkins** [neumino/thinky#361]
See: https://github.com/rethinkdb/rethinkdb/issues/4898

If a node process is spun up with multiple instances, think pm2 app.js -i 4, then we will have multiple copies of the same tables for each model.  Thinky should use some strategy to avoid creating duplicate tables if it is found that the table for a model doesn't exist.  Any way for thinky to help avoid creating multiple tables?  

Maybe if the user creates a "thinky_model_lock" table ahead of time, that table can be used to manage grabbing a lock (document) for creating model tables on the fly, since documents are atomic.

**Comment by neumino** [comment]
Thinky creates table for you to make development nicer.

In prod, you spin up a script that imports all your models/relations first and then start your scripts with `init: false`
