### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#365]
So I spent some time this week end to look at GraphQL, and we could support a `graphQL` command that would spin up an http server that can take a graphQL query as an input and fetch the related documents.

The problem with the official library - https://github.com/graphql/graphql-js -  is that you can't do server side joins. Facebook seems to consider it's ok because they cache everything...
So we would have to write our own implementation of graphql.
- First we need to parse the graphQL query. There are a few parser in the wild, but I'm not sure which one is good
- Implement the transition from a GraphQL query to a thinky query
- Maybe fix https://github.com/neumino/thinky/issues/186 while we are at it

**Comment by rt2zz** [comment]
fwiw I think app based joins would be an acceptable trade off for many apps

**Comment by ondreian** [comment]
Is there anyway to return the relational links in the DB from normal queries that use joins?

`Note: The links saved in the database are hidden from the result.`

They are included in the feeds for a given query, and this would make app-based joins way easier in the short-term whilst this all shakes out.

**Comment by gyzerok** [comment]
It seems like you just need to write custom executor. Parser and validator can be used directly from graphql-js

**Comment by rodrigopivi** [comment]
this would be a great feature, are we too far away from this?

**Comment by fenos** [comment]
Hi guys, I created a **GraphQL** implementation on top of thinky ORM. It has been challenging and fun to made up [graphql-thinky](https://github.com/fenos/graphql-thinky) and I also have some feedback for **thinky** which i'll open a ticket next days. The repository is very new, I wish a good community support to make it as production ready as possible. Please give a visit or two :) Feedbacks are very welcome

**Comment by wookoouk** [comment]
I feel like this is a little beyond the scope of the project, maybe a separate project for this?

**Comment by grantcarthew** [comment]
Agreed, closing.
