### ISSUE TITLE
@question - is it possible to pass an array of IP addresses for my RethinkDB cluster?

### ISSUE THREAD

**Issue by lewisbarber** [neumino/thinky#370]
Currently I can only specify one IP address in the app, which causes the app to fail if that database in my cluster goes down.

**Comment by neumino** [comment]
Yes, all options are forwarded to the driver rethinkdbdash.
So you pass an array in `servers`, or flip `discovery` to `true`.
See https://github.com/neumino/rethinkdbdash/blob/master/README.md

**Comment by joshua1** [comment]
The thinky documetation should be updated then to show ```servers``` as one of the options passed in , not just ```host``` and ```port``` or should say all rethinkdbdash options

**Comment by neumino** [comment]
Want to send a PR? :)
