### ISSUE TITLE
Disable DocumentNotFound behaviour

### ISSUE THREAD

**Issue by sandcastle** [neumino/thinky#371]
It would be ideal if we could provide a mechanism to disable the default behaviour of throwing DocumentNotFound. There are a few scenarios where the default behaviour results in more code than is ideal, if there was a way in which we could disable this behaviour on the driver then it would allow the user to decide what works best for them.

Below is an example from a Koa project im working on  - the disabled behaviour reads far easier than the current behaviour.

#### Default behaviour
```javascript
  var tournament;
  try{
    tournament = yield models.TournamentGame.get(this.params.tournamentId);
  }
  catch (err) {
    this.throw('Invalid tournament', 400);
  }

  // magic here...
```

#### Disabled behaviour
```javascript
  var tournament = yield models.TournamentGame.get(this.params.tournamentId);
  if (!tournament){
    this.throw('Invalid tournament', 400); 
  }

  // magic here...
```

**Comment by neumino** [comment]
You can use `_get` instead.

That being said, you still have to catch connection errors...

**Comment by sandcastle** [comment]
Thanks for getting back to me. 

I would be more comfortable if this was a public API, but will use for now.

**Comment by neumino** [comment]
Also for what it's worth, if you use `_get` you need to use `execute`, not `run`.

**Comment by neumino** [comment]
`_get` is also public-ish, it was added for #299 (which is roughly the same issue)
