### ISSUE TITLE
How to use post("init") hook?

### ISSUE THREAD

**Issue by gutenye** [neumino/thinky#372]
I read it from the documentation http://thinky.io/documentation/api/model/#post

```
var User = thinky.createModel("users", {})
User.post("init", function(next) {
  next()
})
new User().then(user => {
  console.log(user)     // -> [undefined]
})
```

It does not work.

I do not read the code, why post init hook return a promise?

**Comment by neumino** [comment]
Thanks for the report.
Fixed in 2.1.10
