### ISSUE TITLE
Mass Assignment

### ISSUE THREAD

**Issue by niallobrien** [neumino/thinky#373]
I'm just wondering how we deal with mass assignment when using something like Express? Thanks in advance,

**Comment by neumino** [comment]
Can you elaborate what your concerns are?
My guess is that you want `allowExtra` or `removeExtra`.

**Comment by niallobrien** [comment]
Yes, so if `req.body` contains un-needed fields ie. the user has tried to add their own fields to a form's POST, I want to make sure that I only allow what's expected to come through.

**Comment by pthm** [comment]
Surely you should be sanitising your users input before you save it?

**Comment by neumino** [comment]
`allowExtra(false)` is the way to go in my opinion.
Then make sure that your HTTP server drops huge payloads before parsing them if DDOS is your concern.

**Comment by niallobrien** [comment]
@pthm Sanitising user input is a different concern imo.
@neumino Thanks, that's exactly what I was looking for.
