### ISSUE TITLE
How to make .validator execute?

### ISSUE THREAD

**Issue by flockonus** [neumino/thinky#376]
Hi!

I'm having a problem with defining a validation, apparently it doesn't run unless a value was set for it, which makes sense most of the time, but I can't get this particular case to run, is there any advice?

```js
'use strict';

var thinky = require('thinky')();

var r = thinky.r;

var type = thinky.type;

var Token = thinky.createModel('Token', {
  foo: type.string().validator(neededIfBar),
  bar: String,
});

var t = new Token({
  bar: 'hi there'
});

t.save().then(works, fail);


function neededIfBar () {
  var instance = this;
  console.log('validation time!', instance);
  if(this.bar && !this.foo){
    return false;
  }
  return true;
}

function works (m) {
  console.log('works',m);
  process.exit(0);
}

function fail (e) {
  console.log('fail', e);
  process.exit(0);
}
```

**Comment by flockonus** [comment]
On another note, is there a plan to make validator accept Promise? I was scanning through the code and could only figure it would imply some bigger changes, maybe it's something i'd be able to contribute if you want to release on a major number(?)

**Comment by neumino** [comment]
Validation is not performed if the field is undefined and if the field is
not required. The validator is not expected to handle undefined value,
thinky is.

Your function should also take the value of the field as argument. The
context is not set to the value.

About promise nop this is not planned. Hooks are the way to go if you want
asynchronous operation.

I'll add a clear example in the docs when I'll have access to my desktop.

**Comment by flockonus** [comment]
Thank you @neumino! It clears out my question.

I still believe a promise to be returned could be very valuable in cases we are checking things that act like "foreign keys" in many ways, so boolean or a Promise which is a big part (imho) what makes thinky great. [mocha](https://mochajs.org/) behaves in a similar way, also allowing for a `done()` callback.

Obs about `.required()` it seems to make the validation fail before checking my other `.validation` when the field is undefined.

I solved my issue by using a validator on the schema. This is the function:

```js
function needUserId () {
  var instance = this; //jshint ignore:line
  if(instance.domain === 'user' || instance.domain === 'client'){
    if(instance.userId == null){
      return false;
    }
  }
  return true;
}
```
