### ISSUE TITLE
SSL parameter support

### ISSUE THREAD

**Issue by tommaitland** [neumino/thinky#377]
Sorry if this is already all possible and I just haven't been able to find it, but I'm trying to connect to a Compose.io RethinkDB database with an app built on Thinky and compose requires you to use the `ssl` parameter while connecting to the DB.

See https://www.compose.io/articles/rethinkdb-and-ssl-think-secure/

I've done some digging through the module, and though `authKey` is supported when you import thinky, it seems `ssl` isn't. Would it be an easy thing to add in? Or any work arounds?

**Comment by neumino** [comment]
It should already work. The options are directly passed to the driver.

**Comment by chippawah** [comment]
@neumino I'm trying to write a config script that will create an ssl connection to a compose.io instant take all the same options as the the driver but I don't know the best way to export thinky after the async read of the ca_cert. I'm referencing this article for the ssl cert https://www.compose.io/articles/rethinkdb-and-ssl-think-secure/

**Comment by neumino** [comment]
You can export a promise.
