### ISSUE TITLE
Bluebird 3 Support

### ISSUE THREAD

**Issue by artdude543** [neumino/thinky#378]
Would is be possible to add support for Bluebird 3? Either on master or another branch. You can find the main changes here: http://bluebirdjs.com/docs/new-in-bluebird-3.html But that main issue for this module is the deprecation on `settle` which breaks this module.

**Comment by neumino** [comment]
Doesn't it already work with the last version of rethinkdbdash?

**Comment by artdude543** [comment]
I'm getting errors when trying to use the changes feature. With the new version of bluebird.

`Unhandled rejection ReqlOpFailedError: Database 'name' already exists in:`

But downgrading bluebird the version stops the error from being thrown.

**Comment by artdude543** [comment]
Also might want to update the required version of rethinkdbdash as the new version of NPM ignores the `~` flag and installs the version specified instead.

**Comment by artdude543** [comment]
2.1.14 of rethinkdbdash is not pushed to npm to be usable for the Bluebird fix.

**Comment by neumino** [comment]
Hum let me check that tonight once I get on my laptop.

**Comment by paambaati** [comment]
+1 on the issue. I get the same `ReqlOpFailedError` as Thinky is trying to create the database.

**Comment by artdude543** [comment]
Any chance of getting v2.1.14 pushed to NPM for rethinkdbdash?

**Comment by neumino** [comment]
Pushed rethinkdbdash 2.1.14. I believe it should work. Please re-open the bug if it doesn't.

**Comment by artdude543** [comment]
Re-installed 2.1.14 and getting the same error/crash as posted on the other issue. Here is the error with more details.

```
Warning: a promise was created in a handler but none were returned from it
02/11/2015 02:45:13 [INFO] [Core] SocketIO is not listening to new connections. 
    at Pool.createConnection (~\node_modules\rethinkdbdash\lib\pool.js:197:51)
    at Pool._expandBuffer (~\node_modules\rethinkdbdash\lib\pool.js:311:10)
    at PoolMaster._expandAll (~\node_modules\rethinkdbdash\lib\pool_master.js:142:27)
    at ~\node_modules\rethinkdbdash\lib\pool_master.js:135:12
From previous event:
    at PoolMaster.getConnection (~\node_modules\rethinkdbdash\lib\pool_master.js:127:12)
    at ~\node_modules\rethinkdbdash\lib\term.js:146:28
From previous event:
    at Term.run (~\node_modules\rethinkdbdash\lib\term.js:145:21)
    at Thinky.dbReady (~\node_modules\thinky\lib\thinky.js:70:4)
    at new Thinky (~\node_modules\thinky\lib\thinky.js:55:8)
    at module.exports (~\node_modules\thinky\lib\thinky.js:144:10)
    at new Thinky (~\index.js:30:34)
    at ~\index.js:67:16
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by neumino** [comment]
Isn't that an issue with socket.io?

If not, can you provide a script that triggers this error?

**Comment by artdude543** [comment]
The SocketIO log is from my node app and just happened to get in while the Promise error was being thrown.

**Comment by neumino** [comment]
Can you provide a script to reproduce this issue?

**Comment by artdude543** [comment]
I'm trying to figure out what's causing the issue but after reading up on somethings `nodeify` should be changed to `asCallback` not sure if this would fix the issue but it's something to note probably.

```
Warning: a promise was created in a  handler but was not returned from it
    at Pool.getConnection (~\node_modules\rethinkdbdash\lib\pool.js:72:11)
    at Pool.<anonymous> (~\node_modules\rethinkdbdash\lib\pool_master.js:405:12)
    at emitOne (events.js:77:13)
    at Pool.emit (events.js:169:7)
    at Pool.putConnection (~\node_modules\rethinkdbdash\lib\pool.js:164:10)
    at ~\node_modules\rethinkdbdash\lib\pool.js:277:10
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Pool.createConnection (~\node_modules\rethinkdbdash\lib\pool.js:197:51)
    at null._onTimeout (~\node_modules\rethinkdbdash\lib\pool.js:53:14)
    at Timer.listOnTimeout (timers.js:92:15)
```

For code all I'm doing is creating a custom wrapper which I use for my applications for easier model management. But none of these issues persisted in Bluebird 2.

**Comment by neumino** [comment]
Are you importing bluebird and setting up a different config?

**Comment by neumino** [comment]
This error should be just a warning:
http://bluebirdjs.com/docs/warning-explanations.html

Not sure what in your code for this warning to be an error.

**Comment by artdude543** [comment]
I do have my node env set to development which could be the cause of the warnings. But in theory should they not be throwing in the first place? Or am I missing interpreting the warning. (Sorry still kind of new to Promises and it's errors/warnings)

**Comment by artdude543** [comment]
So yeah changing my env to `dev` stopped the messages from showing. But unsure to why just with the new version of Bluebird the messages decide to show. Unless it's a logic flag with the logging?

**Comment by neumino** [comment]
These should be warnings, so I'm not sure what in your code make those errors.
