### ISSUE TITLE
Populate array of keys while joining

### ISSUE THREAD

**Issue by olasfar** [neumino/thinky#384]
Hey guys,

I wasn't able to populate a list of keys while joining on an other table so I was wondering if my models are correct and if what I'm trying to do is possible with Thinky, here is my code:

`Group` model
```
  var Group = thinky.createModel('group', {
      users: [thinky.type.string()],
      place_id: thinky.type.string()
  });
```
`User` model
```
  var User = thinky.createModel('user', {
      name: thinky.type.string()
  });
```
`Place` model
```
  var Place = thinky.createModel('place', {
      name: thinky.type.string()
  });
  Place.hasMany(Group, "groups", "id", "place_id");
```

I'd like to fetch all the `groups` with user's name & place's name for a `place_id`

Here is what I've done:

```
Place.get(PLACE_ID).getJoin({groups: true}).then(function(g){console.log(g);})
```

How can I populate the user's name ? Using `_apply` ? How ?

Thank you in advance :)

**Comment by neumino** [comment]
Thinky does join in a SQL way. See http://thinky.io/documentation/relations/

If a user can belong to multiple groups:

```
  var Group = thinky.createModel('group', {
      id: thinky.type.string(),
      place_id: thinky.type.string()
  });
  var User = thinky.createModel('user', {
      id: thinky.type.string()
      name: thinky.type.string()
  });
  var Place = thinky.createModel('place', {
      name: thinky.type.string()
  });
  Place.hasMany(Group, "groups", "id", "place_id");
  Group.hasAndBelongsToMany(User, 'users', 'id', 'id')

  Place.get(PLACE_ID).getJoin({groups: {users: true}}).then(function(g){console.log(g);})

```

**Comment by olasfar** [comment]
Thanks @neumino for your answer it works just great :)
BTW, do you know how then I can get the Places for a particular User ? This doesn't work:

`Place.getJoin({groups: {user: true}}).filter({groups: {users: {id: "1358944112"}}}).then(function(p){console.log(p)})`

Should I use the `_apply` parameter and then filter on groups ?

Thanks in advance.

**Comment by neumino** [comment]
```
User.hasAndBelongsToMany(Group, 'groups', 'id', 'id')
Group.belongsTo(Place, "place", "id", "place_id");

User.get("132132").getJoin({groups: {place: true}})
```
