### ISSUE TITLE
Change attribute in multiple documents at the same time

### ISSUE THREAD

**Issue by andela-omesanni** [neumino/thinky#386]
Hi,

I have document called Industry and industry has phases and phases has stages etc. Something like this:
```javascript
{
  name: 'film',
   id: 1,
  archived: false,
  phases:[{
   id: 2,
    name: 'production',
   industry_id: 1,
   archived: false,
   stages: [{
    name: 'inception',
    phase_id: 2,
    archived: false
  }]
 }]
}
```

Now when an industry is archived, it means that all the phases get archived and the stages are under each phase gets archived too. As you will notice, they are have an archived attribute. So what I am trying to achieve is that once I set the archived attribute of the industry to true it should go and set all the archived attribute of all directly and indirectly joined documents to true also. The way I am currently doing it is just very efficient. I am looping thru a lot nested arrays which have nested objects which in turn have arrays, and then i fetch each document with their ids and then change their archived attribute and then save.

I am wondering if saveAll could do this where if change the industry archived attribute to true and then call industry.saveAll() it would go and change all the archived attributes of all the joined documents to true too

**Comment by neumino** [comment]
You should be able to do that with a `pre` hook on your Model.

**Comment by andela-omesanni** [comment]
please can you just give me an example relating to my question?

**Comment by neumino** [comment]
http://thinky.io/documentation/api/model/#pre

You still have to loop over the document yourself and update the `archived` field. The pre hook just let you automatically call this method when you save the document.
