### ISSUE TITLE
Best practices for creating tables and indexes in production?

### ISSUE THREAD

**Issue by rgrove** [neumino/thinky#389]
I'm trying to figure out the best way to configure Thinky for production usage in an environment where I'll be running multiple servers, each with a pool of Node processes.

The advice given in issue #332 is to pass `{init: false}` to `createModel()`, then use a script that calls `model.ready()` on each model when you want to create tables and indexes. Unfortunately, this doesn't work. [Table creation is always skipped](https://github.com/neumino/thinky/blob/4b35235107e0ce9696318bffecdb5ea2693f1f4c/lib/model.js#L196) when `init` is `false`, and `model.ready()` doesn't actually do anything to ensure that indexes have been created.

Is this a bug, or have I misunderstood? Is there a better way to manage table and index creation in a production environment?

**Comment by neumino** [comment]
Sorry for the late answer, it slipped through the cracks.

Your node processes that uses thinky shouldn't create tables/indexes themselves. You should have another script like mentionned in https://github.com/neumino/thinky/issues/332#issuecomment-136091307

Then just rn the script before starting the node processes that uses the required tables.

**Comment by neumino** [comment]
I closed the issue, but if you still have questions, feel free to ask them here.
