### ISSUE TITLE
Is a global model safe?

### ISSUE THREAD

**Issue by paulstefanday** [neumino/thinky#390]
Is it ok to make a model a global variable so I can do queries without needing to require it? People generally say using globals are bad but it would make things a little bit cleaner. Is this possible?

I have imported thinky as instructed in the docs: https://thinky.io/documentation/architecture/

User.js
```
var 	config = require(__base+'/config/vars.js'),
	thinky = require(__base+'/config/thinky.js'),
	type = thinky.type,
	r = thinky.r,
	validator = require('validator')

var User = thinky.createModel("users",{
    id: type.string(),
    email: type.string().email().required(),
    password: type.string().required(),
    createdAt: type.date().default(function() { return new Date() })
});

module.exports = User;
```

server.js
```
global.User = require('./User')
```

**Comment by neumino** [comment]
People can say anything they want, at the end of the day you are still free to write the code you want.
It's fine to put the model in global, but you still want to make sure that you saved the model in global before actually using it.

**Comment by andela-idurotola** [comment]
hi when I try to update a model with hasAndBelongsToMany relationship I get an error : [TypeError: Cannot read property 'new_val' of undefined]

**Comment by neumino** [comment]
Please open a new issue with a full stacktrace and a script to reproduce it.
