### ISSUE TITLE
getting a typerror on save with joined documents

### ISSUE THREAD

**Issue by andela-idurotola** [neumino/thinky#391]
I get this error when trying to save the modification to the joined documents:
[TypeError: Cannot read property 'new_val' of undefined]
however if the joined documents were untouched the file saves without error

**Comment by neumino** [comment]
What's the full stacktrace? Do you have a script to reproduce this error?

**Comment by andela-idurotola** [comment]
Hi,
What happens is that if I update only the relationship and nothing else the
error is thrown on the save operation,
I figured that If anything at all about the model is changed then
everything including the relationships too saves correctly
the error shown in the trace comes from the console that I added to the
error callback on the save.

**Comment by neumino** [comment]
I can't reproduce that.
Can you please provide a snippet to reproduce this error?

**Comment by andela-idurotola** [comment]
Hi Michel,
I hope this stacktrace helps I started getting this error after I upgraded
to  rethink 2.2.1.
for reproduction you have to modify only the relationships in a model.
so say you have a model A with name, id, and a hasMany relationship with
model B, if you modify
model A from having B1 to having B1, B2. it thows that error.

**Comment by neumino** [comment]
This works fine for me:
```
var thinky = require('./lib/thinky.js')();
var type = thinky.type;
var r = thinky.r;

var User = thinky.createModel("User", {
  id: type.string()
});
var Post = thinky.createModel("Post", {
  id: type.string(),
  title: type.string(),
  userId: type.string()
});

User.hasMany(Post, "posts", "id", "userId");

var user = new User({
  posts: [
    {title: "foo"}
  ]
})

user.saveAll({posts: true}).then(function(result) {
  user.posts.push(new Post({title: "bar"}));
  return user.saveAll({posts: true});
}).then(function() {
  console.log("Done");
});
```

Did you update thinky when updating RethinkDB?
