### ISSUE TITLE
No 'update' event

### ISSUE THREAD

**Issue by nfantone** [neumino/thinky#393]
I'm trying to modify some fields before updating a document, but it seems like there's actually no event being fired while using `Model.update`. #346 shows this as an approach:

```javascript
Model.docOn('saving', function(doc) {
  doc.updatedAt = new Date();
});
```

But that only works while calling `doc.save()`. Is there any way I could get this to work with something like the following?

```javascript
Model.get(id).update(partial).run()
```

**Comment by neumino** [comment]
Hum, no that's not possible because there's no document on which we can emit the event.

**Comment by nfantone** [comment]
@neumino What do you mean _"no document"_? You *are* updating a document.

**Comment by nfantone** [comment]
Take a look at jsdata approach: http://www.js-data.io/docs/events

Those events are emitted on its `DSRethinkDBAdapter`.

**Comment by ondreian** [comment]
@nfantone that is because JSData is an in memory store, and the document has already been queried and returned from RethinkDB to JSData.  This is a REQL query, so the document is not returned from the database before the changes occur: http://www.rethinkdb.com/api/javascript/#update

**Comment by nfantone** [comment]
@ondreian Ok, I see your point. Any workaround?

**Comment by ondreian** [comment]
You could define a custom static with [Model.prototype.defineStatic](http://thinky.io/documentation/api/model/#defineStatic)

```js
// using ES6 default args feature
Model.defineStatic( 'updateWithTimestamp', function (fields = {}) {
   fields.updatedAt = Date.now();
   return this.update(fields);
});

Model.get(id).updateWithTimestamp(whatever).run()
```

**Comment by nfantone** [comment]
@ondreian Yeah, that's what I had before. Thanks for your responses, people.
