### ISSUE TITLE
Make an atomic 'save' with a checking before it ?

### ISSUE THREAD

**Issue by vieks** [neumino/thinky#398]
I have an User model and make a 'save' call to insert a new one.
But I want to check the database before saving it. Indeed I don't want the user to insert having the same email and name from another existing already.
I see on the doc this is the purpose of 'pre' but it seems that it doesn't perform in an atomic way with  'save'. It a '2 steps' roundtrip with the database can you confirm it ?

If true, making this:
```javascript
  User.pre('save', next => {
      const exist = ...; // check db if the current user this.email and this.name exist on db
     if(!exist)
        next();
    else
        next(new Error('email and name already in use'))
  });
```

Absolutely not guarantee a safe insert because in case of high concurrency many threads can do the same 'pre' check call so giving the access for making a 'save' whilst another thread is performing a 'save' meantime !

The solution will be to implement r.branch on replace from 'save' ( such as shown here [http://stackoverflow.com/a/21617614](http://stackoverflow.com/a/21617614) ) and giving an access through your api with a callback on 'save' permitting to write the test condition for 'r.branch' **OR** even link 'pre' with 'save' with an inner cached test resulting from 'pre' to apply only at 'save' call time.

**Comment by neumino** [comment]
RethinkDB provides atomicity on a document level. And the only way to ensure that a value is not used in another document is to use the field as a primary key.
Alternatively, you can build a distributed lock using a single document.

**Comment by vieks** [comment]
Indeed I am new with rethinkDB and I think at least it was possible to handle that kind of atomicity...
Pretty bad for my use case :( 

Thx dude for your answer.
