### ISSUE TITLE
Merging updates to partial doc removes props

### ISSUE THREAD

**Issue by mattkrick** [neumino/thinky#400]
I have a doc in my DB: `{id: '123', dateCreated: 'today', email: 'foo@bar.com'}`

I get it like this (excluding the date): `user = await User.get('123').pluck('id', 'email').run();`

I add a field saying that the email address was verified: `await user.merge({isVerified: true}).save()`

My doc now looks like this (notice that `dateCreated` is missing): `{id: '123', isVerified: 'true', email: 'foo@bar.com'}`

This was a big gotcha for me since I'd assume that my fields would be merged with what was already in the DB, but it actually acts more like a replace. Is this working as designed? If so, is there a way to perform a merge from the document without retrieving the whole doc, or should I go from the Model?

**Comment by neumino** [comment]
Yes this is working as expected. You can use `User.get('123').update({fsVerified: true})` if you want.

**Comment by neumino** [comment]
The reason why it overrides field is that you need a way to delete fields.
