### ISSUE TITLE
How can I make this work with JSON schemas?

### ISSUE THREAD

**Issue by cggaurav** [neumino/thinky#402]
json-schema.org

**Comment by neumino** [comment]
Hum, I'm not sure what you are expecting from this question, but there's no automatic conversion. So you have to manually parse your json schema to create a thinky one.

**Comment by no-more** [comment]
I think he would like to be able to define thinky models with a json-schema, that would be great to have something not specific to thinky. Some model definition that could be use in the front-end validation too for example.
