### ISSUE TITLE
[Question] Don't retrieve patient when there's no relation with hospital

### ISSUE THREAD

**Issue by eduardonunesp** [neumino/thinky#403]
I have the following relation between Hospital and Patient, which is a Many To Many relationship, so a Doctor want to retrieve a Patient data, but only if the doctor belongs to a Hospital.

```
const Patient = thinky.createModel("patient", {
  id: type.string(),
  last_name: type.string().required(),
  first_name: type.string().required(),
});

const Hospital = thinky.createModel("hospital", {
  id: type.string(),
  name: type.string().required()
});

Patient.hasAndBelongsToMany(Hospital, "hospitals", "id", "id");
Hospital.hasAndBelongsToMany(Patient, "patients", "id", "id");
```

I want to retrieve the patients only if have relationship with certain hospital in `hospital_id`.

```
    const patients = yield Patient
      .getAll(this.params.id)
      .getJoin({
        hospitals: {
          _apply: seq => {
            return seq.filter(row => {
              return row('id').eq(hospital_id);
            });
          }
        }
      });
```

Well, in some cases there's no relation, so I expect that patient isn't returned, so I'll response a 404 in API, but the Patient data is retrieved with `hospitals` field as a empty array.

```
model {
  id: 'a7503dd4-0dba-46ab-8291-1a61a955abf5',
  email: 'mokpok@uhen.net',
  first_name: 'Luis',
  last_name: 'Carroll',
  hospitals: []
}
```

I have worked in some code to filter that after the query, removing Patients no relationship field, But I want to do that in a REQL, is that possible ?

**Comment by neumino** [comment]
Hum, a few things:
1. Can a patient belongs to multiple hospitals? If no, you should use `belongsTo` relation and things are a bit simple since you can just read the local foreign key.

2. While your query works, it is really akward. The filter you are explicitly adding is doing exactly the same thing as what the join is doing under the hood with an index. So it's effectively a no op

3. Theres' no shorcut at the moment if you really need a `hasAndBelongsToMany` relation. This is what you are looking for:

```
Patient.getAll(...).getJoin({hospitals: true}).filter(function(patient) {
  return patient('hospitals').isEmpty().not()
})
```

**Comment by neumino** [comment]
I'm closing the issue, but feel free to ask more questions if you want.

**Comment by eduardonunesp** [comment]
Thanks for your help and patience @neumino, your snippet solved my problem

**Comment by eduardonunesp** [comment]
Hey @neumino, 

Do I missing something ? because I have added another filter to get all patients from the `hospital1` only, but it returns for `hospital1` and `hospital2` as well. Also the relation is many to many for `patients` and `hospitals`.

```javascript
function *index() {
  
 let  patients = yield Patient
      .getJoin({ hospitals: true})
      .filter(patient => {
        return patient('hospitals').filter(hospital => {
          // get only for the hospital1
          return hospital('id').eq(this.req.user.hospital_id); 
        });
      })
      .limit(this.limit)
      .skip(this.offset)
      .run();
  }

  this.body = {
    status_code : 200,
    data        : patients
  };
}
```

**Comment by neumino** [comment]
Never mind I misread your query :)
