### ISSUE TITLE
conditional validations

### ISSUE THREAD

**Issue by panbhag** [neumino/thinky#404]
I am not able to figure out how to write validations which depend on other field values.
So lets say in user model, the field age is required only when the field status has a value of "active".
The validator function only receives the current value of the field, I am not sure if its possible to access the whole user object in the validator function. Please suggest.

**Comment by neumino** [comment]
You can use `validator` on the top level object

```
var User = thinky.createModel("User", type.object({
  id: type.string(),
  name: type.string()
}).validator(console.log));
```
