### ISSUE TITLE
thinky pollutes built-in util module

### ISSUE THREAD

**Issue by simonratner** [neumino/thinky#405]
Presently, this is causing some of my tests to fail because the contents of built-in util module changes depending on whether it is imported before or after thinky. More generally, it just isn't a very clean thing to do, and may result in future conflicts.

What I do in my own code is copy over all built-in util methods into my util module, rather than the other way around:
```js
module.exports = _.defaults(module.exports, builtinUtil);
```
Thinky could do something similar.

**Comment by neumino** [comment]
Hum, this is bad, I didn't remember doing this...
I'll split things

**Comment by neumino** [comment]
Sorry for that, fixed in 2.2.3
