### ISSUE TITLE
Query filters on a many to many relation

### ISSUE THREAD

**Issue by matthewcheok** [neumino/thinky#410]
I'm wondering how this might be best modelled: Suppose I have `User`s and `Post`s where each `User` can have many `Post`s and vice versa. We can do this via `hasAndBelongsToMany`. In one of the queries, I needed to get all the `Post`s belonging to a specific `User` and it appeared to be rather difficult to write this query.

Here's what I ended up with:
```
  r.table('Post_User')
  .filter(r.row('User_id').eq(some_user.id))
  .map((join) => {
    return r.table('Post').get(join('Post_id'))
    .merge(() => {
      return {
        users:
        r.table('Post_User')
        .getAll(join('Post_id'), {index: 'Post_id'})
        .map((join2) => r.table('User').get(join2('User_id')))
        .coerceTo("ARRAY"),
      }
    })
  })
```

The main problems with writing is 
1) We've alluded to the implementation details of the intersection table (there's no way we could have known the table name or the column names)
2) It seems we couldn't use `User` instead of `r.table('User')` or `Post` instead of `r.table('Post')`

Any ideas how this specific query can be written better?

**Comment by neumino** [comment]
I'm on my phone but something like

Users.get(someuserid).getJoin({posts:true})('posts')

Where you define the relation:
Users.hasAndBelongsTo(Post, 'posts', 'id', 'id')

**Comment by matthewcheok** [comment]
I'm getting the following: 

```
TypeError: _models.User.get(...).getJoin(...) is not a function
```

**Comment by neumino** [comment]
Users.get(someuserid).getJoin({posts:true}).getField('posts')

**Comment by matthewcheok** [comment]
```
Error: The results could not be converted to instances of `User`
```

**Comment by neumino** [comment]
You can either:
- remove getField
- use execute instead of run
- rewrite _model in the query to Post

**Comment by matthewcheok** [comment]
Perfect! `execute()` works for me... Is this a rethinkdb API or something specific to thinky?

**Comment by neumino** [comment]
Something specific to thinky.

**Comment by matthewcheok** [comment]
Seems if I rewrite the `_model`, I can no longer use `.count()`. Any workarounds?

**Comment by neumino** [comment]
What doesn't work?
