### ISSUE TITLE
Virtual fields on subdocuments undefined

### ISSUE THREAD

**Issue by matthewcheok** [neumino/thinky#411]
After running a query with `getJoin(...)` the virtual fields on the nested models are `undefined`. How do I fix this?

Edit: if it helps this is query I run last time via `.execute()`

**Comment by matthewcheok** [comment]
I fixed this by trying the other suggested option in #410 rewriting `_model` in the query to `Post` and using `.run()`. This breaks the chaining though because I have to store the query to rewrite `_model` - shouldn't we automatically rewrite `_model` when using `.getField()`?

**Comment by neumino** [comment]
You can create a static method that redefine `_model`. It cannot automatically rewrite `_model` as using `getField` doesn't always mean that you switch model.

**Comment by neumino** [comment]
(with defineStatic)

**Comment by matthewcheok** [comment]
What about allowing us to pass the model to be rewritten to as a second parameter to `getJoin()`?
