### ISSUE TITLE
retrieve posts by tags

### ISSUE THREAD

**Issue by almasakchabayev** [neumino/thinky#412]
I have a Post model that `hasAndBelongsToMany` Tag model.

I need to do the following:
1) Filter out posts if no tags match, i.e. I receive an array of tags, if a post has at least one tag from that array we keep it, else throw away.
2) Order by number of matched tags, i.e.if a post has two tags out of three matched, it should be before a post with 1 tag out of three matched
3) Secondary order by rank field, i.e. tags with same number of tags matched should be ordered by rank field of the post

I struggle with the second point mostly but I thought I would give the full explanation if it depends on where to join and how to group 
 
I have spent quite a the whole day on it and canont fin solution. I am also not proficient with rethinkdb Could you please guide me with this.

Thanks

**Comment by neumino** [comment]
This is the basic solution:
```
Post.getJoin({tags: true}).filter(function(post) {
  return post('tags').count().gt(0);
}).orderBy(function(post) {
  return [post('tags').count(), post('rank')]
})
```

The problem with this query is that it's slow. it requires a scan on the whole `Post` table.

You may want to maintain a local count of how many tags you have in each post. If this is the case, you could do:
```
Post.ensureIndex('tagsAndRank', function(post) {
  return [post('tagsCount'), post('rank')]
})

Post.between([1, r.minval], [r.maxval, r.maxval], {index: 'tagsAndRank'}).orderBy({index: 'tagsAndRank'}).getJoin({tags: true})
```

I'm closing the issue, but feel free to ask more questions here.
