### ISSUE TITLE
Joins and change feeds

### ISSUE THREAD

**Issue by matthewcheok** [neumino/thinky#413]
I'm getting the following error using `Model.getJoin(...).changes()`:

```
ReqlLogicError: Cannot call `changes` after a non-deterministic function
```

What's the right way to access the relation inside of a change feed?

**Comment by matthewcheok** [comment]
Related question - when I do `.saveAll()` on a model and the change feed gets triggered, the (many-to-many) relation has not yet been saved yet. What should I do if I need this information?

**Comment by neumino** [comment]
You cannot listen to the result of a joins at the moment. RethinkDB doesn't support a changefeed on this kind of query.

You could listen to a Model with `changes`, map `change('new_val')` or `change('old_val') and chain with a getJoin though.

I'm not sure what you mean by the second question since you can't open a changefeed on joined documents.

**Comment by matthewcheok** [comment]
Here's a more concrete example:

Suppose we have that many-to-many relation between `Post` and `User`, and we create a new `Post` calling `.saveAll({users: true})`

```
Post.changes()
.then((feed) => {
  feed.each((err, doc) => {
    if (err) {
      console.log(err)
    }

    if (doc.isSaved() === false) {
      console.log("The following document was deleted:");
    }
    else if (doc.getOldValue() == null) {
      console.log("A new document was inserted:")
    }
    else {
      console.log("A document was updated.")
    }
    console.log(doc)
    Post.get(doc.id).getJoin({users: true}).getField('users')
    .execute().then((result) => {
      console.log(result) // this will be empty, []
    })
  })
})
```

**Comment by neumino** [comment]
I'm not sure there's any secret way here. You have to listen on the table Users too.

**Comment by matthewcheok** [comment]
We can listen to `User.changes()` but there's no way to know if that's triggered because of a new `Post`. Also the because it's the intersection table that's updated, I'm not sure we will be triggered on a change feed for the `User` table.

**Comment by neumino** [comment]
Hum, maybe you could listen to the links between `User` and `Post`?
```
Posts._joins['users']['linkModel'].changes()
```

But beside that, there's no way to know if the User was just created or not (besides using a timestamp maybe). This is a limit in RethinkDB. Changefeeds on joins are not yet supported.

**Comment by opsb** [comment]
For anyone that lands here, the issue for joins on changefeeds is at https://github.com/rethinkdb/rethinkdb/issues/3997
