### ISSUE TITLE
Tips for Profiling

### ISSUE THREAD

**Issue by samkelleher** [neumino/thinky#415]
How might one go about profiling the query that gets built. My experience with ORMs is that they wrap the query layer in sugar, with a query being constructed underneath - How to access this query that actually gets sent to the server.  ElasticSearch for example, their SDKs end up producing a json document that gets sent as a string to inspect.

Does thinky do the same? Or would this be more of a property of neumino/rethinkdbdash

The plan is to take the constructed query and execute on the db using the profile tool.

**Comment by neumino** [comment]
You can access the query sent to the server via the property `_query` (on a thinky query).
```
var query = Users.getAll('foo');
console.log(query._query.toString())
```

**Comment by neumino** [comment]
Closing the issue, but feel free to ask more questions.

**Comment by samkelleher** [comment]
@neumino You genius! Thanks for the pro tip! 👏 Love thinky. Thanks for the quick response. 🏃 I'm gonna start examining my queries. 🔎

**Comment by samkelleher** [comment]
I noted this on RethinkDBs issue tracker that the default database is `test` in their data explorer. So once you have captured the query it doesn't run as is as thinky has set the default database in its connection.  In partcular, I see a lot of `r.table` calls in my queries, where to run in the data explorer, they need to be prefixed with `r.database()` or else it tried to run against the test database.
