### ISSUE TITLE
Inserting a lot of documents in bulk slow

### ISSUE THREAD

**Issue by ablankenship10** [neumino/thinky#418]
I have a benchmark app trying to compare mongodb using mongoose vs rethink using thinky. Currently for very similar operations I am getting over double the time in thinky and some weird behavior during saves. Rethink is inherently a bit slower than mongo but I don't think it should be by this much.

I am running 100k inserts of test data, 50k of one model, and another 50k of a model that belongs to the first one after it is saved. With mongo I can see these documents going in as the loop goes, but with thinky it seems like there might be some type of query caching going on before they are actually sent to the server. My test with thinky will go through the for loop 50k times, sit for about 30 seconds, then I finally start to see documents being saved in the rethink web UI as it writes about 1k per second (Is this limited by my max connections? I tried 10k connections and got `Full error:\n{\"code\":\"EMFILE\",\"errno\":\"EMFILE\",\"syscall\":\"connect\",\"address\":\"192.168.99.100\",\"port\":32798}`. How many connections can I have per server?)

This is using a local docker image for rethink.

Models:
```
//First model, created with random data
thinky.createModel("Table1", {
      id: type.string(),
      num: type.number().required(),
      firstName: type.string().default(smallData),
      lastName: type.string().default(largeData),
      addrLine1: type.string().default(largeData),
      addrLine2: type.string().default(largeData),
      addrCity: type.string().default(smallData),
      addrState: type.string().default(smallData),
      addrZip: type.string().default(smallData)
});

//Second model, created with random data + id of document of previous model
thinky.createModel("Table2", {
      id: type.string(),
      num: type.number().required(),
      table1Id: type.string().required(),
      firstName: type.string().default(smallData),
      lastName: type.string().default(largeData),
      addrLine1: type.string().default(largeData),
      addrLine2: type.string().default(largeData),
      addrCity: type.string().default(smallData),
      addrState: type.string().default(smallData),
      addrZip: type.string().default(smallData)
});
```

Test
```
Test.prototype.setup = function (callback) {
    var self   = this;
    self.db    = Thinky(self.settings);
    self.Table1 = require(__dirname + '/../../models/rethink/table1')(self.db);
    self.Table2 = require(__dirname + '/../../models/rethink/table2')(self.db);
    self.Table2.belongsTo(self.Table1, "table1", "table1Id", "id");
    callback();
};

Test.prototype.run = function (callback) {
    var self          = this;
    self.doneCallback = callback;
    var Table1        = self.Table1;
    var Table2        = self.Table2;
    for (var i = 0; i < NUM_RUNS; i++) {
      (function (num) {
        var doc1 = new Table1({num: num});
        doc1.save(function (err, result) {
          if (err) {
            callback('Error doc1');
            return;
          }
          var doc2 = new Table2({num: num, table1Id: result.id});
          doc2.save(function (err, result) {
            if (err) {
              callback('Error doc2');
              return;
            }
            self.count(); // _.after function called after NUM_RUNS times to call doneCallback
          });
        });
      })(i);
    }
};
```

Results: Mongo 60 seconds, Rethink 142 seconds

So is there some sort of query cache slowing down actual saves, am I iterating too fast? Is there a better way to go about this (not using the bulk insert method)?

**Comment by neumino** [comment]
Thinky uses rethinkdbdash under the hood and run one query per connection. So this is probably why you see things happening in bulk-ish. There's no caching involved, we just throttle queries when we don't have available connections.

The EMFILE is because you reach the maximum file open in your system. You can increase that if you want 10k connection. I believe by default it's about 3K connections on Debian.

Also you are probably comparing apples and oranges, except if you forced mongo to commit to disk before returning and if you never run more queries than you have queries.
