### ISSUE TITLE
Disable DocumentNotFoundError?

### ISSUE THREAD

**Issue by contra** [neumino/thinky#424]
Is there any way to turn this off? This behavior is not aligned with how most other ORMs (ie mongoose) operate, and it requires significantly more code just to check for a missing document.

Not sure why this seemed like a good idea to you but it adds a ton of boilerplate and is difficult to work around: Requiring in the db object to get Errors.DocumentNotFoundError, catching the error, then doing an instanceof check on the resulting error to see if it's the right kind.

IMO this should be disabled by default, but a backwards-compatible approach would be to make an option and have it enabled by default.

**Comment by neumino** [comment]
You can use `_get` instead of `get`.
The reason of this error is that you can't chain most of the things you need after a `get` that returns `null`.
Other databases like Mongo typically don't let you do joins, so it's ok for them to return `null`.

**Comment by thomasmodeneis** [comment]
related to https://github.com/neumino/thinky/issues/182

The error: Unhandled rejection DocumentNotFoundError: The query did not find a document and returned null in:

I was really surprised by this behaviour, Its a little bit inconvenient, but @neumino point over why is there, is fair.
 
Would be possible to document this on the docs ? I encountered this issue and was surprised that google search got me only github issues. 

Cheers.
