### ISSUE TITLE
using .run with a callback should capture errors

### ISSUE THREAD

**Issue by contra** [neumino/thinky#428]
`User.get(id).run(cb)` should capture errors, since you are handling them in the callback. It's super funky to support callbacks, but require people to use promises if they want to handle errors

**Comment by ondreian** [comment]
Can you share the code to replicate whatever error you are seeing?  

Is your function accepting Node.js style callbacks `function ( err, result){ /* stuff */ }`? 

It uses `Promise.prototype.nodeify` from the `bluebird` module to handle Node.js style callbacks under the hood, and I have several `async.parallel` queries that depend on callbacks instead of promises.

**Comment by contra** [comment]
@ondreian My specific case is this

```js
User.get(id).run(cb)
```

If the document doesn't exist the promise throws a DocumentNotFoundError as well as calling the callback with the error. Expected behavior is that it only calls the callback and doesn't throw from the promise.

**Comment by ondreian** [comment]
I cannot recreate getting this to throw a Promise error when passing a callback:

```js
var thinky = require('thinky')();
var type   = thinky.type;

// Create a model - the table is automatically created
var User = thinky.createModel("User", {
  name: String
});

User.get('doesntexist').run( function (err, res) {
  console.log(`Callback Err: ${err.message}`);
  console.log(`Result: ${res}`);
  process.exit(0);
});

```
Result:

```log
benjamin@benjamin-linux ~/dev/thinky-test
  % node cb.js                                                                                                                                                          !129
Creating a pool connected to localhost:28015
Callback Err: The query did not find a document and returned null in:
r.table("User").get("doesntexist").default(r.error("The query did not find a document and returned null."))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

Result: undefined

```

Are you using a promise & a callback?

**Comment by neumino** [comment]
Same here, thinky doesn't throw but pass the error to the callback. Something's probably wrong with your code.

Please provide a full script that throws an error if you need help.
