### ISSUE TITLE
What Should Be Passed Into New Errors?

### ISSUE THREAD

**Issue by primitive-type** [neumino/thinky#431]
Before version 2.2.4, the following worked perfectly for me:

```javascript
throw new Errors.ValidationError({
    message: 'Here is a technical custom error message I used in my API',
    displayMessage: 'Here is a user facing message for display to end users'
});
```
At the API level, I catch all errors and based on their type decide which type of HTTP response to send back, along with the above messages. That's where I extract the `message` and `displayMessage` fields from the above error object (currently still working after I reverted back to thinky 2.2.3).

After the new changes, how should I update the above code to work in a similar manner? Now, instead of having the `message` field equal whatever I pass in, it is just `[object Object]`. Am I doing something wrong?

**Comment by neumino** [comment]
Sorry for the late answer, I was out of town the past few days.

I guess what you want is:
```
var Errors = thinky.Errors;
var error = new Errors.ValidationError('Here is a technical custom error message I used in my API');
error.displayMessage = 'Here is a user facing message for display to end users';
```

The syntax was always `Errors.ValidationError(<message>)`. There was no support for adding other fields. You could also just write a sub class of ValidationError if you need multiple fields (and don't want to monkey patch them)
