### ISSUE TITLE
Check if username/email is already used

### ISSUE THREAD

**Issue by christiansakai** [neumino/thinky#434]
What is the preferred workflow to check whether a username/email is already used?

**Comment by neumino** [comment]
Hum, RethinkDB provide uniqueness only via primary key, so I would go with that.
If you create a secondary index, you have to check that the value is not there, and then insert it if it's not. There are some race condition around that though, so it's not 100% safe.

You have to create your own lock (or use another table I guess for that)

**Comment by DiknT** [comment]
Anything wrong with this approach?

```
User.filter({email: email}).nth(0).default(null).run()
 .then( function (user) {
  // user with this email already exists
 })
 .catch(Errors.DocumentNotFound, function (err) {
  // no user with that email, create one..
}
```

**Comment by christiansakai** [comment]
@DiknT ah thats what I am looking for.  What if I also want to add a username on that?

**Comment by christiansakai** [comment]
I tried to put the code above in `pre('save'` and it seems like a bad approach, because once the user is saved the first time, and then we do an update, the `pre('save'` will run and will say that the email is not available

```
User.pre('save', function(next) {                                                                                                                                              
  this.getModel()                                                                                                                                                              
    .filter({ email: this.email })      
    .then(user => {        
        if (user.length > 0) {                         
           return next(new Error('This email is not available'));    
        } 
        next();                                                                                                                                                                  
     });                                                                                                                                                                      }); 
```

Is there a way to avoid this if we strictly want to put the code in the hook

**Comment by DiknT** [comment]
you should put it in a controller action which is responsible to create/signup new users. This way you only check once on creation and not on every update which makes no sense.

**Comment by DiknT** [comment]
but if you really want to, you could also use pre-save to check if current user already has an id saved, and if not check if the email is still available.

**Comment by christiansakai** [comment]
@DiknT 

Ah that makes sense. I realized that id is only given if the user has been saved previously.  Sorry, I came from MongoDB/MongooseJS world, and the approach that people usually use is to check it in `pre('save'` with a statement `this.isNew` to determine whether a document has been saved previously before.

Thanks, I'll close the issue.
