### ISSUE TITLE
Document.addRelation/removeRelation is documented but is not defined

### ISSUE THREAD

**Issue by simonratner** [neumino/thinky#439]
Documented here:
    http://thinky.io/documentation/api/document/#addrelation
    http://thinky.io/documentation/api/document/#removerelation

Either the implementation was removed but docs never updated, or it was planned but never implemented. Easy enough to patch in:
```js
Document.prototype.addRelation = function (field, joinedDoc) {
  let model = this.getModel()
  let pk = this[model._pk]
  return model.get(pk).addRelation(field, joinedDoc)
}

Document.prototype.removeRelation = function (field, joinedDoc) {
  let model = this.getModel()
  let pk = this[model._pk]
  return model.get(pk).removeRelation(field, joinedDoc)
}
```

**Comment by neumino** [comment]
Ah thanks, I think I just forgot to actually implement it, but like you said it's pretty straightforward.
