### ISSUE TITLE
Validation not running on save()

### ISSUE THREAD

**Issue by disbelief** [neumino/thinky#440]
I'm having a bit of trouble validating my models. The docs aren't super clear about this, but I'm assuming that the `validate` function is called automatically on a model when `save` is called.

However I've noticed that this isn't the case for me. Here is some sample code:

```javascript
import createThinky from 'thinky';

const thinky = createThinky();
const type = thinky.type;

const validateName = function (name) {
  console.log('hi from validateName');
  if (name.match(/[^a-z]/i)) {
    return false;
  }
  return true;
};

const User = thinky.createModel('users', {
  id: type.string(),
  name: type.string().validator(validateName)
});

const user = new User({
  name: 'inval1d n4m3'
});

user
.save()
.then(function(user) {
  console.log('user saved!');
})
.catch(function(error) {
  console.error('user save failed!');
});
```

Running the above, I would expect the save to fail because the name doesn't pass the `validateName` function. However in the console I only see `user saved!`. It appears that the validator function isn't running at all.

Am I doing something wrong, or is this a bug?

**Comment by neumino** [comment]
Your script works for me:
```
Creating a pool connected to localhost:28015
hi from validateName
{ [ValidationError: Validator for the field [name] returned `false`.]
  name: 'ValidationError',
  message: 'Validator for the field [name] returned `false`.' }
user save failed!
```

```
var thinky = require('./lib/thinky.js')();
var type = thinky.type;
var r = thinky.r;
var Errors = thinky.Errors;
var assert = require('assert');

const validateName = function (name) {
  console.log('hi from validateName');
  if (name.match(/[^a-z]/i)) {
    return false;
  }
  return true;
};

const User = thinky.createModel('users'+Math.random(), {
  id: type.string(),
  name: type.string().validator(validateName)
});

const user = new User({
  name: 'inval1d n4m3'
});

user
.save()
.then(function(user) {
  console.log('user saved!');
})
.catch(function(error) {
	console.log(error)
  console.error('user save failed!');
});

```

**Comment by disbelief** [comment]
hmm ok perhaps I've left something crucial out of my example code from what I'm doing in real life.

**Comment by disbelief** [comment]
Glad to hear that `validate` *should* be called by `save` at any rate!

**Comment by disbelief** [comment]
Yep, it was a problem on my end. I was importing the validators from an external file, and I had forgotten to actually save that external file with my latest validators *blush* 

Thanks so much for the quick reply!
