### ISSUE TITLE
logging/error handling on connection?

### ISSUE THREAD

**Issue by contra** [neumino/thinky#441]
There doesn't seem to be any way to catch errors, tell if a connection has been established, or do a number of things that seem like a really basic component of a DB access tool.

Problem: I connect to a database, no way to know if it worked.
Problem 2: I connect to a database, it fails to connect - errors ([pictured here](https://cloudup.com/cjNBD7-AN96) spew into my console)
Problem 3: Database goes offline while the application is up, no way to know.

**Comment by contra** [comment]
Here's what I have so far to monkey-patch common sense ORM behavior in:

```js
const db = thinky(config.rethink)

db.r.getPoolMaster()._flushErrors = () => {}

db.r.getPoolMaster().on('healthy', (healthy) => {
  if (healthy) {
    debug('RethinkDB connected!')
  } else {
    debug(chalk.red('RethinkDB failed to connect!'))
  }
})
```

Still has a number of issues that would need to actually be fixed in thinky

**Comment by neumino** [comment]
This is by design. With rethinkdbdash you never have to worry about connections. You don't have to handle disconnections, the driver will do it for you. The pools automatically recover if the server are back up.

Typically calling `rethinkdbdash()` doesn't return a promise but an object and you can immediately run query before any connection is actually established. Queries will be queued until the first connection is open.

**Comment by contra** [comment]
I understand that it *might* recover, but I still need to know when it happens. Other cases where it doesn't recover also happen (wrong connection string, for example). Are you really saying that hiding errors and forcing `console.log` is by design?

**Comment by neumino** [comment]
So what thinky does, is just reproducing the behavior of rethinkdbdash. The idea behind this driver was for the user to never deal with connections because at the end of the day, the only thing we care about is to execute a query. So you see errors when you run a query. If no connection is available and rethinkdbdash knows that it failed to open a connection, it will immediately reject the query.

You can prevent the driver from writing to stderr by passing `silent: true` and you can redirect the logs to anything you want with `thinky.r.getPoolMaster().on('log', <fn>)`
If you want to know if things are working, you can just listen to the `heathy` event.

**Comment by contra** [comment]
@neumino 

The healthy event isn't fired on first connect, only subsequent reconnects. The only way to time how long it took for your db to connect initially is to run a query listing the tables on start.

**Comment by neumino** [comment]
@contra -- that's because the pool is healthy at T=0. A non healthy pool is a pool that will immediately reject a query without trying to open a new connection.

**Comment by contra** [comment]
@neumino So, given all of this discussion - can you answer how users can log/benchmark/whatever on initial connect?

Not documenting it is understandable, but to actively prevent users from accessing internals seems extremely counterproductive for people making plugins and extensions.

**Comment by neumino** [comment]
Documentation is here:
https://github.com/neumino/rethinkdbdash#advanced-details-about-the-pool

This is probably what you are looking for:
```
var connected = false;
var thinky = require('thinky')()
thinky.r.getPoolMaster().on('available-size', function(size) {
  if (connected === false && size === 1) 
    // do stuff
  }
})
```

This i

**Comment by contra** [comment]
For anybody who cares about this and stumbles onto it in the future:

```js
import thinky from 'thinky'
import chalk from 'chalk'
import _debug from 'debug'
const debug = _debug('app:db:rethink')

const db = thinky(config.rethink)

let connected = false
db.r.getPoolMaster().on('available-size', (size) => {
  if (connected) return
  debug(`RethinkDB connected (${size})`)
  connected = true
})
db.r.getPoolMaster()._flushErrors = () => {}

db.r.getPoolMaster().on('healthy', (healthy) => {
  if (healthy) {
    debug('RethinkDB reconnected')
  } else {
    debug(chalk.red('RethinkDB failed to connect'))
  }
})
```

**Comment by hiddentao** [comment]
@contra Thanks so much for this! I totally agree with you that not having a way to access this information properly seems like a bad design decision.

**Comment by hwestbrook** [comment]
Agree with @contra on this too. I had an issue last night with my application where the server lost its ability to do DNS resolution. Thinky (and rethinkdbdash) does not handle errors like that well, so I ended up with a bunch of unhandled errors. 

Would be better for me to be able to handle and parse errors easily.

**Comment by neumino** [comment]
@hwestbrook -- You are welcome to describe a better API and send a pull request.

**Comment by contra** [comment]
@neumino Should be the same as every other db driver: If an error happens, emit an error event from the db.

**Comment by neumino** [comment]
Hum, I'm not sure if what you call `db` is a connection or the pools master.

I would like to see a whole use case behind whatever API you are trying to come up with.
Do you plan to kill your process if RethinkDB is not up? How do you expect to recover?

**Comment by hwestbrook** [comment]
For what I am using Thinky for, @contra's solution works fine. It allows me to catch errors and then to route those errors to the right place so I can recover from them. 

My use case is simple: I have an application that uses thinky to communicate with rethinkdb. Currently, if something happens to that connection (i.e. networking, database down, etc.) my application has no way to know what the error is, when it may recover, the seriousness of the error, etc. If my application did know such things, it could log them out to another service that would escalate the issue to me. 

Maybe for cases like ours, putting @contra's solution in the documentation of the website would be enough to satisfy people who want to catch errors. I only found this solution after a good deal of digging.

**Comment by neumino** [comment]
@hwestbrook -- You can redirect errors messages 
https://github.com/neumino/rethinkdbdash#connection-pool

Also the pool automatically recover. The only case where the pool cannot recover with discovery is when these conditions are met
- The cluster has shifted from all the seeding machines
- The cluster is completely down at some point
- The cluster restarted on completely different machines
- The servers were specified with IP addresses

But then, you have more an infrastructure issue than something else. If you are using a Kubernetes service (or anything similar), the connections will always recover.

If you want to get paged when things go down, the `heatlhy` event is the only thing you should monitor. If the pools master becomes not healthy at some point, it means that rethinkdbdash will immediately reject any queries you are trying to execute.

**Comment by hwestbrook** [comment]
Thanks @neumino -- Will look into your suggestions. 

The issue I experienced is not in your list, but is an infrastructure problem: https://twitter.com/DOStatus/status/710895876164554752. Basically, DO servers stopped doing DNS resolution which meant my application could not get to my database.

**Comment by contra** [comment]
@neumino My problem is an invalid db string, you have no idea there is a problem. A DB driver shouldn't assume everything will be okay when there are a handful of extremely common cases where there is no possibility of recovery and you should definitely not hide that. This is the only DB driver I've ever seen purposely obscure useful information.
