### ISSUE TITLE
What is a foreign key?

### ISSUE THREAD

**Issue by dtoubelis** [neumino/thinky#445]
I often encounter reference in the the documentation to _foreign key_ that is stored with the model. As far as I know rethinkdb have no concept of foreign keys, so it must be "thinky" thing. Is there any place in the documentation that explains what those foreign keys are, how they are stored and what it their life cycle, i.e. when they are created, updated, deleted? Also, what are their memory usage characteristics?

I'm working with one-to-one relationship in my project and I think it is a messy use case since it is essentially circular reference and thinky deliberately prevents them from happening. I think the _foreign key_ concept is the missing piece of information to solving these problems, so some documentation would go a long way.

**Comment by neumino** [comment]
RethinkDB doesn't have the concept of foreign key like a traditional SQL database. We call a field a foreign key if it's used as a foreign key in a SQL database.

There's a bit more information on the relations page:
http://thinky.io/documentation/relations/

The key is set when you save a relation, that is to say when you save a document and its joined document or if you use `addRelation`.

I'm not sure what the problem is with your one-to-one relationship, can you elaborate a bit?

**Comment by dtoubelis** [comment]
The problem I'm facing is as follows:

```javascript
var User = thinky.createModel("User", {
    email: type.string(),
    fullname: type.string(),
    password: type.string(),
    attr: {
        avatar: type.boolean()
    }
});

var Email = thinky.createModel("Email", {
    email: type.string().lowercase().email(),
    userId: type.string()
}, {
    pk: "email"
});

User.hasOne(Email, "_email", "email", "userId");
Email.belongsTo(User, "_user", "userId", "id");

var _testEmail = [
    "user1@example.com",
    "user2@example.com",
    "user3@example.com",
    "user4@example.com"
];

var _testId = [
    "30000000-0000-1000-8000-000000000001",
    "30000000-0000-1000-8000-000000000002",
    "30000000-0000-1000-8000-000000000003",
    "30000000-0000-1000-8000-000000000004"
];

function sample_0 () {

    var newEmail = new Email({
        email: _testEmail[0]
    });

    var newUser = new User({
        id: _testId[0],
        fullname: "Bob Smith",
        attr: {
            avatar: false
        }
    });

    newEmail._user = newUser;

    return newEmail.saveAll({_user: true}).then(function(savedEmail) {
        console.log("--- sample_0 ---");
        console.log(savedEmail);

        // works okay

    });
}

function sample_1 () {

    var newEmail = new Email({
        email: _testEmail[1]
    });

    var newUser = new User({
        id: _testId[1],
        fullname: "Bob Smith",
        attr: {
            avatar: false
        }
    });

    newUser._email = newEmail;

    return newUser.saveAll({_email: true}).then(function(savedUser) {
        console.log("--- sample_1 ---");
        console.log(savedUser);

        // problems:
        // - savedUser.email - not set
        // - savedUser._email.userID - is not set

    });
}

function sample_2() {

    // this works
    return Email.get(_testEmail[0]).getJoin({_user: true}).then(function(emailModel) {
        console.log("--- sample_2 ---");
        console.log(emailModel);

        // works okay
        
    });
}

function sample_3() {

    // this doesn't
    return User.get(_testId[0]).getJoin({_email: true}).then(function(userModel) {
        console.log("--- sample_3 ---");
        console.log(userModel);
        
        // problems:
        // - userModel._email is not present
    });
}
```

So, it seems that `one-to-one` relationship is not symmetrical and only works from `belongsTo` side but I need to use it both ways.

**Comment by neumino** [comment]
You want this:
```
User.hasOne(Email, "_email", "id", "userId");
Email.belongsTo(User, "_user", "userId", "id");
```

Or this
```
User.hasOne(Email, "_email", "enail", "userId");
Email.belongsTo(User, "_user", "userId", "enail");
```

This is because you can't use a single field in two different relation

If you want your script to exit, close the connections with `thinky.r.getPoolMaster().drain()`

**Comment by dtoubelis** [comment]
Thanks @neumino. It took me awhile to understand why it works this way but I think I grok it now. I think the main confusion was that examples provided in the documentation have filed`"id"` on both ends and it is not clear which one is used when defining relationship. It would be nice if you could make the documentation more clear. Anyhow, thanks for all your help and the awesome product :-)

**Comment by neumino** [comment]
Thanks, I'll try to update the doc to make it a bit more clear.
