### ISSUE TITLE
Conflict over connection pool with sequelize

### ISSUE THREAD

**Issue by dtoubelis** [neumino/thinky#449]
I'm migrating our database from postgres/sequelize to rethinkdb/thinky and I have models from both of them in the application at the same time, however it seems they have conflict over connection pool. For instance, I have rethinkdb configured with `localhost:28015` and postgres with `localhost:5432`. When I instantiate `thinky` it hijacks connection pool from sequelize and  forcing all requests from sequelize be directed to `localhost:28015`. I was also experimenting with order in which I import sequelize /thinky modules but it seems have no effect - thinky always wins.

Also, I was thinking about disabling connection pool in thinky as a temporary workaround (inspired by `rethinkdbdash`), but I could not figure if it is even possible .

**Comment by neumino** [comment]
Passing pool:false to thinky options should do the trick.

**Comment by dtoubelis** [comment]
Disabling pool causes an exception, so I guess it is no good as a workaround.

**Comment by dtoubelis** [comment]
Nevermind, this was my fault after all.
