### ISSUE TITLE
Saving keys of type Object

### ISSUE THREAD

**Issue by ondreian** [neumino/thinky#450]
There appears to be something odd going on with saving keys of `type.object()` as they do not update when set to an empty object after having previously been set.

Here is my schema
```nodejs
// Create a model - the table is automatically created
var Thing = thinky.createModel("Test_Things", {
    facets: type.object().default(function () { return {} })
}); 
```
and the remainder of the code to recreate this bug (as well as my logs) can be found [in this repo](https://github.com/ondreian/thinky-bug-report) for easy replication.

I haven't started to dig into what might be going on in `thinky` yet, I just wanted to document it first and see if perhaps there was something I was misunderstanding about how this works.

**Comment by neumino** [comment]
This is working as intended. If you want to delete a field you need `replace`.

**Comment by neumino** [comment]
Or use `r.literal`

**Comment by neumino** [comment]
To be more precise, if you want to remove facets, you need
```
savedThing.facets = r.literal({})
```

**Comment by ondreian** [comment]
I see, thanks for the information. I somehow overlooked `r.literal()` in the documentation.
