### ISSUE TITLE
When to use r.table() and when to use Model

### ISSUE THREAD

**Issue by tuananhtd** [neumino/thinky#452]
Hi guys, it's kind of a newbie question. I recently have to use more complex query like map(), between(). and it often produce some weird errors when I use it with the Thinky Model. eg. the most recent error I got when use `Post.filter({}).map((post) => post('id'))` I got an error like `Cannot build a new instance of `Post` without an object` but when I switched it to r.table('Post') it works.
I have checked the Post table and the only item in there has the correct schema. (I inserted it by post.save() anw).
Hope someone could shed some light on this! Thanks!

**Comment by neumino** [comment]
If you call `Model.<function>.run()`, `run` will know that the results should be instances of `Model`.

If you nest `Model`, you need to call `r.table(Model.getTableName())`.

So
```
Model.map(function(doc) {
  return r.table(Model.getTableName()).get(doc("id"))
})
```
