### ISSUE TITLE
allowExtra and removeExtra overwrite model joins

### ISSUE THREAD

**Issue by rosskukulinski** [neumino/thinky#455]
I have two models:

```
var ThingA = thinky.createModel('ThingA', type.object().schema({
  id: type.string()
}).allowExtra(false));

var ThingB = thinky.createModel('ThingB', type.object().schema({
  id: type.string(),
  thingAid: type.string().required()
}).allowExtra(false));

ThingA.hasMany(ThingB, 'stuff', 'id', 'thingAid');
```

If I try to do ThingA.get('someid').getJoin().run(), then I get:
```Extra field `stuff` not allowed```

Similarly, if I use removeExtra() instead of allowExtra(false), then the field 'stuff' appears to be removed from the join.

**Comment by neumino** [comment]
Hum, I can reproduce that but I looked a bit, and I don't remember how the code was handling this (or if it has been always broken?)

**Comment by rosskukulinski** [comment]
I _think_ the issue has to do with the fact that sub-Types within the Object schema don't get passes the whole Model (which includes references to virtual fields and/or Joins).  I started to poke in the code when I found the issue, but then got distracted.
