### ISSUE TITLE
not able to access custom define method

### ISSUE THREAD

**Issue by gmchaturvedi1** [neumino/thinky#466]
i am not able to access custom define method .kindly find below the code and suggest me : 
my usermodel file 

import thinky  from '../../util/thinky.js';
const type = thinky.type;
import bcrypt from 'bcrypt-nodejs';

const User = thinky.createModel("User", {
    email: type.string(),
    password: type.string()
});

//Hashing Password for security
User.pre('save',function(next){
  var user=this;
  console.log(user)
  bcrypt.genSalt(10,(err,salt)=>{
    if (err) return next(err);
    bcrypt.hash(user.password,salt,null,(err,hash)=>{
      if(err) return next(err);
      user.password=hash;
      next();
    })
  })
})
User.define("comparePassword",function(candidatePassword,callback){
  bcrypt.compare(candidatePassword,this.password,(err,isMatch)=>{
    if(err) return callback(err);
    return callback(null,isMatch)
  })
})

export default  User;

my passport strategy file 

import passport from 'passport';
import User from '../src/models/userModel.js';
import config from '../config.js';
import{Strategy,ExtractJwt} from 'passport-jwt';
import LocalStrategy from 'passport-local';

//Local Strategy
const localOptions={usernameField:'email'};
const localLogin= new LocalStrategy(localOptions,function(email,password,done){
  User.filter({email:email}).run().then((user)=>{
    if(!user) return done(null,false);
    
    user.comparePassword(password,(isMatch)=>{
      if(!isMatch) return done(null,false);
      return done(null,user)
      })

  })

})

//Setup option for JWT Strategy
const jwtOption = {
  jwtFromRequest: ExtractJwt.fromHeader('authorization'),
  secretOrKey: config.secret
};

//create jwt Strategy
const jwtLogin=new Strategy(jwtOption,(payload,done)=>{

  //see if User ID in payload exists in our database
  //if it does ,call 'done with that other'
  //otherwise,call done without a user object
  User.get(payload.sub).run().then((user)=>{

    if(user){
      done(null,user)
    }
    else{
      done(null,false)
    }

  })
})

//Tell the passport to use Strategy
passport.use(jwtLogin);
passport.use(localLogin);

error is coiming
Unhandled rejection TypeError: user.gm is not a function
    at D:/dev_dir/my_app/server/services/passport.js:12:10
    at tryCatcher (D:\dev_dir\my_app\server\node_modules\thinky\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\dev_dir\my_app\server\node_modules\thinky\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (D:\dev_dir\my_app\server\node_modules\thinky\node_modules\bluebird\js\main\promise.js:581:18)
    at Async._drainQueue (D:\dev_dir\my_app\server\node_modules\thinky\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\dev_dir\my_app\server\node_modules\thinky\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\dev_dir\my_app\server\node_modules\thinky\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by neumino** [comment]
Are you sure it's the call to `comparePassword` that's failing?

**Comment by gmchaturvedi1** [comment]
Yes

**Comment by neumino** [comment]
That's because `user` is an array and not a `User`.
