### ISSUE TITLE
getNearest does not return data like other queries

### ISSUE THREAD

**Issue by joeframbach** [neumino/thinky#472]
I have a model

```
var Event = thinky.createModel('Event', {
  name: type.string(),
  point: type.point()
}
Event.ensureIndex('point', {geo: true})
```

It has several hundred documents with names and points.

I run this thinky command:

```
Event.filter(() => Math.random() < 0.5).run((err, events) => {
  console.log(events.map(event => event.name))
})
```

and this is fine.

I run this command:

```
var here = r.point(-122.422876, 37.777128)
Event.getNearest(here, {index: 'point', unit: 'mi', maxDist: 1000}).run((err, events) => {
console.log(events.map(event => event.name))
})
```

and it fails because in that case, `event` looks like this:

```
model {
    dist: 958.2152275561461,
    doc: 
     { 
       name: 'foo',
       point: [Object]
     }
   }
```

It looks like rethinkdb returns the document wrapped in another object, instead of returning my array of results normally.

If this is normal rethinkdb behavior, then thinky should "unwrap" the results from getNearest for me.

**Comment by neumino** [comment]
This should work:
```
Event.getNearest(here, {index: 'point', unit: 'mi', maxDist: 1000}).getField('doc')
```

The reason why it's failing is because `run` expect a document to be returned. If you don't want to parse the result, you can use `execute`.

**Comment by joeframbach** [comment]
Yes, this does work. Thank you. Is there a reason that `getNearest` does not return documents?

**Comment by neumino** [comment]
The commands provided by thinky behaves exactly the same way as the RethinkDB's ones. In this case, `getNearest` returns the distance too
http://rethinkdb.com/api/javascript/get_nearest
