### ISSUE TITLE
r.distance is unefined

### ISSUE THREAD

**Issue by IdanAizikNissim** [neumino/thinky#475]
hi,

Im trying to use r.distance exactly as defined in ReQL, [http://www.rethinkdb.com/api/javascript/distance/](url)
but is undefined in thinky.r.

var policeLocation = r.point(34.8209128,32.0863583);
 
reQL:
Does work in Data Explorer but not through thinky
r.db('temp').table('users').map(function (user) {
  var userLocation = r.point(user('longitude'), user('latitude'));
  var distance = r.distance(policeLocation, userLocation, {unit: 'm'});
  return user.merge({distance: distance});
})

edit:
opened [https://github.com/neumino/rethinkdbdash/blob/master/lib/term.js#L2535](url)
in Term there is an implication: Term.prototype.distance 
but in index.js of rethinkdbdash there is no r.prototype.distance.
this seem to be the problem

**Comment by neumino** [comment]
Thanks for the report. I opened https://github.com/neumino/rethinkdbdash/issues/240 to track that (it's an issue in the driver, not in thinky)
