### ISSUE TITLE
Synchronization issue with connection pool

### ISSUE THREAD

**Issue by dtoubelis** [neumino/thinky#479]
I have few scripts that I need to execute in batch mode and I noticed that operations that expected to be synchronous are not. Here an example:

```javascript
var Promise = require('bluebird');
var app = require('../server/config/app.js');
var thinky = require("../server/services/models");
var r = thinky.r;

// we need this delay to make sure tables have finished being created
// by require("models") above
return Promise.delay(1000).then(function() {

    return r.db("rethinkdb").table("server_status").count().run().then(function(serverCount) {

        return r.db(app.rethinkdb.db).reconfigure({
            shards: serverCount,
            replicas: 3
        }).run().then(function () {

            return r.db("rethinkdb").table("table_status").filter({db: app.rethinkdb.db}).run().then(function (result) {

                return Promise.map(result, function (table) {

                    return r.db(table.db).table(table.name).reconfigure({
                        shards: serverCount,
                        replicas: 3
                    }).run().then(function () {
                        console.log("Resynchronized table '" + table.name + "'.");
                    });
                });
            });
        });
    });

}).finally(function() {

    // we need this delay to make sure all operations are finished
    return Promise.delay(1000).then(function() {
        return r.getPoolMaster().drain();
    });
});
```

As you noticed there are 2 delays in this code and this code will not work as expected without them. This is my analysis of the problem:

--1. If database does not exists and once this statement:
``` javascript
var thinky = require("../server/services/models");
```
is completed tables are not created immediately even though `require` supposed to be synchronous. My guess is that they are synchronously inserted into some sort of queue but taken from queue and executed with connection pool asynchronously and the first delay is in place to compensate for this.

--2. There is also delay before draining connection pool and it supports my first theory. If I call `r.getPoolMaster().drain()` immediately, the pool getting drained right away. This means that if there are any outstanding tasks in the queue they are unable to obtain connection from the pool and  throw an exception. I observe this happening 9 times out of 10 and that is why the second delay.

This problem is less noticeable with interactive apps but it exists nevertheless and it may cause random errors that are impossible explain to reproduce. So, I think it is a bug and it is a high priority.

**Comment by neumino** [comment]
Thinky will fire queries under the hood to create the database/table if they are missing. The only way to prevent that is to pass `init: false` when you call `thinky.createModel`.

While thinky creates the table or make sure they exist, queries are queued.

In your case ,you could do something like:
```
var thinky = require(...)()
thinky.dbReady().then(function() {
  thinky.r.db('...').reconfigure(...)
})
```
If you want to know when a table is available, you can listen to the event `ready` on a table.

I'm not sure what your question in 2. is about. If you close all the connections, then yes you can't run a query.

**Comment by dtoubelis** [comment]
Okay, I think your answer covers the first case. This is actually exactly what I was hoping for :-)

Let me try to explain the second case:

- I do batch insert of 100 records into the database and I call ` r.getPoolMaster().drain();`
- this triggers ar idle connections to be closed and active connections to be closed once they are done.
- this also prevent new connections from being created in the pool which is expected behaviour.
- the problem is that at that time there are still few inserts in the queue that will not be able to obtain connection from the pool. So, last few inserts will fail if I do not add the artificial delay before draining the pool.

**Comment by neumino** [comment]
Well, you just have to call `r.getPoolMaster().drain()` after you are done with your inserts.

```
r.table('foo').insert([...]).then(function(result) {
  // do something with result
  r.getPoolMaster().drain();
})
```

**Comment by dtoubelis** [comment]
This is pretty much what I do but I do whole bunch of inserts concurrently and then drain connections in `finally()`. Here is snippet of my code:

```javascript
var Promise = require('bluebird');
var ServiceError = require('../services/service-error.js');
var utils = require('../services/utils');
var models = require('../services/models');
var _ = require('lodash');

return models.Location.filter(function(location) {

    return location.hasFields("place_id").not();

}).then(function(locationModels) {

    return Promise.map(locationModels, function(locationModel) {

        return utils.resolveAddressWithGoogle({

            address_1: locationModel.address_1,
            state: locationModel.state,
            city: locationModel.city,
            country_code: locationModel.country_code,
            postal_code: locationModel.postal_code

        }, 'en').delay(100).then(function(geocode) {

            if (!geocode) {
                return;
            }

            console.log(geocode);

            locationModel.geo = models.r.point(geocode.lng, geocode.lat);
            locationModel.place_id = geocode.place_id;
            locationModel.save();
        });
    }, {concurrency: 1});

}).finally(function() {
    return Promise.delay(1000).then(function() {
        return models.r.getPoolMaster().drain();
    });
});
```

So if I don't do delay before draining the pool the very last update fails.

**Comment by neumino** [comment]
You need to return locationModel.save() or map is basically synchronous.

**Comment by dtoubelis** [comment]
Oh, I think you are right. These missing returns are still haunting me :-)

**Comment by dtoubelis** [comment]
BTW, `dbReady()` is not documented.

**Comment by neumino** [comment]
`dbReady` was an internal thing, that's why it was missing from the doc. It looks like it can be useful, so  I just added some doc about it.
Thanks
