### ISSUE TITLE
Issue connecting to a new instance in Compose.io

### ISSUE THREAD

**Issue by MDrooker** [neumino/thinky#482]
Im using the latest version of thinky...and getting this error connecting to an instance in compose.
Seems like I have done everything right.  But guess not.
Here is a copy of my config-
config:{
                host: 'host from admin',
                db: 'bahhumbug',
                port: 27494,
                authKey: 'here is where the authkey would be'
            }

Unhandled rejection ReqlDriverError: Could not parse the message sent by the server : 'ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
'.
    at TLSSocket.<anonymous> (/Users/matthewjon/Development/Projects/watercooler-api/node_modules/rethinkdbdash/lib/connection.js:171:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:529:20)

Anyone seen this with compose.io?

**Comment by neumino** [comment]
They provide RethinkDB 2.2 so you need to use a 2.2.x version of thinky.

**Comment by MDrooker** [comment]
Ahh...
Ok.  Im a dumb ass...Thank you.

So any is there any chance of any backward compatibility in our future? 

As I move between instances, local and hosted, switching based on environment may be tricky

**Comment by neumino** [comment]
The rule of thumb is that thinky/rethinkdbdash x.y.z will match any x.y version of RethinkDB.
Most of the time you can use a newer thinky/rethinkdbdash, but this time the handshake was completely changed and it was a bit too annoying to keep multiple handshakes.

That being said, RethinkDB doesn't release as fast as it use, so maybe I'll try to make things more backward compatible in the future.
