### ISSUE TITLE
Error function not triggering

### ISSUE THREAD

**Issue by andela-omesanni** [neumino/thinky#483]
Anytime I run the code above, I am expecting an error message due to me deliberately not including a certain attribute that is required. but every time code runs, it sends a 200 status code back to me. It never enters the .error function. Dont know if u have any ideas on what might me causing this

```javascript
user.saveAll().then(function(doc) {console.log(doc);
    res.json(doc);
  }).error(function(err) {console.log('--here', err);
    res.status(500).send(err);
  });

**Comment by neumino** [comment]
Please provide more context on why you think this should fail, what your model is and what you are actually saving...
