### ISSUE TITLE
Recommendations for multi-tenancy approach

### ISSUE THREAD

**Issue by newoga** [neumino/thinky#494]
Thanks for the great work on your rethinkdb projects. I was looking at using thinky to prototype a small multi-tenanted app. Do you have any recommendations on best way to achieve this using thinky and/or rethinkdbdash?

I reckon that the nature of how rethinkdbdash pools connections, doing multitenancy at the database level would be difficult. I'm assuming that adding some kind of `accountId` or `tenantId` key in each model would the most reasonable approach.

**Comment by neumino** [comment]
I depends what kind of multi tenanted app you need. I'm not sure what you are trying to do, but I guess you probably want to create different databases with each a different user to access it.

Accounts were added in RethinkDB 2.3

**Comment by newoga** [comment]
Yes, I think different databases per account would be best. however is there an easy way to switch database within thinky?

**Comment by neumino** [comment]
Nope, that's currently not possible. The only way to manage multiple databases is probably to create multiple instances of thinky.

**Comment by inteliti** [comment]
Hi, thanks for your work. We are new to Node.js and non-SQL data bases, we are very happy with this technologies. We are building a multi-tenat application where a group of users share the same data model, each of these groups will be a tenant. We are planning to create a new database for each Tenant, it is a good practice when you can get thousands of database? What is the best approach? How many Thinky instance can we do?
