### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by artdude543** [neumino/thinky#498]
Heyo, 

Recently updated to the new version of RethinkDB. But we're coming across an issue with a locked down user on app start it fails with complaints about not having the right `config` options. The user has the needed permissions on the database, but thinky uses a global method which required higher permissions which I don't really want to give out.

This is the [line on the code](https://github.com/neumino/thinky/blob/master/lib/model.js#L208) causing the issue.

Not sure if you have any thoughts about this or a solution which does not mean giving global permissions to a user.

**Comment by neumino** [comment]
If you don't want to give the `config` permission of your user, just pass `init: false` to your model. Thinky won't try to create the table and the indexes.

**Comment by artdude543** [comment]
Does not really solve the problem though. On mass scale you would want the module to create the database and modules w/o needing higher permissions. Otherwise this would open up security issues with apps.

Having to create all the tables / databases along with misc table settings manually is not scalable or efficient. The rest of the module works fine once tables are created manually but even then will still throw errors as the method being called is global scope not database scope. The user has the `config` permission for the database it's allowed on but this does not prevent the issue hence the creation of the issue in the first place.

Either something is kwerky with the permissions scope on Rethink's side or the fact of calling global methods is a bad idea if you want to have users with database / table scopes only.

**Comment by neumino** [comment]
> but even then will still throw errors as the method being called is global scope not database scope
What throws if you pass `init: false`?

I think you have unreasonable expectations. You are not supposed to let the server responsible for serving the traffic to create the table/indexes.

The way updates should be done is:
1. Run a simple script that import all your models, relations, indexes
2. Wait for this script to finish
3. Update the server serving traffic

Can you provide a script that creates your user/database that shows your issue?
