### ISSUE TITLE
toJSON not ES standard compliant?

### ISSUE THREAD

**Issue by moll** [neumino/thinky#501]
Hey,

@MadRabbit reported to me (
https://github.com/moll/js-must/issues/45) that Thinky has a `toJSON` method, but it throws when `JSON.stringify` calls the `toJSON` with one argument, the key under which its serializing the object.

Would you mind looking into this? I don't use Rethink nor Thinky myself. Thanks!

PS. The related section in ES5 specs specifying `toJSON` with one argument: http://www.ecma-international.org/ecma-262/5.1/#sec-15.12.3

**Comment by neumino** [comment]
What happens in https://github.com/moll/js-must/issues/45 is that you tried to compare a ReQL query.
I guess the documents are missing a field and the default value was set to something like `r.now()`. When you try to compare these documents, you try to serialize the query which fail. This is WAI on my end as you don't want to serialize a query to JSON and can't properly compare these anyway.
