### ISSUE TITLE
Get stream using `toStream()`

### ISSUE THREAD

**Issue by hassansin** [neumino/thinky#503]
`Model.toStream().pipe(writable)` throws an error saying pipe is undefined as it wraps the stream with Query object. I am using the private property `_query` to access the stream:

`Model.toStream()._query.pipe(writable)`

Can I get the stream object directly without any private property?

**Comment by neumino** [comment]
`toStream` is an experimental-ish (yet stable?) feature in rethinkdbdash. It's not supported by thinky at the moment. So you using `_query` is the way to go for now.
