### ISSUE TITLE
How to update a document

### ISSUE THREAD

**Issue by mnegi** [neumino/thinky#504]
I just want to update an existing document using PUT. I tried with save but it didn't work. Will appreciate any thoughts on this.

**Comment by neumino** [comment]
What didn't work?
Did you retrieve the document, merge your payload, and save it again?
You could use setSaved to force an update.

**Comment by mnegi** [comment]
Hi @neumino, Thanks for your reply.

I have a user model with basic details like id, name, mobile.
and also I check for unique mobile number
```
User.pre('save', function(next) {
    User.filter({mobile: this.mobile}).run().then(function(result) {
        if(result.length > 0){
            next(new Error("Mobile already registered."));
        }else{
            next();
        }
    });
});

```
When I try updating it with merge. It throws validation exception which is logically correct I call it in this fashion.
```
 var data = req.body; // Data posted by the user
    User.get(data.id).run().then(function(user) {
        user.merge(data).save().then(function(result) {
            res.json({
                result: result
            });
        }).error(handleError(res));
    }).error(handleError(res));
```

Alternatively what I have done is 
```
User.get(req.body.id).update(req.body).then(function(result) {
        res.json({
            result: result
        });
    }).error(handleError(res));
```
Which is working. What do you suggest in this case.

**Comment by neumino** [comment]
`save` perform a `replace` under the hood, so if you want a partial update, your solution is the way to go.

**Comment by jnsq** [comment]
Just to clarify because i was misled : `save` used in conjunction with `merge` will not perform a `replace` but an `update` (just tested a minute ago). If you want to replace the whole document (and may remove fields), use only `replace`, and if you just want to update the document (and never delete fields), use `save` in conjunction with `merge` OR `replace`.

Neumino, feel free to let me know if i'm wrong.
