### ISSUE TITLE
Casting?

### ISSUE THREAD

**Issue by contra** [neumino/thinky#506]
Do you ever plan on adding casting (ala mongoose)?

Example 1 w/ Dates:

```js
const User = rethink.createModel('User', {
  id: type.string(),
  created: type.date()
});

const inst = new User({ created: Date.now() })
console.log(typeof inst.created) // number
// inst.created is a number, even when saved to the db and retrieved again
```

Example 2 w/ Points:

```js
const User = rethink.createModel('User', {
  id: type.string(),
  location: type.point()
});

const inst = new User({ location: [ lat, lon ] })
// inst.location is an array, even when saved to the db and retrieved again
```

It's confusing because even with strict validation on these pass as valid, even though an array is not a point and a number is not a date.

I see a few solutions:

- add casting on save
- add casting on construct
- fix the validation to check dates and points (and any others that might be broken in this way)

**Comment by neumino** [comment]
I'm not sure to understand what's the point in automatically casting a type to another one. Why should a date become a number when it's a date? Where do you store the timezone there?

**Comment by contra** [comment]
@neumino You might want to re-read the issue I think you have something confused. I'm saying it SHOULD be a date, not a number. This is not currently the case, even when the type is set to date - yet the validation still says everything is okay.

**Comment by neumino** [comment]
Oh I see. We currently cast locations because there's no native object to represent a location.

For dates, we do have native objects, so I don't see a strong reason to make the framework less flexible. It's just a wider surface for bugs and `new Date()` is not harder to write than `Date.now()`

#508 for location may be worth doing it though.
