### ISSUE TITLE
Model.update() does not trigger 'save' event

### ISSUE THREAD

**Issue by antoine-duchenet** [neumino/thinky#509]
Is there any way to hook on `Doc.save()` AND `Model.update()` ?

It's a bit counter-intuitive that the `.update()` method called on my Thinky model does not trigger the `pre('save')` defined on this model.

**Comment by kevinkleine** [comment]
https://github.com/neumino/thinky/issues/262

**Comment by neumino** [comment]
Closing as duplicate
