### ISSUE TITLE
Any way of selecting some fields on getJoin?

### ISSUE THREAD

**Issue by nahue** [neumino/thinky#514]
My code is the following:

```javascript
const photos = await Photo.getJoin({
     messages: {
           user: {
                 _apply: function(seq) {
                     return seq;
                 },
                 _array: false
                }
            }
});
```

I would like just to include user.email instead of the whole user object.. how can i accomplish this ? i would love to add this to the docs because i guess other people will run into this trouble.

Thanks!

**Comment by neumino** [comment]
Hum, you can do it, but you need to work on the data returned by getJoin. Just chain getJoin with a map and alter the data to remove everything but user.email.

The problem if you do that is that if you user model has some required field, it will fail the validation on retrieve.
