### ISSUE TITLE
Issue Getting joins to a document that has relations from multiple Tables. 

### ISSUE THREAD

**Issue by valayDave** [neumino/thinky#516]
So I have been digging through the web on the issue I am facing while having multiple 1-n relations in a single table. 

I have a Users, Campaign and a Campaign Transaction model. 

The schema to the Campaign Model is 
```
{   
    name: type.string().required(),

    createdby : type.string().optional(), //ref: Names.master.user
       
    startDate: type.date().default(r.now()),
    
    endDate: type.date(),
    
    campaignAmount: type.number().required(),
   }`

Schema to the user Model is 

`{
    mobile: type.number().required(),
    
    imei: type.number().required(),
    
    name: type.string().required(),
    
    dateOfBirth: type.date(),
}
```

The above two models are the master tables. The transaction table is called CampaignTransactions. 

```
{

    status: type.string() ,

    statusParams: type.any(),

    adminIntervention: type.boolean().default(false),

    createdOn : type.date().default(r.now()) 
}
```

I have defined the following relations : 

```
{
Campaigns.hasMany(CampaignTransactions,'campaign','id','campId');
CampaignTransactions.belongsTo(Campaigns,'campaignData','campId','id');

Users.hasMany(CampaignTransactions,'campaignTransactions','id','userId');
CampaignTransactions.belongsTo(Users,'userData','userId','id');
}
```

Post declarations I am storing a user and a campaign, getting the respective Id's and adding those fields to the CampaignTransactions document.

Now when request a join using thinky on the CampaignTransaction model I get an empty array.

When I try and save it in a way given in the tutorial that I relate the instance of the model object with the appropriate keys in the CampaignTransaction document, I get the following Error on the saveAll() : 

`Unhandled rejection RangeError: Maximum call stack size exceeded
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:428:48)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:534:40)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)
    at /WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:492:44
    at Object.loopKeys (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/util.js:200:16)
    at Document.__makeSavableCopy (/WORK/College/FInal Year Project/WEB SERVICES  node_modules/thinky/lib/document.js:475:10)`

What can be the issue?

**Comment by neumino** [comment]
Can you provide the code where you save/retrieve things?
A short script would be better.

**Comment by valayDave** [comment]
So below is the code I am using for the models provided in the above post. 

       var campaign = new Models.Campaigns({
            endDate : new Date('10/10/2016'),
            campaignAmount : 10,
        });        
        campaign.save(function(err,campaignObj){
           if(err){
               console.log(err);
           }else{
                UserModel.get('8fba8e54-1e53-4e2a-8ff9-9e36fadb039e').run().then(function(user){
                    var transaction = new CampaignTransactions({
                        status : 'done',
                        statusParams : {
                            someParam : 'haha'
                        },   
                        campId : campaignObj.id,
                        userId : user.id   
                                   
                    });

                    transaction.saveAll().then(function(transactionObj){
                        console.log(transactionObj);
                        CampaignTransactions.get(transactionObj.id).getJoin({userData:true}).then(function(someDocument){
                            console.log(someDocument);
                        })
                    });
                });
                
           } 
        });``

The Above piece of code logs the object it saved but yields an empty array from the join.


        var campaign = new Models.Campaigns({
            endDate : new Date('10/10/2016'),
            campaignAmount : 10,
        });        
        campaign.save(function(err,campaignObj){
           if(err){
               console.log(err);
           }else{
                UserModel.get('8fba8e54-1e53-4e2a-8ff9-9e36fadb039e').run().then(function(user){
                    var transaction = new CampaignTransactions({
                        status : 'done',
                        statusParams : {
                            someParam : 'haha'
                        },   
                       // campId : campaignObj.id,
                       // userId : user.id   
                                   
                    });
                     transaction.userData = user;
                     transaction.campaign = campaign;
                     campaign.campaign = transaction;
                     user.campaignTransactions = transaction;
                    transaction.saveAll().then(function(transactionObj){
                        console.log(transactionObj);
                    CampaignTransactions.get(transactionObj.id).getJoin({userData:true}).then(function(someDocument){
                            console.log(someDocument);
                        })
                    });
                });
                
           } 
        });``

This piece of code yields the error mentioned in the above thread.

Am I doing something wrong?

**Comment by neumino** [comment]
This works for me:
```
var thinky = require('./lib/thinky.js')();
var type = thinky.type;
var r = thinky.r;

var Campaigns = thinky.createModel('Campaigns', {
  name: type.string(),
  createdby : type.string().optional(), //ref: Names.master.user
  startDate: type.date().default(r.now()),
  endDate: type.date(),
  campaignAmount: type.number(),
});

var Users = thinky.createModel('Users', {
  dateOfBirth: type.date(),
});

var CampaignTransactions = thinky.createModel('CampaignTransactions', {
  status: type.string() ,
  statusParams: type.any(),
  adminIntervention: type.boolean().default(false),
  createdOn : type.date().default(r.now()) 
});

Campaigns.hasMany(CampaignTransactions,'campaign','id','campId');
CampaignTransactions.belongsTo(Campaigns,'campaignData','campId','id');

Users.hasMany(CampaignTransactions,'campaignTransactions','id','userId');
CampaignTransactions.belongsTo(Users,'userData','userId','id');

var campaign = new Campaigns({
  endDate : new Date('10/10/2016'),
  campaignAmount : 10,
});        
campaign.save(function(err,campaignObj){
  if(err){
    console.log(err);
  } else {
    var user = new Users({});
    user.save().then(function(user){
      var transaction = new CampaignTransactions({
        status : 'done',
        statusParams : {
          someParam : 'haha'
        },   
        campId : campaignObj.id,
        userId : user.id   
      });
      transaction.saveAll().then(function(transactionObj){
        console.log(transactionObj);
        CampaignTransactions.get(transactionObj.id).getJoin({userData:true}).then(function(someDocument){
          console.log(someDocument);
        })
      });
    });
  } 
});
```

Can you provide a full script that triggers your error? (that I can just run).

**Comment by valayDave** [comment]
I checked the issue I was facing . I now come to realise that it was not because of the Join. It was because of the using the getAll function. I have done the following according to the documentation. But I am still facing an issue while querying the secondary composite index. 

The following is the index I created in the campaign transaction table : 

```
CampaignTransactions.ensureIndex('transactionId',function(doc){
    return doc('campId').add(doc('userId'));
`});`
```

The query I ran was the following which is not yeilding anything : 

```
 CampaignTransactions.getAll([campaignObj.id+user.id],{index:'transactionId'}).then(function(someDocument){
                            console.log(someDocument);
`})` 
```

Can I create a secondary index using composite Values and how do I query it ?

**Comment by neumino** [comment]
This is what you're looking for (note that there are no square brackets).
```
CampaignTransactions.getAll(campaignObj.id+user.id,{index:'transactionId'})
```

**Comment by valayDave** [comment]
Thanks @neumino  ! 

One more thing. There isn't a proper documentation provided on how to do Joins and saves for hasManyAndBelongsTo . Can you yield a snippet which does the same so that I can reference it ?

**Comment by neumino** [comment]
Just call `saveAll({<field>: true})`
http://thinky.io/documentation/api/document/#saveall
