### ISSUE TITLE
Relations doesn't create secondary indexes

### ISSUE THREAD

**Issue by deoqc** [neumino/thinky#520]
I thought that by doing relations, the necessary secondary index would be created. But I'm having to use `Model.ensureIndex`.

Is this a bug, a feature or am I doing something wrong?

**Comment by neumino** [comment]
You are probably doing something wrong. `getJoin` is using indexes under the hood, so if they were missing `getJoin` would be throwing errors.

**Comment by deoqc** [comment]
It did throw an error, and it was how I saw the index were not created.

**Comment by neumino** [comment]
Can you provide a script that triggers this error
