### ISSUE TITLE
hasAndBelongsToMany relation and Feeds

### ISSUE THREAD

**Issue by tinque** [neumino/thinky#522]
When you use a hasAndBelongsToMany relation a third table is automatically created and managed by thinky.

How listen feeds on this table ?

Thkx

**Comment by grantcarthew** [comment]
I created the table myself and didn't use `hasAndBelongsToMany`. This isn't an answer I know. I'm interested in Michel's response.

**Comment by Justkant** [comment]
Probably already answered #413

**Comment by neumino** [comment]
https://github.com/neumino/thinky/issues/413#issuecomment-167457785 is probably what you are looking for.

But the TL;DR is that it's not possible at the moment. Changefeeds on join is a feature that is often discussed, but it still hasn't shipped yet :(
