### ISSUE TITLE
how to handle with `pluck`?

### ISSUE THREAD

**Issue by xy02** [neumino/thinky#526]
if I invoke `User.pluck('name').run()`, an error will be thrown:
```
Error: The results could not be converted to instances of `User`
Detailed error: Value for [id] must be defined.
```

**Comment by gjuchault** [comment]
Hi

Using `.run()` will ask Thinky to make the results matches the model. If you want to use `.pluck()` you need to use `.execute()`. Documentation [here](https://thinky.io/documentation/api/query/#execute)

**Comment by neumino** [comment]
Like @gjuchault said, `run` expect a valid model to be returned (one that's savable). If you want to just retrieve a few fields, use `execute` instead.

**Comment by xy02** [comment]
Thanks @gjuchault  @neumino
