### ISSUE TITLE
getNearest with getJoin

### ISSUE THREAD

**Issue by deoqc** [neumino/thinky#527]
I have 2 models `Addresses` and `Stores` and the relations `Addresses.belongsTo(Stores, 'store', 'store_id', 'id')`.

The `Addresses` has a geo index called `geocode` and I wanted to run the following:

```Javascript
Addresses.getJoin({store: true}).getNearest(...)
```

The queries `Addresses.getJoin({store: true})` and `Addresses.getNearest(...)` are working just fine. 

---

Following is the error:
```
Expected type TABLE but found SEQUENCE:
VALUE SEQUENCE in:
r.table(\"addresses\").merge(function(var_1) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return r.branch(var_1.hasFields(\"store_id\"), r.table(\"stores\").getAll(var_1(\"store_id\"), {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        index: \"id\"
        ^^^^^^^^^^^
    }).coerceTo(\"ARRAY\").do(function(var_2) {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        return r.branch(var_2.count().eq(1), r.object(\"store\", var_2.nth(0)), r.branch(var_2.count().eq(0), {}, r.error(r.expr(\"More than one element found for \").add(var_1.coerceTo(\"STRING\")).add(r.expr(\"for the field \").add(\"store\")))))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    }), {})
    ^^^^^^^
}).getNearest(r.point(-43, -23), {
^^                               ^
    index: \"geocode\",
    ^^^^^^^^^^^^^^^^^
    maxDist: 100000,
    ^^^^^^^^^^^^^^^^
    maxResults: 100
    ^^^^^^^^^^^^^^^
})
^ 

```

---

I believe it is related to the `hasFields`. I'm running the query without the thinky models (`r`) and when I used the `hasFields` got the same error.

**Comment by neumino** [comment]
`getNearest` works only on a table, not a sequence.
http://rethinkdb.com/api/javascript/get_nearest/

**Comment by deoqc** [comment]
What about something like `Addresses.getNearest(...)('doc').getJoin({store: true})`? 

I'm able to get the data from from `r` command:
```Javascript
r.table('addresses')
  .getNearest(...)('doc')
  .eqJoin(r.row('store_id'), r.table('stores'))
  .map(function(obj) {
    return obj('left').merge({store: obj('right')});
  })
```
But not the `thinky` command above (`Addresses.getNearest(...)('doc')` errors). Is it the automatic array conversion?

**Comment by deoqc** [comment]
I did `Addresses.getNearest(...).map(r.row('doc')).getJoin({store: true})` and worked. 

Just wondering if there is any performance difference using `thinky`.
