### ISSUE TITLE
Validate uniqueness (username and email) before saving

### ISSUE THREAD

**Issue by deoqc** [neumino/thinky#528]
I was trying to use the `r.branch` command to loosely validate unique ​*username* and unique ​*email*​ (I have a separate table for each with primary key `r.uuid([username or email])`. So:

```Javascript
r.do(
  r.table('usernames').get(username_id), 
  r.table('emails').get(email_id), 
  (username_exists, email_exists) => (
    r.branch(
      username_exists,
      r.error('Username already exists'),
      email_exists,
      r.error('Email already exists'),
      user.saveAll({ username: true, emails: true })
    )
  )
)
```
The problem is the last command `user.saveAll(...)` is running even if `username_exists` is `true` and `r.error('Username already exists.')` is throw.
What am I doing wrong?

**Comment by Justkant** [comment]
This is probably because saveAll is returning a promise. r.branch needs a variable that it can understand.
Take a look at those [utils](https://thinky.io/documentation/api/query/#functional-utilities)

**Comment by neumino** [comment]
Yea, `r.branch` is executed in RethinkDB, so you can't put a promise there. You can put only a ReQL term.

**Comment by deoqc** [comment]
There is no way to use thinky models with r.branch (like [here](https://github.com/neumino/thinky/issues/331))?

**Comment by neumino** [comment]
You can't use `saveAll`/`save` in `r.branch` as these commands return a promise.
You can use a model though or any operation. Just make sure not to call `run` inside `r.branch`.

**Comment by deoqc** [comment]
Ok, thanks @Justkant @neumino.

Is there any recommendation in how to check uniqueness before saving? I'm currently using something like this:

```Javascript
...
const [username_exists, email_exists] = await Promise.all([
        r.table('usernames').get(username_id),
        r.table('emails').get(email_id),
      ])

if (username_exists) throw new Error('Username already exists')
if (email_exists) throw new Error('Email already exists')

await user.saveAll({ username: true, emails: true })
...
```

But I would prefer just to send one command to rethinkdb.

**Comment by Justkant** [comment]
@deoqc -- You could do this with a single table:

``` javascript
r.do(
  r.table('user').getAll(user.username, { index: 'username' }).nth(0).default(false), 
  r.table('user').getAll(user.email, { index: 'email' }).nth(0).default(false), 
  (username_exists, email_exists) => (
    r.branch(
      username_exists,
      r.error('Username already exists'),
      email_exists,
      r.error('Email already exists'),
      r.table('user').insert(user)
    )
  )
)
```

But in this version we're not using thinky

**Comment by deoqc** [comment]
Thanks @justkant

User has only one username but many emails, and it is very important to garantee uniqueness so using table with id r.uuid(username or email). 

My original version would also work if not using thinky, but would be great to use save/saveAll with r.branch though.

**Comment by neumino** [comment]
You can't use thinky's `save`/`saveAll` at the moment.  `doc.save()` is basically just `r.table(tableName).insert(doc)`, so @Justkant's answer is pretty close to what thinky would do if you could use `doc.save` with `r.branch.` (that would in practice means that `doc.save` returns a query instead of the promise coming from running the query).

For `saveAll`, it's impossible because `saveAll` may issue multiple inserts. Changing that is a lot of work and might not be possible.
