### ISSUE TITLE
eqJoin on a filter?

### ISSUE THREAD

**Issue by saikat** [neumino/thinky#534]
I am using Thinky for its schema validation purposes but am preferring to use basic ReQL for my querying and joining.  One thing I noticed though -- even though I can do most ReQL expressions on the result of a filter like this:

```
UserOrganization.filter({user_id: 1}).count()
```

Doing this gives me an error: saying `_models.UserOrganization.eqJoin(...).filter(...) is not a function`

```
UserOrganization.filter({user_id: 1}).eqJoin('organization_id', r.table('organization'))
```

Is this by design?

**Comment by neumino** [comment]
Works fine for me. Can you provide a full script that triggers this error?
