### ISSUE TITLE
Does not work the finished callback

### ISSUE THREAD

**Issue by xfg** [neumino/thinky#535]
The `each` function accepts the second `onFinishedCallback` argument http://www.rethinkdb.com/api/javascript/each/ but within Thinky this doesn't work.

And I can not do this example:
```
Model.filter({field: value})
      .changes({
        includeInitial: true,
        includeStates: true
      })
      .then(feed => {
        feed.each((err, doc) => {
          if (err) throw err;

          let res = {data: doc};

          if (doc.isSaved() === false) {
            res.state = 'remove';
          } else if (doc.getOldValue() === null) {
            res.state = 'add';
          } else {
            res.state = 'change';
          }

          console.log(res);
        }, () => {
          console.log({state: 'complete'});
        });
      });
```

`eachAsync` http://www.rethinkdb.com/api/javascript/each_async/ doesn't work too.

How to run `onFinishedCallback` ? Or it does not work for feeds?

**Comment by xfg** [comment]
I think I found the problem within `rethinkdbdash` at https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L235 `keepGoing` variable is always `undefined` state and thus the code
```
if (keepGoing === false) {
      if (typeof onFinish === 'function') {
        onFinish();
      }
    }
```
never runs.

**Comment by xfg** [comment]
I had been mistaken and seems that the problem somehow bound with [`Cursor.toArray`](https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L93) because when I run my example (see my initial message) then [`Cursor.each`](https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L216) is called two times and as far as I understand [this code](https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L222) should be called when the rows within the cursor is longer not available but this code run only once with `onFinish` equal to this function
```
function() {
  resolve(result);
}
```
which is within [`Cursor.toArray`](https://github.com/neumino/rethinkdbdash/blob/master/lib/cursor.js#L105) function but my `onFinish` callback is never called.

I yet don't undestand how to fix this problem.

**Comment by xfg** [comment]
The problem seems bound with [rethinkdbdash](https://github.com/neumino/rethinkdbdash)

**Comment by neumino** [comment]
A feed never terminates, so you can pass a onFinsh method, but it's never called.

**Comment by xfg** [comment]
But how does [horizon](https://github.com/rethinkdb/horizon/blob/next/server/src/endpoint/subscribe.js#L30) work ?
and if onFinish method is never called then how to make sure that the all current rows was sent to a client and that the client can start to handle them?

**Comment by neumino** [comment]
I'm not sure what horizon does here. Can you describe when you expect this callback to be called? When what is finished?

**Comment by xfg** [comment]
@neumino I try to send one document at a time to client and when the all current documents was sent to client I want to send message that the all documents was sent and that the client can start to handle them.

I initially thought that it can be achieved with help `onFinished` callback, but you and @danielmewes explained me that the `onFinished` callback does not work for changefeeds and also @danielmewes told me that the `horizon` uses for this purpose `{state: 'ready'}` message which is sent when the initial values have all been sent. But I nohow can't do it with `thinky` not through `onFinished` callback not through `{state: 'ready'}` because `onFinished` does not work for changefeeds and also thinky does not send `{state: 'ready'}` message.

Right now thinky just drops the `{state: 'ready'}` message https://github.com/neumino/thinky/blob/master/lib/feed.js#L79 but I think that thinky should be send a `{state: 'ready'}` message or something similar if the client sets the `includeStates` option to `true` for `changes` function.

**Comment by xfg** [comment]
+1

**Comment by neumino** [comment]
I opened #541 to track surfacing these events.
