### ISSUE TITLE
Issue with adding relation

### ISSUE THREAD

**Issue by vmarcel** [neumino/thinky#540]
I am getting an error when I try to add a relation as shown below:
 ```javascript          
userQuery.get(user.id).addRelation("projects", {id: project.id}).then(function (result) {
 console.log( result );
});
```
error given:
```
Unhandled rejection TypeError: Cannot read property 'apply' of undefined
```

**Comment by vmarcel** [comment]
Another quick question, is the intention of getJoin to confirm that thinky created a relation between the 2 documents?

**Comment by neumino** [comment]
Can you provide a full script that reproduce this? What are the models/relations? Also what's the full stacktrace?

`getJoin`'s first purpose is to return the joined documents. It can also be used to confirm that the relation was created.

**Comment by vmarcel** [comment]
Hello @neumino Thanks for the reply. After some testing I confirmed that the joins are there between the documents. I was trying to get the ids of the `project` table in an array of the `user` table to signify that there is a join. Reflecting on your examples in the docs I figured that's how it would save in the database. 
i.e:
```javascript
userDoc {
        email: 'joe@joe.com'
        name: 'joe',
        location: {
            state: 'NJ',
            zip: 12345
        }
        project_id: [ 'id1', 'id2', 'id3' ]
}
```
I had trouble with that case, instead once I realized I can confirm the relation through `getJoin` my original concept went out the window. Do you know of a visual diagram that I can refer to in reference to how the other relations work? If not I can construct some in regards to `belongsTo`, `hasOne` and so on. And with your review can use them to show how these relations work for better understanding.

**Comment by neumino** [comment]
How the relations works and where the foreign keys are is documented at http://thinky.io/documentation/relations/

Let me know if you have more questions.

**Comment by vmarcel** [comment]
Ok I am trying to use addRelations to join 2 documents and the field is not a primary key and I get this error
```
Unhandled rejection Error: The partial value is not valid, so the write was not executed. The original error was:
Primary key for the joined document not found for a `hasOne/hasMany` relation.
```

here is the line of the code that is causing the issue
```javascript
User.filter({id: user.id}).addRelation('projects', {volcan_lead: user.id}).run() // create relation
```
Below is the relations between the models
```javascript
User.hasMany(Project, 'projects', 'id', 'user_creator');
Project.belongsTo(User, 'user', 'user_creator', 'id');
```
In the doc it shows it should work with other fields as you have a user and account_number addrelation example.

What could I be doing wrong?
Thanks for the help in advanced
