### ISSUE TITLE
Documentation bug in hasMany example

### ISSUE THREAD

**Issue by eloquence** [neumino/thinky#542]
In the docs at http://thinky.io/documentation/api/document/ , there is a section which begins with

*Example: Update a hasMany relation.*

It's an author/post example, but it then makes reference to a user model:

````javascript
user.splice(1, 1);
user.saveAll({posts: true})
````

I'm guessing (without having worked with hasMany relations yet!) that this should say:

````javascript
author.posts.splice(1, 1);
author.saveAll({posts: true})
````

(and a few more references to the user model that need to be updated).

If that looks right, I'm happy to prepare a pull request, presumably against:
https://github.com/neumino/thinky/blob/gh-pages/documentation/api/document.md

**Comment by neumino** [comment]
Sorry for the late response, I missed this issue somehow.
You are right, it's a mistake in the example. I just pushed your fix.

Thanks : )

**Comment by eloquence** [comment]
Thanks for taking a look! You fixed the missing "posts", but I think the "user" / "author" confusion is still there.

**Comment by neumino** [comment]
Thanks, I missed that earlier. It should be fixed now.

**Comment by eloquence** [comment]
Mostly! :)
