### ISSUE TITLE
Date range filter with between and during is not working

### ISSUE THREAD

**Issue by mnegi** [neumino/thinky#543]
# Date filter is not working

## Question
We are trying to filter data from a table based on the date field. The data is stored in RethinkDB date type. When we try ReQL query in RethinkDB it shows correct data but with thinky and app its not. 
The question I have is how to apply date filter along with some other filter in thinky.

Model

```
var Entry = thinky.createModel('entry', {
   id: type.string(),
   userId:type.string(),
   description: type.string(),
   transactionDate: type.date(),
   createdOn: type.date().default(r.now)
});

```

Here is the code that is not working

```
Entry.filter({userId:uid}, r.row('transactionDate').during(r.time(2016, 8, 1,"Z"), r.time(2016, 8, 8,"Z"))).skip(offset).limit(limit).run().then(function(entries) {      
     res.json({
           data: entries
       });
   });

```

**Comment by neumino** [comment]
Please providea script that shows what doesn't work with thinky.

**Comment by mnegi** [comment]
Hi @neumino I have updated the issue description with the model and the code.

**Comment by neumino** [comment]
Does it work if you do r.table('entry').filter(...)?

**Comment by mnegi** [comment]
```
r.table("Entry1").filter(  r.row('transactionDate').during(r.time(2016, 1, 1,"Z"), r.time(2016, 6, 8,"Z"))).skip(offset).limit(limit).run().then(function(entries) {      
     res.json({
           data: entries
       });
   })
```

This is working fine. 

Just one more question on this, how can I add another filter to it say userId?

**Comment by mnegi** [comment]
Got a solution for another filter by adding one more filter to the expression.

```
 r.table("Entry1").filter({userId:"silan"}).filter(r.row('transactionDate').during(r.time(fYear, fMonth, fDate,"Z"), r.time(tYear, tMonth, ttDate,"Z"))).skip(offset).limit(limit).run().then(function(entries) {    
 res.json({
           data: entries
       });
   })
```
