### ISSUE TITLE
addRelation

### ISSUE THREAD

**Issue by vmarcel** [neumino/thinky#546]
Ok I am trying to use addRelations to join 2 documents and the field is not a primary key and I get this error
```
Unhandled rejection Error: The partial value is not valid, so the write was not executed. The original error was:
Primary key for the joined document not found for a `hasOne/hasMany` relation.
```

here is the line of the code that is causing the issue
```javascript
User.filter({id: user.id}).addRelation('projects', {volcan_lead: user.id}).run() // create relation
```
Below is the relations between the models
```javascript
User.hasMany(Project, 'projects', 'id', 'user_creator');
Project.belongsTo(User, 'user', 'user_creator', 'id');
```
In the doc it shows it should work with other fields as you have a user and account_number addrelation example.

What could I be doing wrong?
Thanks for the help in advanced

**Comment by neumino** [comment]
Add the primary key for the joined document?

**Comment by vmarcel** [comment]
Do you mean by doing this?
```javascript
User.filter({id: user.id}).addRelation('projects', {id: 'project id'}).run()
```

**Comment by neumino** [comment]
Yes.
http://thinky.io/documentation/api/query/#addrelation

**Comment by vmarcel** [comment]
I am not getting the expected results. When I do what you have suggested the 'owner' of the project shifts from the creator to the acceptor. Currently, the way I intended it to work is for the user to create a project and another user accepts it and joins off of a different field. If I use the primary key the user who accepted the project becomes the creator and replaces the original creator.

Is that how it's supposed to work? 
Do I have to create another relationship between the 2 tables for the user who accepts the project?

**Comment by neumino** [comment]
Can you provide a full script that shows what the problem is?

**Comment by vmarcel** [comment]
Ok there isn't an error but this is what is happening

*A project is already created and a relationship between the User and Project model exists if the User created the Project

I have a userDoc which is the result of a getJoin



```javascript
User.get(user.id).getJoin({projects: true}).run().then(function(userDoc) {

/* userDoc = model {
  alias: 'volcan',
  created: 2016-08-15T21:00:36.042Z,
  email: 'volcan@msn.com',
  id: '47a34d14-5936-4af7-a6ac-40e1da99ebaf',
  is_org: false,
  is_volcan: true,
  location: { state: 'AK', zip: 123 },
  premium: true,
  projects: [] } */

 // in this case when the 'volcan' accepts the project create a join when they return to the projects page

//..query to pull proj.id ..//

User.get(user.id).addRelation('projects', {id: proj.id });

User.get(user.id).getJoin({projects: true}).run().then(function(newUserDoc) {
/* newUserDoc = model {
  alias: 'volcan',
  created: 2016-08-15T21:00:36.042Z,
  email: 'volcan@msn.com',
  id: '47a34d14-5936-4af7-a6ac-40e1da99ebaf',
  is_org: false,
  is_volcan: true,
  location: { state: 'AK', zip: 123 },
  premium: true,
  projects: 
   [ model {
       completed: null,
       created: 2016-08-15T21:01:46.144Z,
       deadline: 2016-08-17T00:00:00.000Z,
       description: 'yep yep',
       id: '6204a82c-441e-4c81-a71d-d3658f5ce95b',
       name: 'Wow',
       started: 2016-08-15T21:03:01.963Z,
       type: 'Upgrade',
       user_creator: '47a34d14-5936-4af7-a6ac-40e1da99ebaf',
       volcan_lead: '47a34d14-5936-4af7-a6ac-40e1da99ebaf',
       volcan_name: 'volcan' } ] } */

});
```
So As you can see the User_creator and volcan_lead share the same id when the volcan_lead is not the originator of the project. What is the proper way to join the project document to the volcan who accepts the project

**Comment by neumino** [comment]
`user_creator` is set, which is what `addRelation` did. I'm not sure what `volcan_lead` is since you didn't provided all the code...

**Comment by vmarcel** [comment]
`volcan_lead` is a user with a `is_volcan: true` specified 
 
this is part of the code that is related to the volcan_lead accepting a project
```javascript
exports.postAcceptProj = function(req, res){
    
    var projectId = req.path.split('/').slice(-1)[0]; // get the id from url path

    Project.get(projectId).update({volcan_lead: user.id, volcan_name: user.alias, started: r.now()}).run().then(function(proj){ // get project and update it
        res.redirect('/projects/' + projectId);
    });
}
```

this is the full code set from above
```javascript
exports.getProjects = function(req, res) {
    if (user.is_volcan == true) {
        User.get(user.id).getJoin({projects: true}).run().then(function(userDoc) { // get the created projects of the user        
            userProjects.filter({volcan_lead: user.id}).run().then(function(projs){
                User.get(user.id).addRelation('projects', {id: projs.id});
                
                User.get(user.id).getJoin({projects: true}).run().then(function(newuserDoc) {
                    res.render('private/volcanProjects', {
                        userProjects: newuserDoc
                    });
                });
            });
        });
    } 
    else {
        User.get(user.id).getJoin({projects: true}).run().then(function(userDoc) { // get the created projects of the user
            res.render('private/clientProjects', {
                userProjects: userDoc
            });
        });
    }
}
```

I hope this helps, I am unsure what else to add.

**Comment by neumino** [comment]
Hum, are you saying that `addRelation` is also updating `volcan_lead` when it's supposed to update only `user_creator`?

I'm not sure what the problem is, but I'm not convinced this is a thinky issue. If you can produce a script I can run that triggers this problem, I can take a look at it, but the code to add a relation is pretty straight forward and I don't see issue there:
https://github.com/neumino/thinky/blob/master/lib/query.js#L481

**Comment by vmarcel** [comment]
I want `addRelation` to join the project document to the `user` who is the `volcan_lead`. I do not want the `user_creator` to be updated as that is already set. 

A better example is I (vmarcel) created this issue, and you(neumino) accepted to help. The intention is that, I am still the creator of this issue. I do not want `addRelation` to update the creator of the issue to you after you have accepted to help. That's what is happening with my code. 

I will try and create a script to showcase it, but I will try out some other means to get the same results. Maybe it isn't a thinky issue as you stated.

**Comment by neumino** [comment]
When you wrote this:
```
User.hasMany(Project, 'projects', 'id', 'user_creator');
Project.belongsTo(User, 'user', 'user_creator', 'id');
```
You are linking the user to the projects by using the field `project.user_creator`. Did you mean to use `volcan_lead` instead of `user_creator`?

**Comment by vmarcel** [comment]
No, That is intended. For all users(this includes volcans) any projects they created can be retrieved with `getJoin`. But for volcans specifically, I need a way to tie projects they haven't created to projects they have accepted, because `getJoin` on projects would be empty unless they created a project.

I figured `addRelation` would be the solution to join on `volcan_lead`, that is where it comes into play. But it doesn't work as I thought, even the [addRelation](http://thinky.io/documentation/api/query/#addrelation) example uses account_number to join user and account, and that is how i tried to configure my setup with users and projects, by using `volcan_lead`

**Comment by vmarcel** [comment]
I figured out another solution. Instead of trying to join it, I just query the projs. I appreciate the help @neumino . I might have been trying too much in one setup. lol
