### ISSUE TITLE
Prevent r.dbCreate() from being called during create model? 

### ISSUE THREAD

**Issue by jasonsokolowski** [neumino/thinky#549]
I'm currently setting up user security for a particular database. The user has been granted full, read/write/config for that specific empty database. 

`r.db("databaseName").grant("username", {read: true, write: true, config: true})`

However, for obvious reasons, it does not have config globally. Is there a way to prevent calling dbCreate() on startup? Or am I missing something obvious? It prevents the rest of the tables / indexes from being generated. 

```
Unhandled rejection ReqlRuntimeError: User `username` does not have the required `config` permission in:
r.dbCreate("databaseName")
```

Thanks!

**Comment by balintant** [comment]
Same issue here. We want to restrict user permissions for production usage now. Thinky only wants to work with global `config` permission.

```js
r.grant('user', {config: true})
```

We need something like what we already have on models:
```js
thinky.createModel(tableName, schema, {
  init: false
})
```

**Comment by neumino** [comment]
Hum, there's currently no way to disable `dbCreate`, but if you create the database before, the `dbCreate` operation will fail but thing will still work.

**Comment by jasonsokolowski** [comment]
Hi, thanks for the reply, however in my experience, it causes all further operations to fail. It's possible I'm missing an important authentication step. However the following "should" give the username account access to do what it needs in the databaseName db. Correct? 

`r.db("databaseName").grant("username", {read: true, write: true, config: true})`

**Comment by neumino** [comment]
What's the error you see? Can you provide a full script I can run?

**Comment by jasonsokolowski** [comment]
Not currently sitting at my dev machine. But if you simply create a database, grant those permissions above. Then create a simple table model. It will fail to create the table. I'll post my error messages in about an hour.

**Comment by balintant** [comment]
I think we're having the same issue. So here's my error.

```bash
User `user` does not have the required `config` permission in:
r.dbCreate("database")
^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at Connection._processResponse (/Users/balintant/Workspace/my/project/node_modules/rethinkdbdash/lib/connection.js:382:15)
    at Socket.<anonymous> (/Users/balintant/Workspace/my/project/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
```

**Comment by neumino** [comment]
I looked a bit into it.

There's some code to ignore the error of `dbCreate` if the database already exists, but in this case if the user doesn't have the right, the error thrown is about the access not about the duplicate.

Pushed 2.3.6. You can pass `createDatatabase: false` to thinky to prevent dbCreate to be executed.

**Comment by singggum3b** [comment]
** `createDatabase: false` for anyone copy-paste like me 😭
