### ISSUE TITLE
Pluralize table names

### ISSUE THREAD

**Issue by nodesocket** [neumino/thinky#551]
I am using the recommended nomenclature:

````
# models/event.js
thinky.createModel('Event', {
    ....
});
````

````
# utils/thinkly.js
module.exports = {
    Event: require('../models/event.js')
};
````

But noticed that tables name in RethinkDB are singular. Sorry to nitpick, but should'nt tables names be plural? I.E. `Events` instead of `Event`.

Is this possible?

**Comment by ondreian** [comment]
you can just change the string you pass into the `createModel` function as the first argument if you want to pluralize them, but still keep the object keys and variable names as `Event`.

I personally would prefer if `thinky` did not pull in an entire inflection library for something that is easily handled by passing a different argument, but that's just me.

**Comment by neumino** [comment]
Just put a s at the end of the table name:
```
thinky.createModel('Events', {
    ....
});
```
