### ISSUE TITLE
Question: Best way to write tests without actually going to the database?

### ISSUE THREAD

**Issue by codewithpassion** [neumino/thinky#553]
Hey,

How can I test simple manipulations of documents without going to the database?
What I'd like to do is something like this:

    const Post = require('./model/post);
    class ServiceToBeTested {
  
       setMessage(postId, newMessage) {
           return Post.get(postId)
              .then(p => { 
                                   p.message = newMessage;
                                   return p.save();
                                });      

       }

   }

This is a fairly dummed down version of my problem, the real one is more complex.

I don't want to test if Thinky get's a saves the document properly, I just want to test if the message is properly assigned to the document and then if save is called.

What are my options?

So far I tried to go and override the proto functions, but that seems a bit clunky. 

Thanks,
Dominik

**Comment by neumino** [comment]
It would probably be mock the promise returned by the query?

**Comment by MarkHerhold** [comment]
@codewithpassion Ditto what neumino says. I do this with sinon and proxyquire.
