### ISSUE TITLE
How set parent of nested data to optional?

### ISSUE THREAD

**Issue by myyellowshoe** [neumino/thinky#556]
I know you create optional fields like:
`foo: type.string().optional(),`

If I create a model like below, how do I set the scores parent field to optional?

```
var Game = thinky.createModel("Game", {
    id: type.string(),
    name: type.string(),
    scores: [{
       win: type.number(),
       lose: type.number()
    }]
});
```

**Comment by neumino** [comment]
type.array().optional().schema(...)

**Comment by myyellowshoe** [comment]
Gotcha! Thanks! Wasn't clear from the docs for that.
