### ISSUE TITLE
How to create one way relation n-n

### ISSUE THREAD

**Issue by SagiUziel** [neumino/thinky#560]
Hi,
I have this model and relation:
```
 var User = thinky.createModel('User', {
        id: type.string(),
        fullName: type.string()
    });

User.hasAndBelongsToMany(User, "friends", "id", "id");
```
To each user, there are a lot of friends. I want to define 'user b' has a friend of 'user a':

`User.get('user a id').addRelation("friends", { id: 'user b id' }); //'user b' is a friend of 'user a'`

But in this case I got that 'user a' is a friend of 'user b' and 'user b' is a friend of 'user a'.
I dont want to define 'user a' has a friend of 'user b'. 

when I Run this command, I get that 'user a' is a friend of 'user b':

```
User.get('user b id').getJoin({friends: true }).execute().then(function(doc){
        console.log(doc);        
      }
```

How can I define one way relation n-n?

**Comment by neumino** [comment]
That's currently not supported
https://github.com/neumino/thinky/issues/421#issuecomment-171334263
