### ISSUE TITLE
Add camelcase options to thinky.createModel

### ISSUE THREAD

**Issue by nodesocket** [neumino/thinky#562]
The options that `thinky.createModel()` takes include:

    enforce_missing
    enforce_extra
    enforce_type

Can we get aliases that are properly camelcase _(ex `enforceExtra`)_? Non-camelcase causes my linter to complain and really camelcase is the JS standard.

**Comment by neumino** [comment]
These options are deprecated, in favor of `required()`, `optional()` etc.
It looks like I missed some at the top domain for the model though.

**Comment by nodesocket** [comment]
Correct, how can I add this requirement on the top domain model? Using `enforce_extra ` was the only thing I seemed to work.
