### ISSUE TITLE
Question: how to make shareable schema (not models)

### ISSUE THREAD

**Issue by no-more** [neumino/thinky#566]
Hi,

I want to share some schema across multiple projects, in order to do this I have created a standalone project to old them. But the problem I have is that I need an instance of thinky to create them as it's the only way to access "type" and "r" which I need to create a schema.
My question is: is there a way to access type and r without creating an instance of thinky first ?
Of course I could pass thinky to a function parameter which will then create my schema, but this is a lot more complicate to do, and I would like to use thinky instance only when creating the model.

I'm not sure if my question is clear

Thanks for your help.

**Comment by grantcarthew** [comment]
Hi @no-more,
Is there a reason you can't just use the RethinkDB driver directly?
There are two popular drivers at the moment.

*   [rethinkdbdash](https://www.npmjs.com/package/rethinkdbdash)
*   [rethinkdb](https://www.npmjs.com/package/rethinkdb)

The `dash` version is made by @neumino and is very good with a heap of extra features. It is also the driver used in `Thinky`.

The `rethinkdb` driver is the official one.

If you use one of these drivers you can connect to the database without using `Thinky`.

**Comment by neumino** [comment]
Hum, you can't really access `type` and `r` without creating an instance of thinky.

What you want to do is probably just create a js file where you create an instance of thinky, and export this instance.
You can then import this file and get the instance to build your schema.
