### ISSUE TITLE
Performance of getJoin() with thousands of children

### ISSUE THREAD

**Issue by nodesocket** [neumino/thinky#569]
By default does Thinky support pagination or any sort of limiting using getJoin() when a model has thousands or even tens of thousands of children?

**Comment by neumino** [comment]
getJoin is always using an index under the hood.
Using `skip`/`limit` is fine, but if you are dealing with million of documents, you may want to craft your own pagination with `between`/`limit`.

Then I guess the only way to know if that works for you is just actually test it.
