### ISSUE TITLE
Define field that cannot be empty string

### ISSUE THREAD

**Issue by nodesocket** [neumino/thinky#576]
````javascript
label: type.string().required().allowNull(false)
````

Using the above allows `{"label":""}`

Is that really the correct behavior? Would expect this to fail validation.

**Comment by neumino** [comment]
Yes, an empty string is not `null` and is a valid string. `allowNull` refers to the `null` values, nothing else.

**Comment by nodesocket** [comment]
Well, what about `.required()`? To me that would mean not `""` since it is not very useful.

At any rate, is there an option then to say not empty string.

**Comment by neumino** [comment]
http://thinky.io/documentation/schemas/
There's nothing prebuilt for empty string. You need to add your own validator.

**Comment by nodesocket** [comment]
I'd be happy to create a pull request, if you can show me where to add another validator on `type.string` for empty.

Thinking the following API to mirror `allowNull()`.

````javascript
type.string().allowEmpty(false)
````

Though this API feels strange as it requires passing `false`. I'd rather have it:

````
type.string().noEmpty()
````

**Comment by nodesocket** [comment]
@neumino created a PR: https://github.com/neumino/thinky/pull/578

**Comment by neumino** [comment]
You can actually use `type.string().min(1)` I think.

You can also just import `validator` for example and do `type.string().validator(validator.isEmail)`. There's no reasosn to bloat thinky with many validators when you can import them.

**Comment by nodesocket** [comment]
Thanks for the reply.`type.string().min(1)` works.

````shell
➜  ~ curl -i http://127.0.0.1:9000/projects -X POST -H "Content-Type: application/json" -d '{"account":"1cd6c094-b49e-455b-af1c-0bda37fb7e05", "label":""}'
HTTP/1.1 400 Bad Request
Connection: close
Server: Node.js
Cache-Control: no-cache, no-store
Strict-Transport-Security: max-age=15780000
Content-Type: application/json
Content-Length: 79
Date: Fri, 14 Oct 2016 07:18:04 GMT

{"code":"BadRequest","message":"Value for [label] must not be shorter than 1."}
````

Deleted PR.
