### ISSUE TITLE
Virtual field with current rows id

### ISSUE THREAD

**Issue by nodesocket** [neumino/thinky#577]
I'm trying to add a virtual field to all models that returns the `url` to the row itself.

````javascript
const Account = module.exports = orm.createModel('accounts', {
    id: type.string().uuid(4).default(() => {
        return uuid.v4();
    }),
    created: type.date().default(orm.r.now()),
    url: type.virtual().default(() => {
        return `/accounts/${this.id}`;
    })
}, {
    enforce_extra: 'strict' // jshint ignore:line
});
```

The field `url` should be `/accounts/79c852a1-37cf-4193-a5af-4ac0145569ae` but getting `/accounts/undefined`.

**Comment by nodesocket** [comment]
Argg figured it out. Caused by using ES6 `() => {}` syntax.

It would be awesome if instead of magically using `this`, if instead the document was passing into `.default()`.

**Comment by neumino** [comment]
Hum, this is a pretty standard use of `this`. There's another bug to track document for that.
