### ISSUE TITLE
Question about adding existing documents to a table with saveAll()

### ISSUE THREAD

**Issue by curtwagner1984** [neumino/thinky#580]
Hello.I'm very new to thinky and rethinkDb, I'm trying to build a local media center using electron and thinky and I'm having trouble saving models joined with existing documents. 

For example, I have a Movie table and an Actor table, both have n-n relationship defined in the model:
```javascript
// models/movie.js

var Movie = thinky.createModel("Movie", {

    name: type.string().required(),
    path_to_file: type.string().required(),
}

var Actor = require(__dirname + '/Actor.js');
Movie.hasAndBelongsToMany(Actor, "actors", "id", "id");
```

```javascript
// models/actor.js
var Actor= thinky.createModel("Actor", {

    name: type.string().required(),
    age: type.number(),
   	gender: type.string()
}

var Movie = require(__dirname + '/Movie.js');
Actor.hasAndBelongsToMany(Movie, "movies", "id", "id");
```

Then I'm fetching a movie and all the actors. If one of the actors is present in the movie filename, I'm trying to add that actor to the movie. This, however, keeps getting a `DuplicatePrimaryKeyError: Duplicate primary key id` error every time I'm trying to save the joined document.

```javascript
// main.js

var allActors = [];
r.table(models.Actor.getTableName()).orderBy(r.desc(function (doc) {
            return doc("name").split("").count()
        }
    )).then(function (actors){
	allActors = actors;
})



models.Movie.filter({name: "Mr & Mrs Smith"}).run().then(function (res) {
		if (res.length > 0){
		var movie = res[0];

		for (let j = 0 ; j < allActors.length ; j++){
			if (movie.path_to_file.includes(allActors[j].name)){
				if (movie.actors == undefined){
					movie.actors = [];
				}
				movie.actors.push(allActors[j]);
			}		
		}

		movie.saveAll({actors: true}).then(function (res)){
				console.log("Saved " + res)
		}	
	}
});
```
Can anyone help me figuring out what am I doing wrong, or how to overcome this issue?

**Comment by neumino** [comment]
You can use `addRelation` if you want to just add a relation without saving the joined doc.
Alternatively, you can retrieve the joined doc with thinky, and use this as a joined document (instead of a pure JS object - that thinky will try to save)

**Comment by curtwagner1984** [comment]
@neumino Thank you.  After some fiddling, I realized that the problem was `r.table(models.Actor.getTableName())` because it return pure JS objects and not models. I changed it to `models.Actor` and now the `saveAll()` works just fine.
