### ISSUE TITLE
Model.post('validate' function being called twice (bug)

### ISSUE THREAD

**Issue by nodesocket** [neumino/thinky#581]
Using the `Model.post('validate'` hook with a custom function, I noticed it is being called twice when invoked with a single `new Model`.

````javascript
Model.post('validate', function(next) {
    console.log('in Model post validate'); // printed twice
    return next();
});
````

You'll see the `console.log()` twice.

**Comment by neumino** [comment]
I guess what you mean is that the hook is called twice when you save a document.
There's one validation happening before saving, and one after on retrieve.

So that's working as intended.

**Comment by nodesocket** [comment]
How then do I only have the hook called before saving? Is that possible.
