### ISSUE TITLE
prototype being mutated on model construct

### ISSUE THREAD

**Issue by contra** [neumino/thinky#584]
## What you are doing?

```js
let o = { id: '123', name: 'test' }
console.log(o.__proto__) // {}
let u1 = new User(o)
console.log(o.__proto__) // model prototype
```

Thinky shouldn't mutate data given to it. Tested on the latest version. Found when tests started failing, so this is a regression that happened in the last few months AFAIK.

Offending code: https://github.com/neumino/thinky/blob/master/lib/model.js#L105

**Comment by neumino** [comment]
This is somehow working as intended. The main reason behind the current behavior is that the document fed to thinky is often a JSON payload that's not used anywhere else.

```
var a = new Model(b);
b === a // true;
```

**Comment by neumino** [comment]
You can make a defensive copy before using `new Model`

**Comment by contra** [comment]
@neumino Seriously, you think this is okay and shouldn't be fixed? This is a huge issue and causes a ton of problems, no other libraries do this.

**Comment by neumino** [comment]
You're welcome to send a PR to add an option to make a defensive copy of
the doc inside what Model.new returns.

Also describing a use case would help better understand this issue.

**Comment by contra** [comment]
It's okay - this is like the fifth issue I've opened to try and help out with this library and you close every one of them basically saying "nah, its not really a problem - no need to fix it". I'd love to send PRs but you don't seem interested in merging any of them so I won't waste my time or yours.

I'll just use something else, message received - no malice intended, I totally understand if you don't have the time to care about it.
