### ISSUE TITLE
User and Password

### ISSUE THREAD

**Issue by gperreymond** [neumino/thinky#586]
Hi all,

I tryed and failed to use user and password in thé options.  
I just checked the code and I don't see anything about this, you just use the authkey.

Have you planned to add this feature ?

Regards

**Comment by neumino** [comment]
It's supported. The syntax is the same as with rethinkdbdash.

**Comment by gperreymond** [comment]
Yeah I tryed and didn't work, if I use an authkey it works.
I Will take a look on my configuration in rethinkdb.

Thanks

**Comment by jnsq** [comment]
It's part of the [rethinkdb api documentation](https://rethinkdb.com/api/javascript/#connect), but it's not on the [thinky api documentation](https://thinky.io/documentation/api/thinky/#r). And `authKey` no longer appears on rethinkdb official api documentation. Any reason to keep this option in Thinky ?

**Comment by neumino** [comment]
No reason, I forgot to update the doc. Done.
