### ISSUE TITLE
Hooks / Events for "first save"

### ISSUE THREAD

**Issue by isaackwan** [neumino/thinky#590]
Hello,

I am wondering if there are any event / hooks (`pre`/`post` etc) that targets the "first save" event? A quick use case would be something like GitHub issues - an email notification should be sent when a new reply is posted, but not during subsequent edits.

Sorry I'm not sure if this is the best place to ask this - please let me know if there are more appropriate support channels.

Isaac

**Comment by neumino** [comment]
I guess you could use create a hook with `isSaved`. If it return false, send an email, else don't.
