### ISSUE TITLE
Thinky doesn`t respect default() method

### ISSUE THREAD

**Issue by smashercosmo** [neumino/thinky#592]
Consider the following example:
```
User.get('non-existent-user').default({}).execute();
```
Promise is rejected with "The query did not find a document and returned null." error even if default() is used. Is it expected behaviour?

Thinky version is 2.2.8

**Comment by neumino** [comment]
Yes it is, get is overloaded in thinky. Use _get if you don't want the
default though it's not recommended.

**Comment by smashercosmo** [comment]
Ok, thx for explaination
