### ISSUE TITLE
Inconsistent documentation, please clarify

### ISSUE THREAD

**Issue by csaintc** [neumino/thinky#594]
## Question

I'm currently trying to configure my thinky, and the documentation is very inconsistent:

Here, it says to configure buffers it's `min`, `max` and `bufferSize`:

https://thinky.io/documentation/api/thinky/

However, I can't find any instances of you using those configurations.

All I can find is you passing those configs to rethinkdbDash, in which case they are incorrect according to your comment here: 

https://github.com/neumino/thinky/blob/master/lib/thinky.js#L9

It seems to me that the api documentation for thinky is just plain wrong. Could you confirm for me?

Thanks a bunch!

**Comment by neumino** [comment]
The code is the source of truth.

The whole config is passed to rethinkdbdash
https://github.com/neumino/thinky/blob/master/lib/thinky.js#L48

I just pushed an update for thinky.io
