### ISSUE TITLE
Question: Connection object

### ISSUE THREAD

**Issue by LoganArnett** [neumino/thinky#596]
Does thinky return a `conn` object like the `r.connect({}, function(err, conn) {})` I am trying to use the `.run` with a project containing thinky and it looks like I need to use the callback in order to use the `new_val` and `old_val`

**Comment by neumino** [comment]
Thinky is using rethinkdbdash's connection pool under the hood, so there's no connection to manipulate.

Are you talking about a changefeed for `new_val`/`old_val`? Or a write operation? Can you write a snippet of what you are trying to do?

**Comment by LoganArnett** [comment]
Trying to do something like this:

``` js
const model = require('model');

model.changes().run(conn, function(err, cursor) {
  // check for insert and emit an event with socket.io
  // and
  // check for remove and emit another event with socket.io
});
```

**Comment by neumino** [comment]
You're probably looking for this:

```
const model = require('model');

model.changes().run().then(function(feed) {
  // Thinky feed
}).error(function(error) {
  // Handle error
});
```

Or if you want the same interface as with RethinkDB
```
const model = require('model');

model.changes().execute().then(function(feed) {
  // RethinkDB feed
}).error(function(error) {
  // Handle error
});
```
