### ISSUE TITLE
Integrate Regrid to store and stream big files

### ISSUE THREAD

**Issue by janek26** [neumino/thinky#602]
Or another filesystem for RethinkDB. 

Advances to buffer -> You can stream data o or from the database

ReGrid -> https://github.com/internalfx/regrid

**Comment by grantcarthew** [comment]
That's not really in the scope of `thinky`.

There are many blob stores to choose from. I wrote my own, [scalable-blob-store](https://www.npmjs.com/package/scalable-blob-store), not to mention Amazon or Azure.

https://www.npmjs.com/search?q=blob+store


If someone would like to use `regrid` they can simply add the module.

**Comment by neumino** [comment]
Like @grantcarthew, there's no reason to merge these two modules together. If someone needs both, they should just import both.
