### ISSUE TITLE
Cannot access the resulting id rethinkdb assigned to a just saved object when {enforce_extra: "remove"}

### ISSUE THREAD

**Issue by fabioespinosa** [neumino/thinky#604]
## Bug report

When having the option of {enforce_extra: "remove"} in the createModel method, one cannot access an id of a just saved object. 

I checked with {enforce_extra: "strict"} and it works fine, but not with "remove" option. I figured it must be a bug then. 

Look at the following example:

```
var Post = thinky.createModel('Post', {
  content: type.string()
}, {enforce_extra: "remove"});

exports.add = (req, res) => {
  var post = new Post(req.body);
  post.save().then(result => {
    
    // I need the id of the newly created post so I can return it back
   // But with "remove" option on the schema it results in undefined
    req.params.idPost = post.id;
    module.exports.get(req, res);

  }).error(err => {
    console.log(err);
    res.status(500);
    res.send();
  });
}

```

I can find a workaroung using strict, however it would be amazing if someone can correct this bug.

**Comment by neumino** [comment]
You need to define the id in the schema.

**Comment by fabioespinosa** [comment]
Thanks @neumino worked like a charm
