### ISSUE TITLE
Unhandled rejection ReqlRuntimeError

### ISSUE THREAD

**Issue by DerEnderKeks** [neumino/thinky#605]
Hello,

I'm currently trying to dockerize [Yanius](https://github.com/DerEnderKeks/Yanius) but there somehow is a problem with the rethink stuff.

It always throws an exception during startup and I have no idea why and where it comes from as the node stacktrace is quite useless... If I start it in my normal environment everything works just fine (same node, rethink and npm module versions).

Can anyone tell me where that `ReqlRuntimeError` comes from and maybe how to fix it? Sourcecode is available in the previously mentioned repository. (It's a mess. I know.)

```
web_1  | > Yanius@2.1.1 start /usr/src/app
web_1  | > node --harmony ./bin/www
web_1  | 
web_1  | Creating a pool connected to db:28015
web_1  | Unhandled rejection ReqlRuntimeError
web_1  |     at Connection._processResponse (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:395:15)
web_1  |     at Socket.<anonymous> (/usr/src/app/node_modules/rethinkdbdash/lib/connection.js:201:14)
web_1  |     at emitOne (events.js:96:13)
web_1  |     at Socket.emit (events.js:189:7)
web_1  |     at readableAddChunk (_stream_readable.js:176:18)
web_1  |     at TCP.onread (net.js:551:20)
web_1  |     at Function.module.exports.loopWhile (/usr/src/app/node_modules/deasync/index.js:72:22)
web_1  |     at module.exports (/usr/src/app/util/setup.js:100:11)
web_1  |     at Object.<anonymous> (/usr/src/app/app.js:38:56)
web_1  |     at Module._compile (module.js:571:32)
web_1  |     at Object.Module._extensions..js (module.js:580:10)
web_1  |     at Module.load (module.js:488:32)
web_1  |     at tryModuleLoad (module.js:447:12)
web_1  |     at Function.Module._load (module.js:439:3)
web_1  |     at require (internal/module.js:20:19)
web_1  |     at Object.<anonymous> (/usr/src/app/bin/www:8:13)
web_1  |     at Module._compile (module.js:571:32)
web_1  |     at Object.Module._extensions..js (module.js:580:10)
web_1  |     at Module.load (module.js:488:32)
web_1  |     at tryModuleLoad (module.js:447:12)
web_1  |     at Function.Module._load (module.js:439:3)
web_1  |     at Module.runMain (module.js:605:10)
```

**Comment by neumino** [comment]
What version of thinky/rethinkdbdash are you using here?

**Comment by DerEnderKeks** [comment]
```
+-- thinky@2.3.8
| +-- rethinkdbdash@2.3.27
```

**Comment by mmahalwy** [comment]
I have the same problem. It's a HUGE pain to find where the source is...

**Comment by mrsum** [comment]
Same problem

**Comment by neumino** [comment]
Can you provide a script that reproduce this error?

**Comment by DerEnderKeks** [comment]
I can't because I don't know what exactly causes this exception and where it's caused. The line number in the stacktrace leads to [this](https://github.com/DerEnderKeks/Yanius/blob/1f64831dd8a6796aa188d209f8d27622eada1cfe/util/setup.js#L100):

```
  deasync.loopWhile(() => { // this line
    return !configSaved; 
  });
```

And this line is not doing anything with thinky directly but it waits for the result of the query above it.

**Comment by neumino** [comment]
If you look at the code in rethinkdbdash, it's an error returned by RethinkDB.
Can you just print the error there? There error should come with a backtrace of what query failed.

**Comment by DerEnderKeks** [comment]
Where exactly is this error message supposed to be? The stacktrace I posted above is everything it logs.

**Comment by neumino** [comment]
/usr/src/app/node_modules/rethinkdbdash/lib/connection.js line 395

**Comment by Steinweber** [comment]
I get the same error after some IDLE time

**Comment by DerEnderKeks** [comment]
alright, after finding out that I forgot to add an error handler in one of my database functions I now got the exact error message:
```
msg: 'Cannot perform read: primary replica for shard ["", +inf) not available',
message: 'Cannot perform read: primary replica for shard ["", +inf) not available in:\nr.table("config").delete()\n^^^^^^^^^^^^^^^^^^^^^^^^^^\n',
frames: [],
 name: 'ReqlOpFailedError'
```
