### ISSUE TITLE
validator on top

### ISSUE THREAD

**Issue by Steinweber** [neumino/thinky#606]
How to validate on top of a model?
Like
```javascript
const Contact = thinky.createModel("contact", {
    id: type.string().required(),
    gender: type.string().required(),
    company: type.string(),
    firstname: type.string().required(),
    lastname: type.string().required()
}).validator(args => {
    return !(args.gender === 'company' && args.company.length === 0);
});
```

**Comment by neumino** [comment]
const Contact = thinky.createModel("contact", type.object({
    id: type.string().required(),
    gender: type.string().required(),
    company: type.string(),
    firstname: type.string().required(),
    lastname: type.string().required()
}).validator(args => {
    return !(args.gender === 'company' && args.company.length === 0);
}));
```
