### ISSUE TITLE
Thinky is no longer maintained for now

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#609]
Hello folks,

I created and have been maintaining thinky during my free time but recently (well for the past year at least), I haven't been updating thinky that much, mostly because:
- My priorities have changed. I have less time allocated to work on arbitrary open source projects.
- My projects that were relying on thinky moved to just rethinkdbdash mostly because ReQL is expressive enough such that an ORM is not as useful as with other databases.

The reasons don't matter that much, at the end of the day, thinky is not really moving. I think it's probably better for me to release the project and officially mark it as not being maintained - @grantcarthew made me realize that they were a few PR opened...

I'm not sure what will happen from here. If someone is interested in maintaining it, I'm happy to give write/admin access to the repo/npm (though I would like that person to have sent at least one PR in the past and/or to be actively picking up incoming PR/issues/questions).

I'm happy to answer any questions. Hopefully the project will keep sailing :)

_Note: I'll keep maintaining rethinkdbdash as it's fairly stable and doesn't much place to grow - which is not the case for thinky since there are plethora of features that could be added._

**Comment by gokaygurcan** [comment]
http://www.nooooooooooooooo.com

**Comment by cur3n4** [comment]
If no one else does, I would be interested in maintaining it.

**Comment by ralphholzmann** [comment]
Bummed to hear, but thanks so much for your work up to this point. Best of luck.

**Comment by martinshkreli** [comment]
good luck

**Comment by wookoouk** [comment]
I'm in as a maintainer, I use thinky every day.

**Comment by lirantal** [comment]
So, updates on new maintainers who can tackle issues and PRs?

**Comment by wookoouk** [comment]
@neumino, Please give someone access, the feature requests and bugs are starting to pile up, If not I will start my own fork, I intend on adding es6 support asap.

Hope things are going ok with you since you departed the project, and we do all appreciate your efforts (like I said before, thinky is used heavily in 8-10 services at my institute.

**Comment by neumino** [comment]
Hum, and who should I give access to?

So far I don't see anyone answering questions/issues/PR. I can give access to anyone as long as they are willing to maintain the project.

**Comment by wookoouk** [comment]
Would you prefer someone to take over support and you just handle accepting PRs or do you want somone to take over the lead?

**Comment by gokaygurcan** [comment]
@neumino why are you trying to pick someone specific. Just give write access to everyone here who's willing to contribute and they'll/we'll handle the rest. So the project can be under your name but people can manage it. 

The important part is keeping this project alive and maintaining it imho, I really don't care who and how.

**Comment by neumino** [comment]
@wookoouk -- no I would like to give full access to someone (or multiple persons), including the npm package.

@gokaygurcan -- I can give access to anyone who's willing to maintain the project. I think some people have expectations on thinky's stability and the fact that it's a good package without any evil piece of code inside. Someone should make sure that it's still the case.

I think the bar is pretty low at the moment but so far no one is answering issues or commenting on PRs...

**Comment by gjuchault** [comment]
Hi @neumino and everyone here.
As stated in [HackerNews](https://news.ycombinator.com/item?id=14543545), I've been writing a small ORM for RethinkDB that would fix the main issues I had with Thinky (3-way relationships). I couldn't get this working on Thinky.
I'd like to make huge thanks to Thinky (especially the extending of rql methods) and neumino's blog :)
Feel free to take anything back here 👍

**Comment by grantcarthew** [comment]
@gjuchault A couple of questions:
*   What's the current status of the project?
*   Is this a personal project or are you funded?
*   What is your expected support strategy?

**Comment by gjuchault** [comment]
Maybe that should not be on this thread, I was just offering help to the future maintainer of thinky.

**Comment by marshall007** [comment]
@gjuchault nice work, this looks great!

**Comment by lirantal** [comment]
@neumino needless to say, I totally appreciate all of your work with thinky and the rethinkdb community, but basically not taking any action is going to render the project hopeless, deprecated and will motivate others to fork or create new projects which will just defragment the community even more (which I'm not sure is a good thing for a niche and small community as rethinkdb is).

IMO at this point, taking no action is just as bad if not worse than choosing the "wrong" maintainers.
Just take a leap of faith with whomever stood-up for the job and let's see how it works out (and you can anyway keep in the background to mentor and advice).

**Comment by neumino** [comment]
@lirantal What are you recommending then?

**Comment by lirantal** [comment]
Well @cur3n4 and @wookoouk volunteered to maintain the project, we can start with adding them as contributors so they can review and merge PRs and take active part in issues backlog.

Also, we can reach out to the community on reddit/twitter and see if more volunteers would apply for the job.

**Comment by joseluisq** [comment]
I used Thinky too but it's true, the ReQL is good enough and [rethinkdbdas](https://github.com/neumino/rethinkdbdash) it could be the next step for...

**Comment by lirantal** [comment]
That doesn't contradict the fact that there are many users of rethinkdbdash who want to keep using it but would like to make sure the project is maintained.

**Comment by joseluisq** [comment]
> That doesn't contradict the fact that there are many users of rethinkdbdash who want to keep using it but would like to make sure the project is maintained.

Of course, the project must continue...
In fact, Thinky has many users. For example I'm using it in my projects too.

**Comment by knowroozi** [comment]
@neumino Has this been transferred to new maintainers or should I look for an alternative?

**Comment by neumino** [comment]
@knowroozi no, there's no maintainer at the moment.

**Comment by grantcarthew** [comment]
@neumino If you don't add a maintainer soon this repo is going to be a ghost town and your concern about someone responsible being in charge will be moot.

**Comment by neumino** [comment]
@grantcarthew - Are you interested in maintaining it?

**Comment by grantcarthew** [comment]
I'm happy to be added to the list. We also have above both @cur3n4 and @wookoouk who are keen. My time is limited however.

**Comment by neumino** [comment]
@cur3n4, @wookoouk still interested?

@grantcarthew, I just sent you an invite - I'm not super familiar with all the write/read access, but if I didn't mess up, you should be able to push code now.

**Comment by wookoouk** [comment]
I am still in!

**Comment by neumino** [comment]
@wookoouk, Done

**Comment by wookoouk** [comment]
Thank you, for me priority is going through the PRs and working oldest-newest through the issues, I believe there are many than can be closed (mostly due to feature requests that are not 'important' for maintaining the project in its current state). Thoughts?

**Comment by grantcarthew** [comment]
@wookoouk Anything you can do is great.
I just merged a security update however there is way to much work needing attention.
The more maintainers the better.

**Comment by cur3n4** [comment]
Sorry I somehow missed this, I am still in as well.

**Comment by grantcarthew** [comment]
@neumino I noticed that @cur3n4 has been working on PR #588 , can you add him in as a maintainer please?

**Comment by cur3n4** [comment]
@neumino That would be great

**Comment by grantcarthew** [comment]
ping @neumino

**Comment by neumino** [comment]
Done, sent an invite

**Comment by cur3n4** [comment]
Thanks a lot @neumino
