### ISSUE TITLE
Site Down?

### ISSUE THREAD

**Issue by wookoouk** [neumino/thinky#622]
This site can’t be reached

thinky.io’s server DNS address could not be found.
Search Google for thinky io
ERR_NAME_NOT_RESOLVED

**Comment by grantcarthew** [comment]
Just checked here in Australia. Same deal. Name is still classed as taken in godaddy.

**Comment by neumino** [comment]
You can access the gh-pages directly: https://neumino.github.io/thinky (your browser may be caching a bad redirect though)

**Comment by aikepah** [comment]
@neumino the links on your new site are just incorrect. ie: http://blog.justonepixel.com/thinky/ works, but then links from there go to http://blog.justonepixel.com/documentation/ when it should go to http://blog.justonepixel.com/thinky/documentation

**Comment by Morgul** [comment]
I've tried thinky.io on several of my development machines, and it doesn't seem to be redirecting. I had been using documentation from the internet archive until finding this issue.

**Comment by aikepah** [comment]
It looks like this is fixed as long as you go to https://neumino.github.io/thinky or http://blog.justonepixel.com/thinky/

**Comment by janek26** [comment]
Whois looks like the domain wasn't paid and is pending to to delete:

```
Domain : thinky.io
Status : pendingDelete
Expiry : 2017-04-23
Delete : 2017-07-23 00:30


Domain reserved

Check for 'thinky.sh' --- http://www.nic.sh/go/whois/thinky.sh
Check for 'thinky.ac' --- http://www.nic.ac/go/whois/thinky.ac
```

**Comment by neumino** [comment]
Updated the link, www.justonepixel.com/thinky or neumino.github.io/thinky
