### ISSUE TITLE
Add URL to Github repo

### ISSUE THREAD

**Issue by benjick** [neumino/thinky#623]
Can you add the URL to the documentation to the top description?

Example: https://github.com/facebook/react

<img width="1008" alt="screen shot 2017-06-12 at 11 21 45" src="https://user-images.githubusercontent.com/430872/27027372-72c0853a-4f61-11e7-9483-c717eb265a4a.png">

**Comment by neumino** [comment]
Thanks, I didn't know that was an option. Done.
