### ISSUE TITLE
How many connected pools are ok?

### ISSUE THREAD

**Issue by dunklesToast** [neumino/thinky#632]
Hey,

I have a question: How many connected pools per Process are ok? I have a shared thinky instance, but anyway it creates about 10 connected pools and if I use the program in a cluster there are up to 40 pools connected. Could this lead to problems and how many pools are ok?

dunklesToast

**Comment by neumino** [comment]
What matters is not the number of pool but more the number of connections.
It mostly depends on max file descriptors.

You may be interested in this too:
http://justonepixel.com/thinky/documentation/architecture/
