### ISSUE TITLE
Duplicate primary keys

### ISSUE THREAD

**Issue by mshick** [neumino/thinky#65]
I'm trying to implement some code to ensure that unique docs are created using the primary key. Ideally I'd look for a creation error, modify the key, and try again or fail entirely. Per an earlier discussion, checking for existence alone, before creating, could lead to race conditions.

The problem is, Thinky seems to be quietly swallowing the dupe key errors. So, if I do:

```
// primary key is 'id'
var data = { id: '123', title: 'Foo' };
var model = new Model(data);
model.save().then(function () {
  var model2 = new Model(data);
  model2.save();
});
```

I would expect model2 to trigger an error of some sort, since I tried to create a new model with that duped key. It completes just fine though (but if data has changed, no update will be made).

I know the rethinkdb library is a bit weird about returning errors like this, perhaps that's the problem? 

https://github.com/rethinkdb/rethinkdb/issues/899 (an issue neumino opened, actually ;) )

**Comment by gebrits** [comment]
:+1: for consistent error interface
