### ISSUE TITLE
Store 'old' values somewhere (hidden) on merged & updated models

### ISSUE THREAD

**Issue by mshick** [neumino/thinky#66]
Mirroring the rethink query results a bit, it would be very useful to me to store a hidden, non-enumerable property somewhere on the model that contains the "old_val" from an update.

Use case here, if I want to trigger later code based on "dirty" fields, or certain field updates.

So, maybe if I did this:

```
var model = new Model({ title: 'Foo', body: 'Super cool.' });
model.save();
...
model.merge({ title: 'New Title' });
model.save().then(function (saved) {
  console.log(saved.__was);
  // prints: { title: 'Foo', body: 'Super cool.' }
  console.log(saved)
  // prints: { title: 'New title', body: 'Super cool.' }
});
```

I say it should be 'hidden' because it's not necessarily information we'd want printing anywhere, or becoming a first-class, enumerable object property.

**Comment by gebrits** [comment]
Couldn't this be used to check for isDirty? #73 . (e.g.: check the diff?).
