### ISSUE TITLE
Cache results

### ISSUE THREAD

**Issue by neumino** [neumino/thinky#7]
That would be an awesome feature, but 
- It's tricky to implement
- I'm worried that users will not manually destroy elements meaning that their app will leak

If we cache results, we can make sure that users never have a duplicate reference. Even if 2 documents have the same joined document, we can provide a unique joined document reference.

It would be awesome with triggers too, but that's another story I guess.

**Comment by xpepermint** [comment]
Any progress on this?

**Comment by neumino** [comment]
No progress on this.
If someone can suggest how the cache should behave, we could reconsider an implementation, but for now there are too many pitfalls any suggestions I saw/had.

**Comment by neumino** [comment]
Closing as this probably won't happen.
