### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by anweiss** [neumino/thinky#72]
Is there any consideration for developing TypeScript definitions for thinky?
https://github.com/borisyankov/DefinitelyTyped

If so, I'd love to help out but have no idea where to start lol

**Comment by 20zinnm** [comment]
Did anything happen with this?

**Comment by d3viant0ne** [comment]
@20zinnm - I've been running with @ExoZoneDev's https://github.com/ExoZoneDev/typings-thinky also and https://github.com/ExoZoneDev/typings-rethinkdbdash. Though it would be optimal to get all of the above into @types
