### ISSUE TITLE
Model.get() of non-existent id needs better handling

### ISSUE THREAD

**Issue by davewasmer** [neumino/thinky#90]
Right now, if you try to `Model.get()` with an id that doesn't exist, an error is thrown:

``` javascript
// assume a Post Model
Post.get("nonExistingId").run().error(function(error) {
  // error: Cannot build a new instance of `posts` with `null`.
});
```

See: https://github.com/neumino/thinky/blob/master/test/query.js#L127

This is less than ideal - it's difficult and brittle to test for this condition, and the error message is confusing. I spent a while trying to understand what I was doing wrong, only to realize this is expected behavior.

Ideally, this wouldn't result in an error condition. It should simply resolve the promise with `null`. At the very least, the error message should be updated to something a bit clearer and easier to test for (e.g. `"id not found"` or something similar).

Happy to take a stab at a PR, but wanted to make sure I wasn't missing anything before I dove in.

**Comment by anasbud** [comment]
Hi there,  sorry for reopening an old issue. 

I just wanted to know if it's possible that empty result `[]` (when using filter) would be considered as a "DocumentNotFoundError" Error. 

That would be logical to consider the empty array as a DocumentNotFoundError after all...

**Comment by neumino** [comment]
You can hack something like this:
```
Users.filter(...).coerceTo("ARRAY").do(function(result) {
  r.branch(
    result.count().eq(0),
    r.error("The query did not find a document and returned null."),
    result
  )
})
```

**Comment by neumino** [comment]
Or replace `"The query did not find a document and returned null."` with new thinky.Errors.DocumentNotFound().message

**Comment by neumino** [comment]
For context, the main reason we throw when get returns null is because we can't chain a few methods after null but can after an empty sequence.
